### ISSUE TITLE
Log HTTP -> HTTPS redirects

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1013]
In our infrastructure, HTTP -> HTTPS redirects are generally a bug, because the app servers should not be accessible over HTTP. This can cause strange bugs like self-imploding 301 caching. To help track this down, we should add logging any time we would redirect to HTTPS.

There are two ways to do this:

1. Modify the Django middleware that is doing this redirect.
2. Install a separate middleware that logs all HTTP requests that would be redirected, independent of the middleware doing the actual redirecting. This should exclude URLs in `settings.SECURE_REDIRECT_EXEMPT`, which we use to filter out endpoints that are hit directly via HTTP by automation.

Reaching into Django internals is usually a bad idea, so I suggest we go with option 2.

@relud Can you specify what kind of logging you'd like to get out of this?

**Comment by relud** [comment]
ideally we would see absolutely everything you can get, especially body and headers
