### ISSUE TITLE
Need to double click on new recipe button to create recipe.

### ISSUE THREAD

**Issue by marcrowo** [mozilla/normandy#1019]
After one click of the "New Recipe" button: 

![screen shot 2017-08-31 at 11 29 13 am](https://user-images.githubusercontent.com/1198628/29939132-bd95a21c-8e3f-11e7-8b39-da75d6b1982a.png)

Console error:
`TypeError: action.get(...) is undefined        RecipeForm.js:153`

**Comment by andymikulski** [comment]
This appears to be an easy fix, but I suspect the issue appears when there are no previously loaded recipes/actions and I haven't wiped my DB to test this out.

However, the fix should be as simple as changing from `value={action.get('id').toString(10)}` to `value={action.get('id', '').toString(10)}`

**Comment by marcrowo** [comment]
@andymikulski This seems to work! Just tested by deleting all the recipes in my database and replacing that line.
