### ISSUE TITLE
Collapse migrations

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1023]
We have a bunch of migrations. We should collapse most of them. This will speed up tests and new developer set up, and let us remove some older libraries.

We should probably keep migrations back to the last major deployed version (v55). Anything prior to that we can collapse.

**Comment by rehandalal** [comment]
I'm guessing the "v55" part of the description is obsolete at this point?

**Comment by mythmon** [comment]
Yeah v55 is out of date now. The current deployed version is v79. This info can be gotten from  https://normandy.cdn.mozilla.net/__version__
