### ISSUE TITLE
Add Pioneer tab to about:studies

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1025]
We need to add a new tab to `about:studies` that lists the Pioneer studies that a user has participated in (or is currently participating in). [Here's a mockup](https://mozilla.invisionapp.com/share/UC9XM7O9X#/screens/241294331) using the pre-Photon styling for about:studies.

Open questions:
- Should the tab be visible even if the user has not enrolled in Pioneer?
- Is the Learn more link enough of an explanation for what Pioneer is?
- What text should go next to the checkbox for controlling enrollment?
- What URL should the Learn more link go to? A SUMO page?
- Do we expect the page to list Pioneer studies that a user has not participated in _yet_ but are available? Put another way, are users supposed to be able to specifically choose to participate in a single study?
- If a user unchecks the opt-in checkbox, should their studies end immediately? If they then re-check them, should they be re-enabled again, or only on next run?
- Can a user re-enter a study after they've exited it?

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435877
