### ISSUE TITLE
Pioneer-specific study action

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1027]
We will need to add a new action to Normandy for enrolling users in an individual Pioneer study. It should be similar to the opt-out-study action, with the following changes:

- It should abort if the user does not have the Pioneer opt-in preference set.
- It should mark the installed study as a Pioneer study using the new API from #1026.
- The pre- and post- handlers should only operate on Pioneer studies, not normal ones.
  - We'll also need to update the opt-out action to ignore Pioneer studies.

**Comment by mythmon** [comment]
We have shipped a couple pioneer add-ons now. They have checks in the recipes' filter expressions and also in the add-ons themselves via pioneer-utils. I don't think we need a third check that the pioneer opt-in is set. I also don't think the #1026 is going to go anywhere. Closing this out as wontfix.
