### ISSUE TITLE
Set the Pioneer opt-in preference and uninstall the enrollment add-on if it is detected

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1028]
The Shield add-on will need to detect the presence of the Pioneer enrollment add-on. If it is found, we should set the enrollment preference (name TBD) and uninstall the add-on.

We can either do this on startup and register an add-on install watcher, or we can run the check once before every recipe run. I suspect the former has a better UX since the Pioneer tab will immediately show their enrollment.

**Comment by Osmose** [comment]
This is blocked pending some technical decisions as to how we'll be storing the flag that users have opted in to Pioneer.

**Comment by mythmon** [comment]
We've decided to not use pref-based pioneer enrollment at this time.
