### ISSUE TITLE
Add version+channel filter object

### ISSUE THREAD

**Issue by gregglind** [mozilla/normandy#1046]
Release management, PMs and others think about constructs like "57 beta".  I want to make that easier to talk about / filter on / explicitly model.

I want to easily both SPECIFY, and UNDERSTAND "trains affected".  

1.  MAYBE that is a new key called "trains" in the api?
2. Maybe in the filters we can see things like "57 beta", "58 beta", etc.
3. Another possible path:  jexl expression for "trains".    `&& train in ['57-release']` *a la* `locale`

Benefits:
- gets us closer to "experimenter"
- easier dashboarding
- more 'magical' handling of when trains change over  (ie, we stop enrolling)
- less "hand-entered" jexl.

@jaredkerim 
@MattGrimes

**Comment by mythmon** [comment]
@gregglind so I can understand this better, can you explain how treating trains as first class things differs from the below, with the exception of more typing?

```jexl
normandy.channel == 'release' && normandy.version >= '57' && normandy.version < '58'
```

**Comment by mythmon** [comment]
I talked about this with@gregglind in a meeting. The filter I gave in my last comment is functionally the same as what he wants. Mostly this is about better UI and better filtering. I think that filter objects would deal with this nicely, without needing to add any new add-on features.

**Comment by MattGrimes** [comment]
That seems reasonable to me.

**Comment by shell1** [comment]
this case is for if someone wanted to experiment on beta 58 and release 57.  for now - that is not critical.  won't fix unless this has a driving user case.
