### ISSUE TITLE
Firefox Nightly: this.saveStartupPrefs is not a function

### ISSUE THREAD

**Issue by Rob--W** [mozilla/normandy#1058]
When Firefox Nightly starts, the following error is dumped to the console:

> this.saveStartupPrefs is not a function at   PreferenceExperiments.jsm:302

To fix this, add `.bind(PreferenceExperiments)` to line 175 (and also lines 176 - 180 just in case).

https://github.com/mozilla/normandy/blob/a2b399f966d15154fb751a2fad5cba2c55ede068/recipe-client-addon/lib/NormandyDriver.jsm#L173-L181

**Comment by Osmose** [comment]
Thanks for the report! I've got a fix and will be pushing it shortly. :D
