### ISSUE TITLE
Crashing the JEXL parser can result in a 500 code in /api/v2/recipe/

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/normandy#1059]
If you POST an invalid JEXL string like

extra_filter_expression: '"invalid string'

You can crash the JEXL parser and 500 the response:

VisitationError at /api/v2/recipe/
SyntaxError: EOL while scanning string literal (<unknown>, line 1)

Parse tree:
<Node called "string" matching ""TODO - CONVERT TO JEXL
        Browser: 10% of Firefox 57.0 Nightly
        Additional: Locales: slovak, en_us, dansk, so_dj"">  <-- *** We were here. ***
    <RegexNode matching ""TODO - CONVERT TO JEXL
            Browser: 10% of Firefox 57.0 Nightly
            Additional: Locales: slovak, en_us, dansk, so_dj"">

Request Method: POST
Request URL: http://localhost:8443/api/v2/recipe/
Django Version: 1.10.7
Python Executable: /usr/local/bin/python3.6
Python Version: 3.6.0

This should probably be handled more gracefully.

**Comment by mythmon** [comment]
@rehandalal I think this should be a pretty simple try/catch block somewhere during our validation of requests. It should be a good issue for getting back into Normandy.

**Comment by glasserc** [comment]
I will try to work on this.

**Comment by glasserc** [comment]
Can I please have some more detailed steps to reproduce? I went to the Shield console locally and filled out the form to create a recipe called "ethan is testing" with the filter expression `"invalid-string`, but submitting this gets me a 400 with the error `{"extra_filter_expression":["Could not parse expression: \"invalid-string"]}` (which is shown nicely in the form). It seems like this is handled explicitly by the `RecipeSerializer` (see e.g. https://github.com/mozilla/normandy/blob/4a57612c72eecd58ee7add38e28a769afafffcfb/recipe-server/normandy/recipes/api/v2/serializers.py#L144-L161). Are you using some other mechanism to POST the recipe?

**Comment by mythmon** [comment]
I was able to reproduce an error like this by running this code in the browser console of a Normandy tab in Firefox:

```js
fetch('/api/v1/recipe/', {
  method: 'POST',
  credentials: 'same-origin',
  body: JSON.stringify({extra_filter_expression: '"\n"'}),
  headers: {'content-type': 'application/json'},
});
```

Note that the string sent contains the raw characters "double quote, newline, double quote". It seems the problem is having a newline in a Jexl string.

**Comment by glasserc** [comment]
I have tried to put a band-aid on the problem in #1207 as well as opening Osmose/pyjexl#12 to try to address a slightly deeper cause of the symptom.
