### ISSUE TITLE
Update manifest API for hosted extensions

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1061]
We anticipate needing to update in-progress opt-out studies. Add-ons already support [automatic updating](https://developer.mozilla.org/en-US/docs/Extension_Versioning,_Update_and_Compatibility#Automatic_Add-on_Update_Checking). The straightforward approach would be to modify our data model to allow for multiple XPIs (with different version numbers) associated with a single extension, and have the server generate an update manifest that the add-on manifest will link to.

Open questions:
- [ ] Should Normandy be modifying the add-on manifests with the proper update URL / public key? If so, this will probably require that we automate the signing process for opt-out studies.
- [ ] Should Normandy be handling the signature bits of the update manifests? This probably means we'd have to store a private key and rotate it, and also implies that we're updating the XPIs over time with the correct public key.
- [ ] Does this update manifest apply to webextensions?

**Comment by mythmon** [comment]
I don't think this is the way we want to take extensions. We do eventually want to be able to update extensions, but I think doing so explicitly in recipes will be better for us. It also allows us to bypass the signing issues raised above.
