### ISSUE TITLE
Errors in recipe enrollment in 56b11

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/normandy#1063]
Related to the issue with losing users in the Activity Stream 56 Beta study found here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1399936

We have found reproducible errors at Firefox startup related to recipe enrollment, see here:

https://pastebin.com/raw/qrLSPz3m

https://pastebin.com/raw/6cWR5cRW

It's possible that the Shield System Addon is failing to enroll users in studies which is why we're seeing users disappear from our studies.

**Comment by jaredkerim** [comment]
It looks like there's a drop in population size for multiple experiments:

https://sql.telemetry.mozilla.org/queries/38609#103686

**Comment by emtwo** [comment]
Initially we saw the drop in users in Activity Stream:
https://sql.telemetry.mozilla.org/queries/27149#93513

I've confirmed similar drops in Onboarding:
https://sql.telemetry.mozilla.org/queries/38610#103685

And Search:
https://sql.telemetry.mozilla.org/queries/38635#103758

**Comment by Osmose** [comment]
> We have found reproducible errors at Firefox startup related to recipe enrollment, see here:
> 
> https://pastebin.com/raw/qrLSPz3m
> 
> https://pastebin.com/raw/6cWR5cRW

The second pastebin here is #1058 and the fix is being uplifted in [bug 1399245](https://bugzilla.mozilla.org/show_bug.cgi?id=1399245). @mythmon and I looked into it this morning and we think that it should not affect enrollment (it fails at the end of initializing the preference experiment, and the method that isn't found is also called when the add-on shuts down).

**Comment by emtwo** [comment]
@Osmose what about the first pastebin? Any information on that one?

**Comment by Osmose** [comment]
> @Osmose what about the first pastebin? Any information on that one?

@mythmon is investigating it as we speak and should have some more info shortly.

**Comment by lizzard** [comment]
I think maybe in beta 10 (released Sept. 8). The surge on Monday could be normal weekday users coming back. So maybe the dip in users really began with beta 10.   These changes were in beta 10: https://bugzilla.mozilla.org/show_bug.cgi?id=1397415

**Comment by Osmose** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399936 contains more details, and a fix that was only deployed to Fx56. Closing this out.
