### ISSUE TITLE
Single recipe sorting incorrectly on prod

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1067]
I noticed a single recipe sorted out-of-order on prod earlier:

<img width="905" alt="screen shot 2017-09-20 at 3 04 02 pm" src="https://user-images.githubusercontent.com/193106/30669939-33bb92dc-9e15-11e7-8a02-5ecd23bf8412.png">

The only interesting hint as to why this is happening is that the "Tracking Protection" experiment has a pending review request filed 2 minutes after the review request for the "Onboarding" experiment was approved.

**Comment by mythmon** [comment]
Without more details about this, or steps to reproduce, this isn't something that is actionable.
