### ISSUE TITLE
Marking uploaded extensions as unusable or disabled

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1069]
In [bug 1401744](https://bugzilla.mozilla.org/show_bug.cgi?id=1401744) we found that the opt-out nothingburger study had a shutdown error that broke `about:addons`. To avoid future mistakes, I'd like to mark the extension as unusable on Normandy, so that it cannot be used in a recipe. 

Open questions:
- What should happen to studies that are currently set to use the extension when it is marked as unusable?
- Should studies be able to be marked as usable again?
- Should the upload URL for an unusable extension still return the extension file?

@MattGrimes Thoughts? Is this something we'd want?

**Comment by shell1** [comment]
For now -we're shelving this.  won't fix
