### ISSUE TITLE
Add general notes field to recipes 

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1082]
Every recipe should have a comments field that recipe editors can save arbitrary notes about the recipe in. This could be related bugs or documents, or explanation of what's going on. This should not be visible to users (public API is fine), related to any particular action, or have any other purpose.

**Comment by andymikulski** [comment]
Is the field persistent across revisions, or is a new one created each time? I'm also going to assume this is for general note keeping and not actually holding a conversation on the page (a la threaded comments).

**Comment by mythmon** [comment]
I think this should be part of the revisions, in that it is versioned along with all the other fields. It will require adding a new field to the API, as well as UI for it.

And yes, this isn't intended to be used for conversation. We don't need to track authorship or threading or anything like that.

The main purpose here is to provide a space for notes that are useful in explaining a recipe. Recently there were some opt-out studies that abused the Study Description field to do this. The problem being that Study Description is user facing data. (#1081 covers this).

**Comment by mythmon** [comment]
@rehandalal I think this would be a good PR for getting back into Normandy.

**Comment by rehandalal** [comment]
Turns out we already have this field: https://github.com/mozilla/normandy/blob/master/normandy/recipes/models.py#L323

I believe this is a remnant of reversion. It is currently not used in the UI and exposed as a read only field in the API. I don't think there is any value to the historical data in this field so we should probably just use this going forward as the comments field. 

@mythmon thoughts?

**Comment by mythmon** [comment]
It also seems we haven't ever used this for anything useful:

```
⟩ curl -s https://normandy.cdn.mozilla.net/api/v2/recipe_revision/ | jq -r 'map(select(.comment != "")) | .[] | "\(.id) \(.recipe.name) - \(.comment)"'
1429 Release Channel Filtering Test - Changed enabled.
1428 Release Channel Filtering Test - Changed release_channels.
1427 Release Channel Filtering Test - Changed enabled and release_channels.
1426 Release Channel Filtering Test - Changed enabled.
1425 Release Channel Filtering Test - No fields changed.
1424 Release Channel Filtering Test - No fields changed.
1423 Release Channel Filtering Test - Added.
1435 Locale Filtering Tests - Changed enabled.
1434 Locale Filtering Tests - Changed locales.
1433 Locale Filtering Tests - Added.
```

(Notably, we also don't paginate the revision endpoint, which we probably should)

**Comment by mythmon** [comment]
Yes, lets use that field for this.
