### ISSUE TITLE
Localize about:studies

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1083]
The add-on's listing of opt-out studies, about:studies, isn't localizable. This gets us in trouble if we want to run studies with non-English populations. We should fix this.

**Comment by MattGrimes** [comment]
This is going to become an issue rather quickly. It is becoming clear that Shield is now the go to platform and the number of non-english experiments is starting to stack up.

**Comment by mythmon** [comment]
CC @Pike @flodolo

**Comment by mythmon** [comment]
@Pike has convinced me to try and use Fluent (formerly l20n) for this. We'll be one of the first in-tree uses, so we might hit some snags. If there proves to be too much effort overall, I might explore another solution.

**Comment by flodolo** [comment]
I need some more background: are we talking about getting about:studies localized, or also actual studies included in Shield? I'm not completely familiar with the matter, so I don't know if there's interactivity involved in any of the studies.

How frequent would be the updates? Could they ship directly in release, skipping Nightly and Beta?

**Comment by mythmon** [comment]
This issue only covers translating things that are a part of the system add-on. Studies that need localization will need to implement their own, separate, localization.

Frequency of code updates vary, and whether the can ship directly to release varies depending on the type of change. For string changes, I think we could ship directly to all channels instead of riding the trains, but I'd like to hear more about the options.

**Comment by flodolo** [comment]
Can you clarify when you'd like to see this feature localized? Is it safe to assume that you're targeting 58 (or later)?

**Comment by mythmon** [comment]
I'd like to complete the work here as soon as possible, so targeting 58 seems right to me. I'm still a bit fuzzy on the work of actually getting translations from localizers into builds of the add-on though. If there are other time constraints going on, I'd be happy to discuss them.

**Comment by MattGrimes** [comment]
This is quite high priority given the current Shield queue. 58 seems like the right target to me. 

As @mythmon mentioned above, we're localizing the content on the about:studies page and the single preference that we inject into about:preferences only. This gives users visibility into any studies they may currently be participating in and allows them to opt-out of the program altogether without disabling telemetry. 

Individual studies will require localization. We currently have each experimenter handle localization on their own, but it would be good for us to establish a more formal process soon.

**Comment by mythmon** [comment]
> Individual studies will require localization. We currently have each experimenter handle localization on their own, but it would be good for us to establish a more formal process soon.

To be clear, this issue doesn't cover localizatoin individual studies. the type of localization needed there is very different. I would like to explore this in the future though.

**Comment by MattGrimes** [comment]
Yes, sorry. I thought I was echoing that but I can see how it might have been confusing. That is a problem for a later date.

**Comment by flodolo** [comment]
Thanks for the update. At this point I'll need @Pike and likely @zbraniecki to figure out if Fluent is the right fit in this timeline.

**Comment by Pike** [comment]
Sorry for the lag, we've been trying to figure out what we can offer, and didn't get far.

One thing we know is that we want you guys to end up using fluent. We also know that there's nothing that exists and is proven for your use-case.

Problem space: about:studies is in content, which makes it hard to use code we landed in m-c.We have a [bug 1407418](https://bugzilla.mozilla.org/show_bug.cgi?id=1407418) on file to see if we can get goodness exposed, but that doesn't have a timeline yet. Being in-content means that any solution we pick needs to ship within about:studies for the most part, probably.

With fluent, I expect us to figure this out together, but there's no better way than starting and figuring out what we need to fix right now.

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435875
