### ISSUE TITLE
Pass Experimenter URL to the web UI via the API

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/normandy#1084]
Here:

https://github.com/mozilla/normandy/blob/master/recipe-server/normandy/base/api/views.py#L59

We can pass the Experimenter URL to the React client so it knows where to call.

**Comment by mythmon** [comment]
Experimenter is going to land as a monolithic feature in #917, instead of a bunch of small PRs. That means this is a duplicate of #917 now.
