### ISSUE TITLE
Heartbeat Prompt URL Param Addition

### ISSUE THREAD

**Issue by rayborn** [mozilla/normandy#1102]
I would like the recipe name slug to be passed in as a url param.  Right now you have to add your own URL param for reliable funnel analysis, especially since the message text that we use as utm_campaign is not unique in many cases.

If we're worried about name data leakage, I would also accept the recipe ID as a unique identifier.  In fact that would guarantee uniqueness so in some ways it's superior.

**Comment by mythmon** [comment]
This sounds like a good and useful thing. I'd lean towards recipe ID, since we use that as the primary key everywhere else.

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435874
