### ISSUE TITLE
Please add a mechanism to distinguish "rollout" studies from experiments

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/normandy#1106]
Per [Bug 1381954](https://bugzilla.mozilla.org/show_bug.cgi?id=1381954), we need to be able to determine, by examining a given Telemetry ping, whether it represents a feature rollout aimed at broad deployment so that we can ignore those kinds of pings in the experiments pipeline.

**Comment by mythmon** [comment]
How do you want to go about this? I didn't see any solid recommendations in the bug. Should we use a separate experiment type for this? Possible `shield-pref-exp` and `shield-pref-rollout`? (Both of these are under the 20 character limit I think exists)

Or is there another mechanism we should use here?

**Comment by sunahsuh** [comment]
That's perfect -- I'll need add the `shield-pref-exp` type to the whitelist so please let me know ~2 weeks before this is deployed, if possible so I can make sure it gets deployed in the normal sprint cycle.

**Comment by mythmon** [comment]
@sunahsuh I'll be making this change fairly soon, and I'd like to sync this to mozilla-central (and thus Nightly) in the next couple weeks. From there it will right the trains. Does that sound good?

**Comment by mythmon** [comment]
After giving this some more thought, I'd like to propose a different set of experiment types, to better capture what we're trying to do here. Specifically, "rollout" is not specifically the thing we're trying to filter out. We're trying to filter out high population recipes. Because of this, I propose `shield-pref` and `shield-pref-highpop`. I think this conveys the idea better.

**Comment by sunahsuh** [comment]
Hey @mythmon when is this change going out to the world? i need to deploy a change to our pipeline re: the new type string

**Comment by mythmon** [comment]
We don't have a defined timeline for this. Lets chat about when works best.

**Comment by mythmon** [comment]
For the record: The next deploy to the pipeline is Monday. @sunahsuh is going to try and get support for this into that deploy. We should not push this to mozilla-central without sunahsuh's go-ahead.

**Comment by sunahsuh** [comment]
Changes are finally live! All clear to merge changes

**Comment by mythmon** [comment]
Changes will merge into Firefox Nightly 59 in [bug 1422407](https://bugzilla.mozilla.org/show_bug.cgi?id=1422407).
