### ISSUE TITLE
Parse extension ID out of XPI files and expose in API

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1107]
Upon upload, we should read the `install.rdf` or equivalent webextension file to get the ID of extensions. This data should be available read-only in the API.

**Comment by rhelmer** [comment]
Just a few notes based on having to do this a lot in addons manager (the webextensions manifest name is `manifest.json` for context):

1) don't bother with "real" RDF parsers, just parse `install.rdf` as XML
2) XPI files are just regular zip files, should be able to read the manifest out of it directly (as opposed to uncompressing the whole thing etc)
3) webextensions can be embedded - if `install.rdf` has `hasEmbeddedWebExtension` then there will be a `webextension/manifest.json` that should be checked as well

**Comment by mythmon** [comment]
Thanks for the advice! Normandy is already doing [some processing of XPI files](https://github.com/mozilla/normandy/blob/master/recipe-server/normandy/studies/api/v2/fields.py), treating them like regular zip files and reading individual files out. Hopefully we aren't doing anything goofy there. We don't check for hybrid extensions though, which is a good thing we should be watching out for.

**Comment by shell1** [comment]
this falls under the purview of the add-on handling project rehan is working on .  also fixed already.
