### ISSUE TITLE
Require that extension IDs end with @shield.mozilla.org

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1108]
Once #1107 is done, we can start putting requirements on what extension IDs can be. Once we can do that, we should require have a pattern that is easy to recognize. I think `@shield.mozilla.org` would be a good pattern for that.

Should we allow `@pioneer.mozilla.org` as well? CC @lonnen @rehandalal

**Comment by shell1** [comment]
situation has changed - removing this request as it's not so clear what we'd want to do with expanded content types
