### ISSUE TITLE
Save and continue

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1109]
I think it would be nice to have the "Save" button take you back to the details page and have a "Save and Continue" button to continue editing.

**Comment by andymikulski** [comment]
@rehandalal Can you elaborate on this a little? I initially read the ticket title and assumed it was something along the lines of persisting unsaved draft changes locally and then offering to pick up where users left off, but I don't think that's what you had in mind.

**Comment by rehandalal** [comment]
Currently we have a single "Save" button. When you click this button it saves the changes you have made and flashes a message to let you know it has saved successfully.

I would like to change the behavior so that, when you click the "Save" button, it takes you back to the recipe details page after it successfully saves your changes.

In addition we should add a "Save and Continue" button that works the way the current "Save" button works.

**Comment by andymikulski** [comment]
Ooooh. Got it.
