### ISSUE TITLE
Ability to Pause pref flips

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/normandy#1112]
We've run into a couple of situations where we have hit our enrollment numbers for pref flips but needed to keep the recipe live for an additional period of time. It would be nice if we could pause enrollment for pref-flips the same way we can for native studies so we don't over-enroll.

**Comment by mythmon** [comment]
Implementation note: opt-out studies pause enrollment in the action, not in the driver, so this is something we can fix without a system add-on update. This should  be a pretty easy change. The opt-out studies version of this is just a few lines: https://github.com/mozilla/normandy/blob/4a7bf8083cac71b521e909ee3e55bda4c318c67e/recipe-server/client/actions/opt-out-study/index.js#L40-L41
