### ISSUE TITLE
ExtensionSelect Test failure on master.

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1113]
Circle CI builds on master are failing with the following test failure:

> <ExtensionSelect> should fire an onChange event appropriately - Firefox_56_0_0_(Ubuntu_0_0_0).
>
> Expected undefined to be 2.

The merge of PR #1072 was the first commit to show this problem. The tests in #1072 passed, so this must be an incompatibility with that long lived PR and master.

**Comment by mythmon** [comment]
@andymikulski any updates about this issue? This is going to block any PRs merging until it is fixed or the breaking changes are backed out.

**Comment by andymikulski** [comment]
I started to rewrite the ExtensionSelect component, but that will take more time. To prevent blocking PR's, I will simply back out the breaking changes now.
