### ISSUE TITLE
Add ordering to extension listing

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#1165]
Required to resolve #1091 

Currently, there is no sorting/ordering enabled for the Extension Listing pages and related API endpoints. This functionality is required in a couple spots, particularly the `ExtensionSelect` component.

**Comment by peterbe** [comment]
The [commit](https://github.com/mythmon/normandy/commit/59113b9054486497f861049e8b90e77c07e47d79) appears to say that fixes this bug. But it's still open. Mistake or some paperwork I don't know about?

**Comment by mythmon** [comment]
This seems to be a bug. I guess it's a bigger issue than I thought, and we should track it down.
