### ISSUE TITLE
What should Normandy never be able change?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1174]
Identified in our Experiments work week there are at least three commandments: 

1. Thou shall never break the ability to update Firefox 
1. Thou shall never make Firefox slower
1. Thou shall never reduce retention 

There may be more. However, in the spirit of Safety what are things that we should enforce in code that Normandy (recipe-client, recipe-server) should never be able to do?

**Comment by mythmon** [comment]
I don't think "commandments" 2 and 3 actually follow from the work week. We discussed that they are metrics we need to watch, but it is possible that it is ok to slow down Firefox or reduce retention for particular studies. I don't think this is something we should try and enforce automatically, and in fact I don't think we can do this within Normandy.

Command 1 is definitely true though. We have to make sure we can always roll back if something goes wrong. However, again I don't think there is a bright line we can draw that will keep us safe without totally crippling our behavior.

For example, bootstrap add-ons can do almost anything, including break the updater. Normandy will install bootstrap add-ons as a part of a study. We can't reasonably detect updater-breakage ahead of time. The only way to definitely be safe would be to make no changes to Firefox. The only way to actually get anything done is to accept the risk that add-ons might not be perfect.

I think [the things that Normandy will never do](https://www.youtube.com/watch?v=dQw4w9WgXcQ) are mostly around operational security. It won't send things out that haven't been authorized by (at least) two valid users. It won't execute things that aren't signed correctly. Beyond that, I think that we have to leave Safety to the process, not code.

If you have more specific ideas I'm happy to explore them. Specific features will always need to be designed with safety in mind, but blanket "automate that nothing can ever go wrong" rules aren't something I think we should spend time on right now.

**Comment by rhelmer** [comment]
> Thou shall never break the ability to update Firefox

Totally on board with this one! @bdanforth and I are working on running all the same perf/correctness tests that normal Firefox features get for the upcoming Tracking Protection study, so I think we could reduce the risk around breaking core Firefox features, especially things like startup/update/ability to use the product.

> Thou shall never make Firefox slower

This I think is not appropriate for experiments like the TP study above, and likely many others - for instance the purpose of the study is to present a new proposed UX and measure how users respond to it, and the tracking protection implementation is necessarily much higher-level than it will be if we go forward with it.

The point here is that we want to measure things like user retention *before* we invest the full engineering effort into this feature, so having some small perf regressions is acceptable in this case. The point though is that we've measured and know exactly how much we're regressing and why, and we'll make sure that's reflected in the intent-to-ship that goes in front of release management.

> Thou shall never reduce retention

Per above I think this is the sort of thing we use experiments to measure... if we ship the TP study and it causes retention to drop then we've done something wrong, and this is very useful data that we'll need to get to the bottom of, before we start even thinking about building out the real feature.

**Comment by mostlygeek** [comment]
These answers have very good points and don't answer my original question.  I don't think I asked the question well. So I'll close this issue and ask it a different away.
