### ISSUE TITLE
What safety features should Normandy have? 

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1179]
This is a follow up to issue #1174. 

Normandy is a powerful tool with the ability to make changes to almost every part of a user's Firefox.  This has allowed us to get data and make informed decisions about how changes affect the experience of our users.  We want to do more of this. We want to scale out the Shield program so more internal groups can run their own studies.

However, Normandy is a powerful tool.  As we scale the number experimenters and experiments our tools should allow us to go fast but also provide seatbelts in case of accidents. 

Different considerations and positions came out of online and offline discussions: 

- Is it Normandy's responsibility to have any sort of limits? 
- Should only process, human checking and approval be responsible for vetting studies? 
- There should be a balance between human process and automated process

There will be a lot more questions and different considerations. This issue's intent is to capture them and decide what should be in Normandy.

**Comment by mythmon** [comment]
This topic is good to talk about, but it doesn't fit a Github issue well. There isn't a clear thing that would make this issue "done". I'm going close this, since it doesn't represent a task to do.
