### ISSUE TITLE
Move mozjexl to its own repo

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1189]
Mozjexl, our fork of https://github.com/TechnologyAdvice/Jexl, should be moved to it's own repo.

**Comment by mythmon** [comment]
The repo it is moving to is here: https://github.com/mozilla/mozjexl. For now, that is just a fork of the original Jexl. It needs to get updated with the changes from this repo, and CI and other tooling added.

**Comment by dmose** [comment]
@mythmon Do you know/recall why mozjexl chose to base itself off of TechnologyAdvice/JEXL, rather than the upstream of that, [TomFrost/JEXL](https://github.com/TomFrost/Jexl)?  Also, what was the motivation for forking at all?

**Comment by mythmon** [comment]
I don't remember why we chose the base we did. I do remember the reason for the fork was that we wanted to make changes to the language without slowing down for upstream collaboration. I think that re-aligning with upstream in a compatible way would be a fine step forward.

**Comment by dmose** [comment]
Thanks!

Am Do., 23. Juni 2022 um 13:39 Uhr schrieb Michael Cooper <
***@***.***>:
