### ISSUE TITLE
Allow for client-side actions

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1193]
In [bug 1436129](https://bugzilla.mozilla.org/show_bug.cgi?id=1436129), we are implementing actions in the client. That implies that there may be actions for which the implementation *not* on the server. We should have a way to deal with this, possibly by having stub implementation or supporting actions without implementations

**Comment by mythmon** [comment]
Part of this puzzle will be syncing argument schemas between the server and the client. To do this, an NPM module will be published out of mozilla-central. The server and delivery console can pull this from NPM and use it to validate arguments.

**Comment by mythmon** [comment]
Update: the schemas are published in the (verbosely named) NPM package [mozilla-normandy-action-argument-schemas](https://www.npmjs.com/package/mozilla-normandy-action-argument-schemas).

**Comment by peterbe** [comment]
Can we close this issue or are there more patches on the recipe-server side we want to make?

**Comment by mythmon** [comment]
I think that we can close this now.
