### ISSUE TITLE
Transition Normandy to CircleCI 2.0

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1196]
CircleCI [has announced](https://circleci.com/blog/sunsetting-1-0/) they are going to stop supporting CircleCI 1.0 on August 31st. Normandy currently uses 1.0. We'll need to migrate to 2.0 before the end of August.

**Comment by mythmon** [comment]
The deadline is getting closer, so bumping the priority on this.

**Comment by peterbe** [comment]
@mythmon Why did you use the `machine` in the original circle 1.0 config?

**Comment by mythmon** [comment]
At the time, the machine executor was the only way to build, test, and publish a Docker image. It may be possible to do this with the remote docker system in Circle 2.0, and if that is true, it would be good to stick to that.

**Comment by peterbe** [comment]
Note-to-self;

* Let's use docker and docker-compose [like kinto-dist](https://github.com/mozilla-services/kinto-dist/pull/214)
* Let's not worry about the existing docker-compose stuff (e.g. https://github.com/mozilla/normandy/tree/master/compose) if it just adds confusion.
* We probably want to use PG 9.5 but bpitts might know more accurately. 
* The count-down is at the time of writing, [7 weeks 3 days and 5 hours](https://circleci.com/).

**Comment by pdehaan** [comment]
I found https://circleci.com/docs/2.0/local-cli/ which points to a handy CircleCI v2 config validator (using something like <kbd>$ circleci config validate -c .circleci/config.yml</kbd>).

**Comment by peterbe** [comment]
I've used local-cli and am often disappointed. It's been several times where it's reported that all is well only to find out it breaking on something fundamental when you start a circle test.
