### ISSUE TITLE
CSP blocks "Try it out" in API docs

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1206]
The [API docs](https://normandy.cdn.mozilla.net/api/docs/) offer a way to try out the API by making in the browser, but those requests are blocked by CSP. 

The CSP error report sent to the server is:

```json
{
  "csp-report": {
    "blocked-uri": "self",
    "document-uri": "https://normandy.cdn.mozilla.net/api/docs/",
    "original-policy": "worker-src 'none'; frame-src 'none'; block-all-mixed-content; object-src 'none'; form-action https://normandy.cdn.mozilla.net; default-src https://normandy.cdn.mozilla.net https://normandy-cloudfront.cdn.mozilla.net/; base-uri 'none'; report-uri https://normandy.cdn.mozilla.net/__cspreport__",
    "referrer": "",
    "source-file": "https://normandy.cdn.mozilla.net/api/docs/",
    "violated-directive": "default-src"
  }
}
```

The violated directive (`default-src`) is `default-src https://normandy.cdn.mozilla.net https://normandy-cloudfront.cdn.mozilla.net/`. I'm not sure why that blocked the request. Maybe `self` needs to be added?

**Comment by shell1** [comment]
verified working now with update of doc library
