### ISSUE TITLE
KeyError: 'slug' when validating arguments

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1209]
It looks like when validating the changes between old and new arguments, we assume that `slug` is in the old arguments, which isn't necessarily true. We should make this a bit more resilient.

https://sentry.prod.mozaws.net/operations/normandy-stage/issues/3234355/

**Comment by mythmon** [comment]
I'm guessing that this is related to #600. If the type of an action changes between revisions, the old arguments won't meet the requirements of the new action.

**Comment by shell1** [comment]
Hit QA recently - if we change the type things get weird.  closing as duplicate of #1863
