### ISSUE TITLE
Decimal numbers don't convert to canonical JSON in the same way as Firefox's Canonical JSON

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1210]
To verify recipes executed on the client, we include a signature of the canonical JSON serialization of the data. The client can verify the signature by serializing it into JSON and verifying the signature against that. This relies on the server and client using the same serialization steps. This generally works fine.

It doesn't work fine for very small decimals, such as `0.00001`. The Python implementation serialized this value as `1e-5`, and Firefox's as '0.00001`. The server is much easier to change in this regard, so we should change it there.

As a side note, I don't think that canonical JSON is standardized anywhere, so we can't defer to authority on this.

CC @jvehent this is probably interesting to you.

**Comment by mostlygeek** [comment]
Are we using [autograph](https://github.com/mozilla-services/autograph) for the signature? 

>  The client can verify the signature by serializing it into JSON and verifying the signature against that.

Am I understanding this part correctly:

- the "it" refers to a recipe
- this bug comes from the recipe-client re-serializing the recipe into JSON. That doesn't match how Python does it, so the JSON is different
- the signatures won't match cause the bytes are different

> The server is much easier to change in this regard, so we should change it there.

This sounds like the path to hell...

**Comment by jvehent** [comment]
> Are we using autograph for the signature?

Yes, but autograph knows nothing of the input data. It just signs a bunch of bytes.

> As a side note, I don't think that canonical JSON is standardized anywhere, so we can't defer to authority on this.

We talked about this a bunch when kinto implemented serialization, a couple years back, but never standardized it. Maybe it's time?

**Comment by mostlygeek** [comment]
Isn't [RFC7159](https://tools.ietf.org/html/rfc7159) is the canonical JSON standard? 

Are we asking if we should have a standard on the way JSON should be *formatted*? so the bytes are always the same between different de/serializers?

**Comment by mythmon** [comment]
@mostlygeek, your understanding is correct. This is a difference between JSON serializers that are meant to be byte-for-byte identical.

RFC7159 is the canonical standard for JSON. What we're talking about here is "Canonical JSON", a subset of JSON that is intended to always produces the exact same bytes for a given object, which RFC7159 does not require.

For a simple example, `{"a": 1, "b": 2}` and `{"b": 2, "a": 1}` are equal under RFC7159, despite being different byte sequences. Canonical JSON would serialize both of these as `{"a":1,"b":2}` (keys sorted, no unneeded spaces).

> > The server is much easier to change in this regard, so we should change it there.
>
> This sounds like the road to hell...

It's worked fine for us so far. More importantly, [we aren't the only user of `CanonicalJSON.jsm`](https://dxr.mozilla.org/mozilla-central/rev/6ff60a083701d08c52702daf50f28e8f46ae3a1c/services/common/blocklist-clients.js#27) (the one in Firefox), and Normandy's serializer is used only by Normandy, and its only purpose is to match Firefox's. This is a pretty easy job, since Firefox's serializer [hasn't changed in behavior since it was introduced in April 2016](https://hg.mozilla.org/mozilla-central/filelog/6ff60a083701d08c52702daf50f28e8f46ae3a1c/toolkit/modules/CanonicalJSON.jsm).

**Comment by mostlygeek** [comment]
What are the reasons for not checking the signature before we deserialize the JSON?

**Comment by jvehent** [comment]
Because the signature is stored inside the json.

Note that it could also be served as a http header, but we don't do that in
Normandy or kinto.

**Comment by mostlygeek** [comment]
Sending the signature so we don't have to de-re-serialize would be a lot better.  Not having to use CanonicalJSON.jsm seems desirable.

**Comment by mythmon** [comment]
To expand on what @jvehent said, the payload we are verifying from the server looks like this (expanded to non-canonical JSON, to improve readability):

```json
[
  {
    "recipe": { ... },  // this is the signed portion
    "signature": { ... }, // the signature for the recipe
  },
  { ... } // the recipe-signature pairs are repeated for each recipe
]
```

It would be technically possible to extract the raw bytes of the recipe key in each object from the response, but that would require a specialized JSON parser that doesn't exist in Firefox to my knowledge. I try and avoid writing parsers.

In order to serve the signature as a header, we would have to serve each recipe separately instead of in one request. This has negative effects on our servers (few big, consistent requests being easier than many small requests). We opted for the deserialize/serialize/verify step because it makes our servers scales better, and the code to support it on the client is robust enough.

I don't think that changing the signature verifying algorithm is in scope for this issue. If you'd still like to explore this change, please move this conversation to another issue or the mailing list.

**Comment by mythmon** [comment]
Closing this in favor of #1211.
