### ISSUE TITLE
Convert revisions ids to simple autoincrement instead of hashes

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1212]
Currently `RecipeRevision` ids are not the normal Django pattern of a simple autoincrementing integer key. Instead they are using a hash of some of the data in the revision. The original goal was to have a git-like system and to avoid duplicating revisions.

We either didn't implement these features, or have removed them. The hashes are a point of complexity we don't need, and tech debt we should get rid of. Specifically this makes it very difficult to change the way we deal with filtering. When trying to migrate from simple filters to filter objects, it isn't reasonable to make filter objects correspond exactly with their simple filter counterparts. It also doesn't allow us to change the representation of filter objects in the future.

One issue is that these revisions are used in URLs, and making this change will change the URLs. I briefly talked to S&I, and although they use these URLs, they don't save or bookmark individual links, so if the format changes it won't affect them.

This issue covers:

* Removing the revision hashing
* Switching to auto-incrementing IDs for revisions
* A database migration to move existing revisions over to the new system
* Checking that the Control interface continues to work (I suspect it won't need any changes).

**Comment by mythmon** [comment]
@rehandalal Have you been able to make any progress with your "copy the model" idea?Should we go ahead with the proposed solution in #1243 instead to unblock filter objects?

**Comment by rehandalal** [comment]
Got sidetracked will work on that this evening.
