### ISSUE TITLE
Mention how to edit this in Nightly

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1215]
In Nightly instead of `extensions.shield-recipe-client.api_url` it's called `app.normandy.api_url`.
The documentation should mention that. 
<img width="836" alt="screen shot 2018-03-28 at 1 29 01 pm" src="https://user-images.githubusercontent.com/26739/38054543-268570a4-328c-11e8-9343-bfabf76a90ce.png">

**Comment by mythmon** [comment]
I updated this as a side effect of #1238.
