### ISSUE TITLE
Checks are not unit tested

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1223]
<img width="825" alt="screen shot 2018-04-11 at 4 13 55 pm" src="https://user-images.githubusercontent.com/26739/38640819-5df18326-3da3-11e8-80c9-fdd0595ebbc8.png">
<img width="903" alt="screen shot 2018-04-11 at 4 14 25 pm" src="https://user-images.githubusercontent.com/26739/38640845-6ea13ae0-3da3-11e8-9eb3-0c03d7fff23c.png">
<img width="938" alt="screen shot 2018-04-11 at 4 14 52 pm" src="https://user-images.githubusercontent.com/26739/38640865-7d67e466-3da3-11e8-95a1-524c4626c842.png">
<img width="915" alt="screen shot 2018-04-11 at 4 15 33 pm" src="https://user-images.githubusercontent.com/26739/38640908-9b72f2b6-3da3-11e8-891b-838731981db1.png">

We ought to have some unit tests for these.

**Comment by rehandalal** [comment]
This is a non-issue now that we're on dockerflow. Fixed by https://github.com/mozilla/normandy/pull/1337.

**Comment by mythmon** [comment]
I don't  agree. #1337 switched out the infra that we used to run the checks, but this issue is about the Normandy-specific checks that we have implemented. Those weren't replaced in #1337, and still have no test coverage.

**Comment by rehandalal** [comment]
Oops! I missed those. My bad.

**Comment by shell1** [comment]
won't fix.
