### ISSUE TITLE
letting opt-out study addons know when Normandy kills a study

### ISSUE THREAD

**Issue by raymak** [mozilla/normandy#1236]
This is in regards to https://github.com/mozilla/shield-studies-addon-utils/issues/89. Now that we are moving towards web-extensions, a potential solution is to broadcast a message that tells the study that it's being disabled by Normandy (as opposed to by the user). This message can be caught by the Shield utils.

**Comment by mythmon** [comment]
This sounds like a good feature.

We've changed how we are tracking work now. This repository is only for the server side of Normandy. Any work that happens in the client should be tracked in Bugzilla. I've filed [bug 1456247](https://bugzilla.mozilla.org/show_bug.cgi?id=1456247) for this work.
