### ISSUE TITLE
Make API v1 readonly and remove unused endpoints.

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1362]
Along with making a v3 API (#1361), we're going to trim down the v1 API, to minimize the amount of code we need to maintain. To do this we're going to make the v1 API read-only, and remove views that aren't used by the Firefox Normandy client.

I think there may be a couple users of the v1 API that we should also reach out to. We should either help them migrate to v2 or v3, or maintain the behavior they need.

**Comment by shell1** [comment]
partially done - is now readonly.  quick pass was done to remove the obvious.  possible there is more that could be cleaned up.  removing would break backward compat with older firefox and older clients.  NOT DOING MORE CLEAN-UP.
