### ISSUE TITLE
Add tracking bugzilla bug number to pref change recipie

### ISSUE THREAD

**Issue by emceeaich** [mozilla/normandy#1388]
When creating and editing pref change recipes related to feature rollouts, we would like to know the associated bugzilla bug for the associated feature. 

This would enable us to associate the status of prefs to features in bugzilla and enable better reporting. 

From a discussion with @rhelmer.

**Comment by rehandalal** [comment]
Would the general notes field as outlined in #1082 do? Or do we specifically want a bug ID field?

**Comment by emceeaich** [comment]
We'd want a bug ID field because I'd want an API endpoint I could use to query to get recipes/actions that reference that bug ID

**Comment by mythmon** [comment]
There is already a bug on file to add this data, #1198. I'll prioritize getting that added to the API. We have some architectural issues to sort out before we can make it available in the UI though.
