### ISSUE TITLE
Django admin needs an auth method that works with auth0

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1399]
Currently we rely on external authentication via Nginx for both the API and the admin interface. We're moving to direct OIDC authentication for the API via bearer tokens. This works well for the API views, but doesn't work for non-API views.

The only place we'll have non-API views after Delivery Console is in place will be the Django Admin. We may eventually complete replace the Django Admin, but for now we still need it. To do this we'll need an Django authentication method that talks with auth0 to authenticate a user and then sets up a session for that user to use the Admin.

This is not related to the authentication that clients of the API will be doing, and will only apply to the Django admin interface, which at the moment is only used for user management by super users. Again, this will go away eventually, but for now we need this bandaid.

**Comment by mostlygeek** [comment]
This is only for creating / managing user permissions within django?  Would replacing the permission layer with something like Doorman also fix this issue? 

Until we have that I would be fine to running a tiny, one-off ec2-box behind the VPN with django admin for managing users and permissions.

**Comment by mythmon** [comment]
This is also the current "escape hatch" we have for deleting recipes, if we accidentally put something secret in a recipe. This could also be added to the API in the future.

Running a second admin node is basically what we'll be doing automatically if we do nothing, since we are going to be running one Normandy with openresty-lua and another with our own OIDC. I'd like to eventually not do that though. Maybe we can push it off long enough to just use Doorman and replace all the other features though.

**Comment by mythmon** [comment]
We've decided to run a second admin node until the future of Doorman is decided upon. If Doorman has a future, we'll use that for user permission, and make APIs for anything else we need. If Doorman does not have a future, we'll find another way to manage user permissions (likely reading ldap groups from auth0).
