### ISSUE TITLE
Don't allow a preference rollout and its rollback to both be enabled at the same time

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1400]
In [bug 1459920](https://bugzilla.mozilla.org/show_bug.cgi?id=1459920), Adrian brought up that having both a rollout and its rollback targeting the same user will produce strange results and noisy telemetry. Talking to Adrian and @glasserc, we came to the conclusion that this isn't a state that really makes any sense. Since rollbacks can't be undone, after one is created you'll have start over on a brand new recipe anyways.

Since this is a situation that doesn't make sense, and we want to not do, we should make it a rule and enforce it in the API. In the same way that we enforce other inter-recipe rules (like that recipe slugs must be unique).

To be specific, consider two recipes: `r1` is a preference rollout with slug `foo`. `r2` is a preference rollback that references `r1`'s slug. If `r1` is currently enabled, then `r2` cannot be enabled. If `r2` is currently enabled, then `r1` cannot be enabled. (Perhaps if `r2` exists at all?). It is fine to disable both recipes at any time.

**Comment by peterbe** [comment]
The task is to validate the recipe enabling based on looking up it's anti-recipe using the same slug string?

```
# What to enable r?
look_for 'rollout' if r.action == 'rollback' else 'rollback'
if Recipe.objets.filter(slug=r.slug, action=look_for, enabled=True).exists():
    raise NotValid()
```

Is that what you mean?

**Comment by mythmon** [comment]
Something like that, yeah. Except the slug is in the arguments JSON, so you'll need to be a bit more clever than that.

**Comment by mythmon** [comment]
@peterbe Are you still working on this?

**Comment by peterbe** [comment]
> Are you still working on this?

Short answer; no. Reason; I had totally forgotten about it. 
I do have time to work on it though.

**Comment by mythmon** [comment]
Ok. If you're going to work on it, neat. If not, can you unassign your self?
