### ISSUE TITLE
SSLError in local development

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1402]
Not sure if this is a me problem or something bigger. One minute everything was working fine and then all of a sudden it just stopped completing the TLS handshake and I saw this error:
```
----------------------------------------
Exception happened during processing of request from ('172.16.150.1', 55435)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/home/rehandalal/.virtualenvs/normandy/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 139, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2273)
----------------------------------------
```

Tried a few things, but they didn't help:
- Upgraded openssl to latest.
- Created new certificate/key pair.
- Tried in different browsers and new profile.

**Comment by rehandalal** [comment]
I have now also tried: 
- Creating a brand new VM with Ubuntu 18.04 instead of 16.04

While I still have an issue on the VM I was able to get normandy working using docker-compose. And as far as I can tell there are no problems with the cert/key.

I guess the issue is just with the development server not the cert/key.

**Comment by rehandalal** [comment]
I have now also tried: 
- Creating a brand new VM with Ubuntu 18.04 instead of 16.04

While I still have an issue on the VM I was able to get normandy working using docker-compose. And as far as I can tell there are no problems with the cert/key.

I guess the issue is just with the development server not the cert/key.

**Comment by mythmon** [comment]
This is working fine for me on Ubuntu 18.04. I'm not sure what could be different between our environments. Reading the traceback, it is almost like the keys you're generating are bad somehow, but again I don't see what could cause that. Can you send me the cert and key file that you have in `etc/ssl/`?

**Comment by rehandalal** [comment]
Turns out my issue with my local Normandy was unrelated to this error and this error is just a side effect of how Firefox deals with certificates.

Closing as WONTFIX.
