### ISSUE TITLE
Hitting Auth0's rate limits when verifying the bearer token

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1416]
We sometimes hit [Auth0's rate limits](https://auth0.com/docs/policies/rate-limits) when making lots of requests to the API using bearer token authentication. This is because we verify the token on every request. We should implement some kind of caching to prevent this.

**Comment by mythmon** [comment]
While talking with security, the idea of caching was one they were very cautious about.

@jvehent Can you advise about how we should do this? We've talked about caching a token's validity for as long as the token is reported to be valid by auth0, or for some configurable, static amount of time. Do you have a preference?

**Comment by jvehent** [comment]
I'll defer to @gdestuynder's expertise here, he's the auth0 service owner.

**Comment by rehandalal** [comment]
From Auth0's docs:


Endpoint | Path | Limited By | Affected Tenants | Rate Limit
-- | -- | -- | -- | --
User Profile | /userinfo | User ID | All | 5 requests per minute with bursts of up to 10 requests

So we could simply cache for 15 seconds per bearer token and it would solve this issue. That's a very small cache window.

**Comment by peterbe** [comment]
@gdestuynder said:
```
<kang> we may have slightly different rate limit because we're on a different instance, but not very different
16:14 we also arent able to set these manually
16:14 P<peterbe> Ok. Interesting. 
16:14 Thanks for sharing. 
16:14 K<kang> that said, they both have a rate limit header and uhm, access token should be cached
16:14 i think that if we asked them and said the issue is that we hit the limit when re-issuing the token for each request they would tell us to cache it as intended and not raise limits
P
```

**Comment by mythmon** [comment]
I think instead of a hard coded rate limit, we should dynamically adjust the caching based on the rate limits included in the response. This is recommended in the auth0 docs. Maybe something like `timeUntilRefresh / rateLimitRemaining * 2`, i.e. aim to use about half of the rate limit. Half because maybe some other backend is also trying to 

From [the auth0 docs](https://auth0.com/docs/policies/rate-limits#authentication-api):

> Auth0 reserves the right to modify the rate limits at any time. For the up-to-date information on rate limits, please review the headers returned from rate limited endpoints.

**Comment by gdestuynder** [comment]
ideally I would recommend both respecting the rate limit and actually caching the access_token
the access_token and id_tokens are delivered with a validity period (`exp`) which can be used for this as well. In particular, note that the user profile endpoint data should be the same data as the id_token in auth0 (we have little control over this)

**Comment by mythmon** [comment]
I don't think we have access to the the validity period when verifying the tokens. We get an opaque token in the `Authorization` from clients (Delivery Console), and use that to access the `/userinfo` endpoint, which returns data like this:

```json
{
  "sub": "ad|Mozilla-LDAP|mcooper",
  "given_name": "Michael",
  "family_name": "Cooper",
  "nickname": "Michael Cooper",
  "name": "Michael Cooper",
  "picture": "https://s.gravatar.com/avatar/a971e3a64dcecd173a23edb1e8118a6c?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fmc.png",
  "updated_at": "2018-07-03T21:53:20.714Z",
  "email": "mcooper@mozilla.com",
  "email_verified": true,
  "https://sso.mozilla.com/claim/groups": [
    "<snip>"
  ],  
  "https://sso.mozilla.com/claim/README_FIRST": "Please refer to https://github.com/mozilla-iam/person-api in order to query Mozilla IAM CIS user profile data"
}
```

The headers provide the rate limit information, but nothing about the validity period.

**Comment by rehandalal** [comment]
@mythmon we get that info when we actually get the access token and we cache on the client side accordingly

**Comment by gdestuynder** [comment]
this looks like the `id_token` which should include `exp` (https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) depending on where/how you get it
I'm probably missing some things though :)
