### ISSUE TITLE
Remove Normandy-Admin

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1420]
Delivery Console has made normandy-admin obsolete.  We should remove the code from this repo.  This requires that DC is deemed ready and we are not losing any functionality. 

- [x] Add a deprecation warning #1415 
- [x] Deploy changes to staging, production environments
- [ ] Remove normandy-admin code from this repo

**Comment by rehandalal** [comment]
I think the first step for this is landing #1415. I think we should do that Monday.
