### ISSUE TITLE
Migrate Normandy to Remote Settings

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1440]
This was a topic we discussed in the Vancouver work week.  

This proposal is to transition Normandy to using Remote-Settings to get recipes to desktop clients.  

Some advantages this would bring: 

1. A heavy use case for remote-settings.  
1. Normandy benefits from all the remote-settings/kinto work we've done
1. Diff based updates.  Reduces bandwidth requirements 
1. Real time updates.  Benefits from remote-setting's broadcast support
1. Fewer servers to maintain.  We wouldn't need to run the public facing cluster
1. Separation of concerns: 
   - normandy-server manages business logic and workflows
   - remote-settings handles getting recipes to clients
1. ???

**Comment by mythmon** [comment]
This is definitely an exciting feature, and I think it will help Normandy become even more useful. The speed up from 24 hours to 6 was a big help, but 6 hours is still a relatively long time. It makes some users, especially relman, hesitant to use Normandy for certain things.

Some of the challenges we need to figure out as a part of this project include:

* Making Normandy-server update kinto when recipes change
* Making Normandy-client listen to updates from kinto
* Clients must run more often than just when recipes update. We'll need to figure out the strategy for this

> 4. Fewer servers to maintain. We wouldn't need to run the public facing cluster

I think we will still need the public facing cluster. Several groups use the public facing API to build dashboards and generally work with our data. We will be able to reduce the number of servers in that cluster though.

**Comment by leplatrem** [comment]
Current status: 
- client code was shipped (Fx 66, https://bugzilla.mozilla.org/show_bug.cgi?id=1506175, pref'ed off)
- server code was merged (https://github.com/mozilla/normandy/pull/1616)
- normandy collection was created (https://github.com/mozilla-services/remote-settings-permissions/pull/11)
- normandy account was created (https://bugzilla.mozilla.org/show_bug.cgi?id=1512466)

To be done:
- release and deploy Normandy v106
- enable integration in Normandy settings (cloudops repo, https://bugzilla.mozilla.org/show_bug.cgi?id=1513856)
- pref rollout for client switch (https://bugzilla.mozilla.org/show_bug.cgi?id=1513854)

**Comment by peterbe** [comment]
Also, https://docs.google.com/document/d/1usrPhnzZ9calM6APKVWViTdZmeY2WBM1VhW79QWcAwM/edit#

**Comment by leplatrem** [comment]
Current status:

* integration is working in STAGE :) 
* feature gates landed ([Bug 1519276](https://bugzilla.mozilla.org/show_bug.cgi?id=1519276))

To be done:

* deploy in PROD
* slowly onboard users using feature gate
