### ISSUE TITLE
Test that the docs build

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1441]
Depends on https://github.com/mozilla/normandy/pull/1435

If you make changes to the `.rst` files, our CI should test that the docs build. 
For example, something like this: https://github.com/mozilla/buildhub2/blob/a99b70dee53bf2ca04ddbfd4a05a515561972ef1/.circleci/config.yml#L78-L81

**Comment by peterbe** [comment]
Perhaps we can just copy [this from `delivery-console`](https://github.com/mozilla/delivery-console/blob/3c087ef8ba05e353b629ee8db1eb5c487ed20e7f/.circleci/config.yml#L73)

**Comment by mythmon** [comment]
:+1: I like this idea, and having as a separate job in the workflow would be good as well. Since it isn't related to the Docker image we publish, we don't need to complicate it with remote docker and docker-compose.
