### ISSUE TITLE
Remove use of product_details

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1449]
Need to investigate how product-details works and if it's the same stuff as Buildhub. 

Buildhub is a good place for getting aggregates such as "All possible locales" or "All possible versions for Firefox". Depending on Buildhub has the advantage that its data is near real-time. When a new version is built for the first time, it's value is available in Buildhub within seconds.

**Comment by mythmon** [comment]
The usage of mozilla-product-details is actually mostly legacy code we should remove. We may need something like this in the future when we build better UIs, but it may be more useful in Delivery Console. Though since Delivery Console is a static app, maybe Normandy should update from buildhub on a cron job, and expose that data to DC via an API? Or can DC pull from Buildhub directly?

**Comment by peterbe** [comment]
I was hoping to split that up. We *could* fetch that data from Buildhub directly in DC (not sure about CORS headers on Buildhub) or just use Normandy as a proxy (with cache and certainly the right CORS headers). 

I started poking around with how we *use* `product_details` in Normandy and I'm not yet any wiser. 

I also had another idea to see if I can completely convince `django-mozilla-product-details` to read from Buildhub instead. The code ultimately does some `requests.get()` to https://product-details.mozilla.org/1.0/ but being confident about a change like that doesn't seem lightweight. 

Perhaps if you can help me understand how and where we use this data in Normandy we can refactor Normandy to instead fetch from Buildhub on-the-fly (with caching) or, as you said, in a cron job. Cron is yucky but pretty nice in that it's then very unlikely to not have data. Granted, I could envision that people might want to refer to a new version (in a drop-down (e.g. UI for Filter Objects)) seconds/minutes after a new Firefox version has been built. 

Thoughts on that?

**Comment by peterbe** [comment]
Check out the new title of this issue. 

I like that. When we need values for drop-downs in the UI for Filter Objects we'll revisit.
