### ISSUE TITLE
Refactor all the DRY in vX api code

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1458]
Code repetition is rife in our code base. [See this report](https://gist.github.com/peterbe/0f97f5eb915fa66a878df229bdf37a44) (the first line demonstrates how to run it). 

It's a pain because when I made [this PR](https://github.com/mozilla/normandy/pull/1456) I had to put the same code in three different places (6 if you count the `test_*.py` files). 

I vaguely remember us talking about keeping v1 more or less forever (because it's used by the clients) and aggressively deprecating v2 (because it's only used my DC and the old legacy admin). 

If deprecation is hard, I'd rather we use subclassing and make things like v2 and v3 inherit from v1 in some way but I'm not sure how we're going to solve tests. We could consider refactoring the test code heavily and do things like this:

```python
def test_list_filter_channels_null_bytes(self, api_client):
    res = api_client.get("/api/v1/recipe/?channels=\x00")
    assert res.status_code == 400
    assert res.json()["channels"] == ["Null characters are not allowed."]

    res = api_client.get("/api/v2/recipe/?channels=\x00")
    assert res.status_code == 400
    assert res.json()["channels"] == ["Null characters are not allowed."]

    res = api_client.get("/api/v3/recipe/?channels=\x00")
    assert res.status_code == 400
    assert res.json()["channels"] == ["Null characters are not allowed."]
```

**Comment by mythmon** [comment]
We specifically chose to not de-duplicate the code between versions of the API, so that adding features to new APIs, and deprecating older APIs would be simpler. It also allows us to be very clear about what the tests do in each case. Not having to worry about breaking v1 while working on v3 is valuable.

It does make bug fixes like this one harder, but it makes other things easier. I think we should keep it the way it is now, but I'm open to other opinions.

**Comment by peterbe** [comment]
What's the state of the deprecation effort? 

In Socorro we tried to make informed decisions about which overly-liberal API endpoints we could deprecate by keeping stats on usage. 

Like, where are we in terms of v2 usage?

**Comment by mythmon** [comment]
Delivery Console still uses v2 exclusively. We'll need to work on DC before we can turn off the v2 API.

**Comment by rehandalal** [comment]
I opened this: https://github.com/mozilla/delivery-console/issues/401

**Comment by peterbe** [comment]
Let's not refactor things. Let's keep v1 as slim and simple as it is and that leaves [just v3](https://github.com/mozilla/normandy/issues/1694). If/when we do v4 and we need the same endpoints as v3 *had* I'd rather not refactor to avoid DRY but to come up with a better strategy. Reopen if you disagree.
