### ISSUE TITLE
Populate list of channels and locales from Buildhub

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1534]
We need this to feed the drop-down choices in Delivery Console for the Filter Object UI.

**Comment by peterbe** [comment]
Note-to-self; Let's use Buildhub only to populate `Locale`s and `Channel`(s) which we already have models for.

**Comment by peterbe** [comment]
Note-to-self; We can move this from v1 to v3 and https://normandy.cdn.mozilla.net/api/v1/filters/ for the benefit from Filter Object UI

**Comment by mythmon** [comment]
Careful with that. DC may already be using the v1 version of that.

**Comment by peterbe** [comment]
Ok. If it does, I might be able to change that too.

**Comment by peterbe** [comment]
I'm losing faith in this one. 

1. The list of channels you get from making an aggregate query on Buildhub is: `['beta', 'esr', 'nightly', 'release']`. Not only does it lack the full names like ["Developer Edition"](https://github.com/mozilla/normandy/blob/788f1831037dd4acfa5ad6b07dc92a7851410735/normandy/recipes/management/commands/initial_data.py#L31)
2. The [hardcode list](https://github.com/mozilla/normandy/blob/788f1831037dd4acfa5ad6b07dc92a7851410735/normandy/recipes/management/commands/initial_data.py#L29-L32) we currently depend on is very different from what you get out of Buildhub. For example, we don't have "esr" in *our* list and we have "aurora" (which we call "Developer Edition") which Buildhub doesn't yield. Feels like a big can of worms.
3. If we were to download all the possible locales from Buildhub today you'd get a list like this: `['ach', 'af', 'an', 'ar', 'as', 'ast', ...` but that doesn't give use the names like `['Acholi', 'Afrikaans', 'Aragonese', 'Arabic', 'Assamese', ...`. That information, the English names, is only available in product-details. [This file to be exact](https://product-details.mozilla.org/1.0/languages.json).
4. I compared *all* possible build locales in Buildhub with all locales in [that `languages.json`](https://product-details.mozilla.org/1.0/languages.json) and the difference that the `languages.json` has every locale that Buildhub has but it also has 54 more including things like `x-testing`. 

I'm tempted to just copy the `languages.json` file from product-details, stick it into our git repo and have a management command (e.g. `initial_data`) just populate the database with its content. 

We *could* get fancy and make a Buildhub query so that we don't get locales that we don't build at Mozilla in TaskCluster but that feels fragile because, what are you going to do, delete locales if they haven't been built in a log time.

What say you @mythmon ? Shall I just make a `requests.get` to `https://product-details.mozilla.org/1.0/languages.json`, or check in `languages.json`. I'm personally in favor of checking in the file and reading from it in `initial_data.py`.

**Comment by mythmon** [comment]
I'm sad to hear that buildhub doesn't have the details we need.

If we are going to be using product-details anyways, is there any reason not to revert back to the way we had it before, where we use a cron job to update DB tables sourced from product-details?

If not, I think that I'd prefer not checking in a copy of `languages.json`, and using our existing initial data systems to get that data. I imagine we'd forget to update the copy in our git repo and then get weird bugs because of stale data.

**Comment by sciurus** [comment]
> using our existing initial data systems to get that data

Could you elaborate on what you mean by that? I'm curious what data Normandy fetches from external sources and when it does it.

**Comment by peterbe** [comment]
> If we are going to be using product-details anyways, is there any reason not to revert back to the way we had it before

It would be an easy task to just revert that git commit. Granted, updating from product-details was slow, required another dependency, etc. More moving parts. 

All we need is a list of all languages but that list is very static and not even mozilla specific. And we only really need it 1 single time and that's when you start setting up your development environment. We don't even need it for CI. 

I suggest we make a management command that downloads [that URL](https://product-details.mozilla.org/1.0/languages.json) and mention it as a step you need when setting up your dev environment. 

Granted, checking in `languages.json` isn't all that different from using [`django_countries`](https://github.com/mozilla/normandy/blob/091bc5fc1df48867b97788ede09500fc9fc007df/requirements/default.txt#L28). The world's list of languages isn't going to change any time soon.

**Comment by mythmon** [comment]
> Granted, updating from product-details was slow, required another dependency, etc. More moving parts.

I don't have any evidence that it's alleged slowness was a problem for us in the past, and writing this ourselves is *also* another moving part. I'd rather modularize our dependencies instead of becoming a ball of mud.

> I suggest we make a management command that downloads that URL and mention it as a step you need when setting up your dev environment.

This is pretty close to what we had with product-details. We had a management command that populated the DB with the data from product details, and put that in our setup docs, and ran a cron job on the server.

**Comment by mythmon** [comment]
> Could you elaborate on what you mean by that? I'm curious what data Normandy fetches from external sources and when it does it.

Right now the only thing we fetch from an external source is the GeoIP database, and that's done at build time. In the we had a cron job that downloaded from product details and put that data into the database on a cron job.

**Comment by peterbe** [comment]
Going with this instead: https://github.com/mozilla/normandy/issues/1583
