### ISSUE TITLE
Increase cache ttl for self-repair

### ISSUE THREAD

**Issue by sciurus** [mozilla/normandy#1563]

**Comment by mythmon** [comment]
"self-repair" here refers to https://normandy.cdn.mozilla.net/en-US/repair/. This was the page that the predecessor of Normandy used. It was loaded in a background iframe and given some special privileges. Normandy used it as a shim while the system add-on was in development. We keep it around for very old Firefoxes that might still hit, but it is now simply a message explaining its own deprecation.

The current cache TTL is 30 seconds. Given that it isn't expect to change, but doesn't have a hashed URL, I suggest we give it a one day TTL.

It may also make sense to simply remove this URL entirely, but I'd like to hear more about how many hits we are still getting to it. We have theorized needing to re-activate this URL for some special circumstance where we needed to contact the Firefox clients still hitting it, and could do something with the limited capabilities the old system had. I think that time has probably passed now.

**Comment by sciurus** [comment]
self-repair is the only traffic to the elb named shield; you can see its traffic [here](https://app.datadoghq.com/dash/713690/normandy-traffic?live=true&page=0&is_auto=false&from_ts=1537824374254&to_ts=1538429174254&tile_size=m&fullscreen=290374165). It gets about 40 million hits a day. The most prominent user-agents in the logs are variations on Firefox/52.0.

**Comment by mythmon** [comment]
Ah, ok. Thanks for chekcing. ESR 52 didn't get the system add-on version of Normandy (even though Release 52 did). We'll have to keep supporting that for a while. Notably, ESR 52 is where we put all the Windows XP users, and was the last ESR release before Firefox 57 when we broke all the legacy extensions. It's going to be with us for a while. Lets bump the cache time so at least we don't have to spend as much supporting them. Maybe a week would be a better TTL, what do you think?

**Comment by sciurus** [comment]
Either sounds fine. There's no real harm in going longer, since in the off chance that we have to change the content we can invalidate the cached items.
