### ISSUE TITLE
Support Google Cloud Storage in addition to S3

### ISSUE THREAD

**Issue by sciurus** [mozilla/normandy#1566]
Normandy admin currently uploads addons to an S3 bucket. Normandy should support uploading to a GCS bucket as well. 

Currently we have an DJANGO_AWS_STORAGE_BUCKET_NAME bucket name. Maybe we could also have a DJANGO_GCS_STORAGE_BUCKET_NAME, and the one that is set determines which storage to use?

**Comment by mythmon** [comment]
Our storages library [provides a lot of settings](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#settings). I think the only one there we will need to expose is `GS_BUCKET_NAME` (which will be mapped to `DJANGO_GS_BUCKET_NAME`. @sciurus are there any other setting in that list you will want to set? It is easy to add more later, but it would be nice to start with a useful set.

We'll likely just directly expose more of the library's settings. The result would look like this:

```env
# Set the file storage to Google Cloud
DJANGO_DEFAULT_FILE_STORAGE='storages.backends.gcloud.GoogleCloudStorage'
# Poit to the right bucket
DJANGO_GS_BUCKET_NAME=...
```

**Comment by sciurus** [comment]
I think those two will do it!
