### ISSUE TITLE
PreferenceRollouts.closeDB is not a function

### ISSUE THREAD

**Issue by pdehaan** [mozilla/normandy#1618]
Trying to test https://github.com/motin/jestr-pioneer-shield-study w/ signed add-on in Nightly and spotted this in the Browser Console output:

![browser_console_and_new_issue_ _mozilla_normandy](https://user-images.githubusercontent.com/557895/48435928-6396ac00-e732-11e8-88f9-750914f5e094.png)

```
PreferenceRollouts.closeDB is not a function (PreferenceRolloutAction.jsm:173)
  _finalize (resource://normandy/actions/PreferenceRolloutAction.jsm:173:11)
  InterpretGeneratorResume (self-hosted:1255:8)
  next (self-hosted:1210:9)

PreferenceRollouts.closeDB is not a function (PreferenceRollbackAction.jsm:58)
  _finalize (resource://normandy/actions/PreferenceRollbackAction.jsm:58:11)
  InterpretGeneratorResume (self-hosted:1255:8)
  next (self-hosted:1210:9)
```

<img width="675" alt="firefox_nightly_first_run_page" src="https://user-images.githubusercontent.com/557895/48436133-e0298a80-e732-11e8-9a65-3765ad1ccaf8.png">

**Comment by mythmon** [comment]
Thanks for the report. The Firefox client portion of Normandy is in-tree and bugs are handled in Bugzilla. This is already reported there as [bug 1506816](https://bugzilla.mozilla.org/show_bug.cgi?id=1506816). I hope that this won't affect your testing of the Jestr study.
