### ISSUE TITLE
Rename opt-out-study action

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1631]
One of the current actions is `opt-out-studies`. It is entirely not obvious that what this action does is install an add-on for a limited period of time. The implementation of the client-side action in Firefox is named `AddonStudyAction`. Another proposed name is add-on experiment. We should change the name of this action to something that makes its purpose clearer.

There are some users of the API that depend on the names of these actions. Specifically Delivery Console, but I believe there are also some data analysis tools that rely on the names as well. We'll need to coordinate with these users to make sure that other systems update as well.

This issue is not time sensitive, and depending on the name we choose, may actually need to wait for Firefox changes to happen as well. This issue covers choosing a new name, renaming the action in our repository, making sure that the action in the DB on the server is updated (instead of duplicated), and communicating with any external users that may need to change as well.

**Comment by mythmon** [comment]
As an implementation note, I think that naive thing of replacing most of the names in the code will work, with the exception of the `update_actions` management command. That command will need to figure out how to rename the existing action so that the existing recipes update correctly. Alternatively, we may want to do this with a database migration.

**Comment by peterbe** [comment]
@rehandalal Is this related to the work you're doing in Delivery Console on this name transition? Should you maybe assign it to yourself?

**Comment by shell1** [comment]
likely don't need this anymore 
3 different ways: 
opt-out - old ones.
add-on study: don't need this one, never used.
branched add-on study: new one
