### ISSUE TITLE
Incorrect README.md Link

### ISSUE THREAD

**Issue by Wittiest** [mozilla/normandy#1675]
## Problem
The "Developer Setup" link in the README.md gives a 404:
https://normandy.readthedocs.io/en/latest/dev/install.html
The following link works:
https://normandy.readthedocs.io/dev/install.html
## Speculation
I've noticed this isn't the usual behavior of links on readthedocs.io. For example, 
https://docs.readthedocs.io/en/latest/index.html
https://docs.readthedocs.io/index.html

The first link works and the second does not. This could be related to the fact that other documents seem to have a separate /en/latest and /en/stable releases, but normandy seems to have just the normandy.readthedocs.io link (which is the latest/stable release)

## Proposed Solutions
Change the link to https://normandy.readthedocs.io/dev/install.html
||
Configure the docs to make the /en/latest/ link function.

**Comment by mythmon** [comment]
Thanks for the report @Wittiest. This is related to a recent change that removed localization and versioning from the readthedocs setup. It's not the default, but I think it is right for Normandy.

I think that updating the README to use the new link is the right choice. Would you like to make a PR for that?

**Comment by Wittiest** [comment]
Addressed in PR #1682
