### ISSUE TITLE
Delete all v2 API

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1694]
See https://github.com/mozilla/delivery-console/pull/638#event-2076464360

**Comment by peterbe** [comment]
Perhaps it's dead-obvious but we should take our time with this one. Once we know that the new v3 usage in delivery console is in Production and works solidly.

**Comment by mythmon** [comment]
@sciurus Is it possible to get (or can you show me how to get) metrics for how much `/api/v2/*` is being used? Now that Delivery Console is using the v3 API, I expect that most of our users will be gone, but I'd like to look a bit more.

**Comment by peterbe** [comment]
@mythmon How about adding something like [markus](https://github.com/willkg/markus) to statsd send various events that our django_rest stuff does. Then we could plot these kinds of questions in Datadog/Grafana and also, as a bonus, get timings on how long it takes for our Django to render those views.

**Comment by mythmon** [comment]
I'll leave that decision up to @sciurus. I don't care if we do this via statsd or request logs.

I checked out the logs, and I agree that we don't have any users of v2 in the last day. I think we probably ought to wait about a week to make sure no one else is using it more intermittently.

**Comment by peterbe** [comment]
>  That links to a search for any load balancer logs that include `/api/v2/` in the last 24 hours. There were none.

With that in mind, I'd favor being bold and going ahead.
