### ISSUE TITLE
Add filter object for profile creation date

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1714]
One of the types of targeting that is needed occasionally is to distinguish between new and existing users. The way this is usually done is to pick a particular date, and declare that any profile created before this date is an existing user, and any profile created after this date is a new user.

This data is available in Telemetry via a variable known as `profile.creationDate`, often abbreviated PCD. Because this value is in telemetry,  it is affected by [bug 1472781](https://bugzilla.mozilla.org/show_bug.cgi?id=1472781): It isn't available during the Telemetry session. Because of this, the JEXL for this type of targeting is more complex than usual. Here's an example:

```jexl
!normandy.telemetry.main ||
normandy.telemetry.main.environment.profile.creationDate > 17483
```

Of note is the units of `creationDate`: it is specified in *days* since January 1st 1970. The reduced precision is to limit the finger-printability of this metric. As such, the value `17483` represents November 13th 2017 (the release of Firefox 57). This particular value was used several times to target users that started using Firefox after the Quantum release.

I propose this structure for the filter object:

```json
{
    "type": "profileCreationDate",
    "direction": "olderThan",
    "date": "2019-02-01",
}
```

The key `direction` can have either the key "olderThan" or "youngerThan". The key `date` is an ISO8601 formatted **date**. Since PCD is given in terms of days, there is no use in being more precise.

The filter expression renderer will need to convert from the date given to the units of "days since epoch".

Alternatives include having separate filter objects for "profile older than" and "profile newer than", or allowing one or two dates to be specified, such as 

```json
{
    "type": "profileCreationDate",
    "notBefore": "2019-02-01",
    "notAfter": "2019-03-01",
}
```

Each key would be optional, but at least one would be required. This kind of ranged PCD filter is less common, but may still be useful.

**Comment by mythmon** [comment]
@peterbe what are you thoughts on this filter expression?

**Comment by shell1** [comment]
Don't have any range or comparison filter objects yet - would be first of kind.
