### ISSUE TITLE
Stop setting HSTS headers

### ISSUE THREAD

**Issue by sciurus** [mozilla/normandy#1762]
We are standardizing on doing this in the infra code instead.

**Comment by mythmon** [comment]
While reviewing the code to do this, I found that this can be configured without a code change. Setting `DJANGO_SECURE_HSTS_SECONDS=0` will cause the security middleware [to not send the header](https://docs.djangoproject.com/en/2.1/ref/middleware/#http-strict-transport-security).

@sciurus does that work for you, or would you prefer having a code change to disable this by default?

**Comment by sciurus** [comment]
That WFM.
