### ISSUE TITLE
Remove the Django Admin

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1773]
With the migration to GCP, we no longer use the Django Admin, at `/admin`. It isn't possible to authenticate to it, and we have replaced it's use cases with other tools. We should remove it entirely.

**Comment by peterbe** [comment]
Actually, https://github.com/mozilla/normandy/issues/1775 might get solved by *this* issue when we tackle it.

**Comment by mostlygeek** [comment]
Didn't we still need django admin to manage admin users?  How do we do that now?

**Comment by rehandalal** [comment]
We have the user API that I wrote in #1626.
