### ISSUE TITLE
Is CONN_MAX_AGE working and can be increase the default?

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1783]
See:

```
▶ DJANGO_CONN_MAX_AGE=50 ./manage.py shell
...

In [1]: from django.conf import settings

In [2]: settings.CONN_MAX_AGE
Out[2]: 50

In [3]: settings.DATABASES
Out[3]:
{'default': {'NAME': 'normandy',
  'USER': 'postgres',
  'PASSWORD': '',
  'HOST': 'localhost',
  'PORT': '',
  'CONN_MAX_AGE': 0,
  'ENGINE': 'django.db.backends.postgresql_psycopg2',
  'ATOMIC_REQUESTS': False,
  'AUTOCOMMIT': True,
  'OPTIONS': {},
  'TIME_ZONE': None,
  'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}}

```

I.e. the integer is set but it's not incorporated into the `DATABASES` config. 

[In Tecken](https://github.com/mozilla-services/tecken/blob/e49cc259aa968a7d988800d09fc8460b3e30a6e6/tecken/apps.py#L42-L47) I had to use the `TeckenAppConfig.ready` thing to set this. But don't remember the reasons exactly. It uses django-configurations too.

**Comment by peterbe** [comment]
Also, the default is [currently set to `0`](https://github.com/mozilla/normandy/blob/5718076dcf8dd79caf0a4d8a2ab0f618276e906c/normandy/settings.py#L259) which I don't know if we should even make it configurable because ideally, we should have a similar non-zero setting in local dev, Stage, and Prod.

**Comment by peterbe** [comment]
By the way, if we have pgBouncer, in production, in front of PostgreSQL I don't think we should set CONN_MAX_AGE. Or, alternatives like pgBouncer that I might not know the name of.

**Comment by sciurus** [comment]
We don't use anything like pgBouncer.

Normandy connects so infrequently to the database, and latency is so low, there's likely little benefit in enabling connection pooling.

<img width="2288" alt="screen shot 2019-03-04 at 10 45 00" src="https://user-images.githubusercontent.com/677595/53744254-9f34bd80-3e6a-11e9-8902-c0f14dbb0285.png">

**Comment by peterbe** [comment]
I'm not sure what I'm looking at but the average on that graph seems to be ~2. Does that mean 2ms to make a database connection?

**Comment by sciurus** [comment]
No, that connection shows how many connections there are to the database. Mainly, I wanted to show that frequently there aren't any active connections at all.

**Comment by peterbe** [comment]
Actually, with that in mind, I don't think it's worth it. Normandy's flaw is that a bunch of requests are horribly in that they require tonnes of SQL selects per request but the requests themselves retain the connection within.

We could morph this issue to clean up the incorrect usage of `CONN_MAX_AGE` as an env var that doesn't get into the database connection even if you set it.

**Comment by mythmon** [comment]
> Actually, with that in mind, I don't think it's worth it.

I agree

> We could morph this issue to clean up the incorrect usage of `CONN_MAX_AGE` as an env var that doesn't get into the database connection even if you set it.

That seems like a good idea. Settings that don't do anything are bad. We should either fix it like you propose, or remove the setting (since we don't really use it much).

**Comment by shell1** [comment]
if we ever tried to perf tune normandy - this would be one of the tasks.  we're closing for now.

**Comment by cpre20068** [comment]
Thank you very much. My issue has been fixed.
