### ISSUE TITLE
Add instrumentation to web requests

### ISSUE THREAD

**Issue by sciurus** [mozilla/normandy#1789]
Let's add some basic instrumentation to Normandy like we did for classify client in https://github.com/mozilla/classify-client/issues/41 . In normal operation we can use this instead of New Relic. It will have the advantage of being usable on the admin hosts too, where we're unwilling to use New Relic.

A timer named something like `normandy.request` that records request handling time and is tagged with the view name (or some other appropriate identifier) and the http response code class (e.g. 2xx, 3xx) would be a great start. I think that would be straightforward to do via a django middleware.

https://github.com/willkg/markus is used in some of our other python projects for recording metrics.

We'll need environment variables to set the statsd server host and port.

**Comment by peterbe** [comment]
We could add a million metrics but how about we start with A) installing it and making it env var configurable, and B) a metric on each request/response via a Django middleware. 

Tecken uses `markus` too. But it uses `"markus.backends.datadog.DatadogMetrics"` as the default backend and it has `datadog==X.X.X` in the requirements.txt. Is that a bad idea? Should we avoid Datadog? We could make a no-op be the default for now or perhaps the `markus.backends.statsd.StatsdMetrics` backend.

**Comment by sciurus** [comment]
You'll want to use the DatadogMetrics backend so you can publish datadog-style tags.

**Comment by mythmon** [comment]
Fixed in #1856.
