### ISSUE TITLE
The "opt-out-study" study names are not unique

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/normandy#1791]
*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

*[Affected Versions]:*
- Firefox Nightly 67.0a1

*[Prerequisites]:*
- Have access to the [delivery console](http://delivery-console.stage.mozaws.net/).
- Have a "opt-out-study" recipe already created.

*[Steps to reproduce]:*
1. Navigate to http://delivery-console.stage.mozaws.net/.
2. Create an opt-out-study recipe with the same study name as the one from prerequisites.
3. Click the "Save" button and observe the behavior.

*[Expected result]:*
- An error is shown explaining that the "Experiment name" MUST be unique.

*[Actual result]:*
- The recipe is successfully created and can be published without any errors.

*[Notes]:*
- The issue is not reproducible for the "preference-experiment", "show-heartbeat" and "preference-rollout" recipes. 
- Attached a screen recording with the issue:
![unique](https://user-images.githubusercontent.com/19226534/53961394-24310880-40f1-11e9-8305-4f806880f63e.gif)

**Comment by mythmon** [comment]
Specifically, we often use this field as an identifier in telemetry, so duplicate names will be confusing.
