### ISSUE TITLE
Archive mozilla-normandy-action-argument-schemas on npmjs?

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1821]
Old: https://www.npmjs.com/package/mozilla-normandy-action-argument-schemas

New: https://www.npmjs.com/package/@mozilla/normandy-action-argument-schemas

Both are fed from the same [README](https://searchfox.org/mozilla-central/source/toolkit/components/normandy/actions/schemas/README.md) so I don't think it's an option to edit that to say that `@mozilla/normandy-action-argument-schemas` is the new hotness. 

Can whoever owns `mozilla-normandy-action-argument-schemas` on npmjs change it to mark it obsolete or something?

**Comment by mythmon** [comment]
I marked the old package as deprecated in favor of the new one. It seems I can't remove the old package entirely though. I think that's good enough for now.

**Comment by peterbe** [comment]
Neat! I've actually never even seen that npmjs feature before. Thanks
