### ISSUE TITLE
v3 Contract tests are failing with 'default' is a required property

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1826]
The contract tests on master are failing with an error. This is blocking CI.

```
jsonschema.exceptions.ValidationError: 'default' is a required property
```

See this CI run for more details: https://circleci.com/gh/mozilla/normandy/8631

**Comment by mythmon** [comment]
After more investigation, I've learned that this is an intermittent problem. In [this CI log](https://circleci.com/gh/mozilla/workflows/normandy/tree/pull%2F1825),  I have two commits, each of which I retried twice. Each one failed once and passed once.

**Comment by shell1** [comment]
mythmon wanted to close and does't rememnber seeing in a while
