### ISSUE TITLE
Upgrade Django to 2.2

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1834]
In #1832, pyup tried to update Django to 2.2. That caused a bunch of test failures I had trouble resolving locally. In the interest of not leaving things open, I pulled out that upgrade to handle it in a separate branch.

**Comment by mythmon** [comment]
After spending significant time on this, I think that there is either a bug in Django 2.2, or a very subtle bug in Normandy. I wasn't able to reproduce the bug in a small test project though, so I'm not going to file a bug.

For now, I'm going to wait until 2.2.1 is released, and hope it fixes the issue we saw, or more people on the internet have a chance to upgrade and can reveal what we did wrong.

**Comment by rehandalal** [comment]
Seems to be resolved in 2.2.3
