### ISSUE TITLE
"normandy.experiments.*" additional filters no longer work for add-on studies

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/normandy#1851]
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Versions]:**
- Firefox Nightly 68.0a1
- Firefox Beta 67.0b10
- Firefox Release 66.0.3

**[Prerequisites]:**
- Have access to the delivery console.
- Have a profile has or has been in an optout study.
- Have "devtools.chrome.enabled" set to "true" in about:config.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the Browser Console and paste the following :
Cu.import("resource://normandy/lib/RecipeRunner.jsm", {})
  .RecipeRunner.checkFilter({
    id: 1,
    arguments: {},
    filter_expression: `
      (
"<name of experiment>" in normandy.experiments.all
      )
    `,
  })
  .then(result => console.log(result)) 
3. Change the <name of experiment> string with the name of the optout experiment that the profile is or was in.
4. Press Enter and observe the console output.

**[Expected result]:**
- The console returns the "true" value because the profile is/has been in the experiment.

**[Actual result]:**
- The console returns the "false" value.

**[Notes]:**
- The issue is also reproducible with the "normandy.experiments.active" and "normandy.experiments.expired" filters.
- The issue when trying to filter users that have been/are in a "preference-experiment".
- Attached a screen shots with the issue:
  **- working for pref experiments:**
![pref-experiment-console-output](https://user-images.githubusercontent.com/18304511/56130469-a54fab00-5f8d-11e9-8105-8bf8e2cfd79b.png)

  **- not working for addon experiments:**
![optout-experiment-console-output](https://user-images.githubusercontent.com/18304511/56130484-b0a2d680-5f8d-11e9-9251-6f00235330e9.png)

**Comment by mythmon** [comment]
First, this is a Normandy client problem, which should be tracked in Bugzilla. This repository is specifically the server component of Normandy.

Second, in your report you say this "no longer works". As far as I know this never worked: we only implemented it for preference experiments. This isn't a regression, but actually a missing feature. It would be a great feature to have though.
