### ISSUE TITLE
Add instrumentation to update_signatures

### ISSUE THREAD

**Issue by sciurus** [mozilla/normandy#1854]
We need a way to monitor the daily update_signatures command. If update_signatures submitted metrics for the  number of recipes and actions it signed and unsigned, we could alert if the data is missing for more than 24 hours.

Collecting this data would also give us a nicer way to see what it's doing than reading the logs.

Metrics library and config for this could be the same as #1789 

https://bugzilla.mozilla.org/show_bug.cgi?id=1538417

**Comment by mythmon** [comment]
@sciurus Do you have any ideas for what this metric should be called?

Things I think would be good to capture:

* Signing recipes vs actions (vs other things possibly in the future)
* Whether the update was forced or note
* How many things had their signatures removed

**Comment by sciurus** [comment]
What you put in the PR LGTM.

**Comment by mythmon** [comment]
Fixed in #1856.
