### ISSUE TITLE
Publish recipes that require "non-baseline" capabilities to a separate collection

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1935]
Once Normandy can identify the capabilities a recipe needs (#1932), we should distinguish recipes that only requires "baseline capabilities" from those that require more. Recipes that only require baseline capabilities should be published in the existing Remote Settings collection (`normandy-recipes`), and those that don't should only be published in a separate collection (`normandy-recipes-capabilities`).

Additionally, this separation should apply to recipes published in the v1 `/api/v1/recipe/signed/` endpoint that older Firefox clients read from. Recipes that require more than the baseline should not be published in that endpoint. Optionally we can enable showing non-baseline recipes in this endpoint with a special query string, such as `/api/v1/recipe/signed/?capabilities=v1`

The baseline capabilities should be defined as the capabilities that are supported by versions of Firefox that don't check capabilities. Versions of Firefox that support capabilities should read from the new collection.

Although older versions of Firefox do not check capabilities, if they did most versions would support these capabilities, and so I propose we use this set as the baseline.

* `action.addon-study`
* `action.console-log`
* `action.preference-rollback`
* `action.preference-rollout`
* `action.show-heartbeat`
* `action.single-preference-experiment`
* `action.opt-out-study`
* `action.preference-experiment`
* `jexl.transform.date`
* `jexl.transform.stableSample`
* `jexl.transform.bucketSample`
* `jexl.transform.preferenceValue`
* `jexl.transform.preferenceIsUserSet`
* `jexl.transform.preferenceExists`
* `jexl.transform.keys`

Notably this leaves out the following JEXL transforms that are implemented in Firefox 68.

* `jexl.transform.length` - Added in Firefox 63
* `jexl.transform.mapToProperty` - Added in Firefox 63
* `jexl.transform.regExpMatch` - Added in Firefox 68
* `jexl.transform.versionCompare` - Added in Firefox 68

Since none of these are present in ESR 60, I suggest that we do not include them in the baseline. This means we would not be taking full advantage of the available resource of Firefox 63-68. We have not used these filters significantly so far due to backwards compatibility concerns. (This is the motivating point behind Normandy capabilities). I think this is the right balance to strike.

**Comment by shell1** [comment]
jared going through and mythmon and him will mindmeld on the plan
