### ISSUE TITLE
Cascaded revision deletions can cause weird data

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1941]
We recently encountered an issue on stage where deleting an action caused a cascade that resulted in all the revisions for a recipe being deleted and the `latest_revision` and `approved_revision` on that recipe being set to `None`.

Maybe we should handle this better? 

Or perhaps we should have a script we can run to clean up bad recipes?

**Comment by rehandalal** [comment]
This is a related sentry error:
https://sentry.prod.mozaws.net/operations/normandy-stage/issues/6121853/

**Comment by mythmon** [comment]
Note: Deleting an action is not common, and in fact can only be done with a SQL or Python shell on the admin server, not via any HTTP request. I think that one of the a valid solutions here is "do nothing", and be more careful next time.

**Comment by shell1** [comment]
agreed to close.  have this record.  if we hit this again will file new.
