### ISSUE TITLE
Docs aren't being published

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1942]
In CircleCI our `docs-publish` job is failing with this error:

```
$ gh-pages --dotfiles --message "[skip ci] Docs updates" --dist docs/_build/html

The "file" argument must be of type string. Received type undefined
Exited with code 1
```

Here is an example CI job: https://circleci.com/gh/mozilla/normandy/12787

This job only runs on master, so bors hasn't noticed it. This problem seems to have started recently. I'd guess it is because we don't actually pin a version of the `gh-pages` tool, and install it via `npm install gh-pages@2`. We should probably move this to package.json and manage it like all the other Node dependencies.

**Comment by glasserc** [comment]
This build failure seems to have stopped as of `gh-pages 2.1.1`: https://circleci.com/gh/mozilla/normandy/13389. See https://github.com/tschaub/gh-pages/pull/312. But I still think the idea of explicitly versioning `gh-pages` is valuable, so I'll do that.
