### ISSUE TITLE
Release v1.128.x

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#2036]
Welcome Release Captain!  ⛵️

- [x] Assign this issue to yourself
- [x] Create 1.129.0 Milestone (due date two weeks from when you read this)
  - [x] Move all open tickets in milestone 1.128.0 to 1.129.0 if any
- [x] Close 1.128.0 Milestone
- [x] Approve and merge all open dependabot/renovate/pyup PRs by adding a `bors merge` comment to the PR. 
- [x] Pull master
- [x] Ensure all linting and tests pass with docker: `make check`
- [x] `git tag v1.128.0; git push --tags`
  - pushing a tag triggers a stage deployment automatically
- [x] in #normandy, write: `@here deploying normandy v1.128.0 to stage https://github.com/mozilla/normandy/milestone/12?closed=1`
- [x] Verify that stage loads with v1.128.0
  - [x] Wait for delivery notifications in #delivery-notifications to indicate that stage is being built and deployed
  - [x] Verify that https://stage.normandy.nonprod.cloudops.mozgcp.net/__version__ shows the new version number
  - [x] Fetch https://stage.normandy.nonprod.cloudops.mozgcp.net/api/v3/recipe/ or some other endpoint and verify that you get a 200
- [x] File [Bugzilla Release Bug](https://bugzilla.mozilla.org/enter_bug.cgi?format=__default__&product=Cloud%20Services&component=Operations%3A%20Normandy) with content copied from `./bin/generate_deploy_bug.py v1.127.0 v1.128.0` 
   - on mac: `python3 ./bin/generate_deploy_bug.py v1.127.0 v1.128.0`
- [x] Add QA `:cmuresan` as QA contact on the bugzilla ticket
- [x] Add release bug to comments in this issue
- [ ] Await QA green sign off
  - if there was a bug found, generate a point release, push the new tag and let QA know to test again.
- [ ] `@bpitts please deploy normandy v1.128.X to prod <bugzilla link>` in #normandy where X is last point release and <bugzilla link> is the link to the bugzilla ticket created above
- [ ] Verify that https://normandy.cdn.mozilla.net/__version__ shows the correct version number
- [ ] Fetch https://normandy.cdn.mozilla.net/api/v3/recipe/ to verify it returns a 200
- [ ] Create release issue for Release v1.128.0

**Comment by tiftran** [comment]
Bugzilla Release Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1602036

**Comment by tiftran** [comment]
closing as 1.130 has been deployed
