### ISSUE TITLE
Filter Object: OS

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2101]
Let's add a filter object for filtering OS, I guess the options look something like:

Windows
OSX
Linux

We need to be able to filter for multiple OS's but it's not clear to me whether a single instance of this filter object takes a single OS parameter and then we can OR multiple of them togethether? @mythmon ?

**Comment by mythmon** [comment]
Lets follow the same pattern we do with Locale, Country, etc and make this filter on multiple OS's. We currently can't OR together filter objects, so depending on that will make things more difficult.
