### ISSUE TITLE
Filter Object: Pref

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2103]
We need a filter object that takes a pref and optionally a value and supports the following options:

- eq
- neq
- gt
- lt
- is_user_set (this can be either true or false)

**Comment by uhlissuh** [comment]
also preferenceExists?

**Comment by mythmon** [comment]
It seems like preferenceExists is less common, but still used occasionally. If it's not a pain, might as well.

**Comment by uhlissuh** [comment]
I don't see a case where value would need to be optional?

**Comment by mythmon** [comment]
I'm sorry. I don't quite understand what you're saying. Do you have a question about the implementation, or about design? Your sentence is a statement, but it has a question mark. I just don't follow.

**Comment by uhlissuh** [comment]
I don't see a case where value would need to be optional.

**Comment by mythmon** [comment]
Oh, I see. Thanks for clarifying. I think that the optional part might have been for `is_user_set` and friends. After seeing it in action that split between the simple comparisons and the complicated ones seems a bit odd.

**Comment by jaredlockhart** [comment]
Yeah exactly, I was thinking of cases like is_user_set or pref_exists where it only cares about the pref name.
