### ISSUE TITLE
Filter Object: Addon

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2104]
We need a filter object for filtering for the presence of an addon by its addon id.  I think if we want to exclude an addon we will have to combine this with https://github.com/mozilla/normandy/issues/2105

**Comment by uhlissuh** [comment]
I see two representations of addons on the filter expressions. One looks like `normandy.addons['uBlock0@raymondhill.net'].isActive` and often times, several of these get strung together with `||`. The other I see is something like `normandy.addons[\"@asdfjhsdfuhw\"]` without the `isActive` part (also string together with `||`s).. and the addon string is looks different between these two things. 

What is the difference between these two items?

**Comment by mythmon** [comment]
If you are seeing `\` in filter expressions in something like Delivery Console or NDT, those are probably bugs in the recipes. On the API though that might just be normal string escaping.

`normandy.addons` is an object where the keys are add-on IDs (which can be anything including `uBlock0@raymondhill.net`, `@asdfjhsdfuhw`, or even just UUIDs), and the values are an object describing details about that add-on. Here's an example from my own profile:

```
normandy.addons["{446900e4-71c2-419f-a6a7-df9c091e268b}"]
```
```json
{
  "id": "{446900e4-71c2-419f-a6a7-df9c091e268b}",
  "isActive": true,
  "name": "Bitwarden - Free Password Manager",
  "type": "extension",
  "version": "1.42.2",
  "installDate": "2020-02-21T00:16:14.000Z"
}

A filter like `normandy.addons[\"@asdfjhsdfuhw\"]` asks "is this add-on installed". A filter like `normandy.addons['uBlock0@raymondhill.net'].isActive` asks "is this add-on installed and enabled", which is a stricter check. Both are useful in some cases.

For example, if we want to test out a new password manager feature, we might exclude users that already have a well known password manager. In this case we want to know if it is enabled, because if it is disabled they aren't using. In this case we'd use `normandy.addons[...].isActive`.

Another example would be trying to mitigate the damage that a malware add-on has done. In this case, we would want to test if the add-on is present, even if it was disabled (since it could have done the damage and then disabled itself). In this case we'd just use `normandy.addons[...]`. If the add-on is installed, that will evaluate to a truthy value, and if the add-on is not installed, that will evaluate to undefined.

**Comment by uhlissuh** [comment]
OK thanks for the clarification.
