### ISSUE TITLE
Automatically generating system user for v3 API tests

### ISSUE THREAD

**Issue by chartjes** [mozilla/normandy#2122]
I am at a point where I am ready to submit a PR for the test of the v3 API contract tests. Current status using the tests running against a Dockerized version of the API:

contract-tests/v3_api/test_action_list.py::test_action_list PASSED                                                                                                        
contract-tests/v3_api/test_action_read.py::test_action_read PASSED                                                                                                        
contract-tests/v3_api/test_approval_request.py::test_approval_request PASSED                                                                                              
contract-tests/v3_api/test_approval_request_close.py::test_approval_request_close PASSED                                                                                  
contract-tests/v3_api/test_approval_request_list.py::test_approval_request_list PASSED                                                                                    
contract-tests/v3_api/test_approval_request_read.py::test_approval_request_read PASSED                                                                                    
contract-tests/v3_api/test_approval_request_reject.py::test_approval_request_reject PASSED                                                                                
contract-tests/v3_api/test_extension_list.py::test_extension_list PASSED                                                                                                  
contract-tests/v3_api/test_extension_read.py::test_extension_read SKIPPED                                                                                                 
contract-tests/v3_api/test_filters_list.py::test_filters_list PASSED                                                                                                      
contract-tests/v3_api/test_group_create.py::test_group_create PASSED                                                                                                      
contract-tests/v3_api/test_group_delete.py::test_group_delete PASSED                                                                                                      
contract-tests/v3_api/test_group_list.py::test_group_list PASSED                                                                                                          
contract-tests/v3_api/test_group_partial_update.py::test_group_partial_update PASSED                                                                                      
contract-tests/v3_api/test_group_update.py::test_group_update PASSED                                                                                                      
contract-tests/v3_api/test_list.py::test_list PASSED                                                                                                                      
contract-tests/v3_api/test_recipe_delete.py::test_recipe_delete PASSED                                                                                                    
contract-tests/v3_api/test_recipe_disable.py::test_recipe_disable PASSED                                                                                                  
contract-tests/v3_api/test_recipe_enable.py::test_recipe_enable PASSED                                                                                                    
contract-tests/v3_api/test_recipe_history.py::test_recipe_history PASSED                                                                                                  
contract-tests/v3_api/test_recipe_list.py::test_recipe_list PASSED                                                                                                        
contract-tests/v3_api/test_recipe_read.py::test_recipe_read PASSED                                                                                                        
contract-tests/v3_api/test_recipe_revision_list.py::test_recipe_revision_list PASSED                                                                                      
contract-tests/v3_api/test_recipe_revision_read.py::test_recipe_revision_read PASSED                                                                                      
contract-tests/v3_api/test_recipe_update.py::test_approval_request_reject PASSED                                                                                          
contract-tests/v3_api/test_service_info_list.py::test_service_info_list PASSED                                                                                            
contract-tests/v3_api/test_user_create.py::test_user_create PASSED                                                                                                        
contract-tests/v3_api/test_user_delete.py::test_user_delete PASSED                                                                                                        
contract-tests/v3_api/test_user_list.py::test_user_list PASSED                                                                                                            
contract-tests/v3_api/test_user_partial_update.py::test_user_partial_update PASSED                                                                                        
contract-tests/v3_api/test_user_read.py::test_user_read PASSED                                                                                                            
contract-tests/v3_api/test_user_update.py::test_user_update PASSED

These tests are currently using a hard-coded system user generated using the 'make createuser' command. Is there a way to automatically generate a system user (the tests use {'Authorization': 'Insecure <email address here>'} header) and store those values somewhere the tests can use?

**Comment by mythmon** [comment]
Users are stored in the database, and the database for CI is ephemeral and recreated for every Circle job that runs. If another part of the system was handling this, it would be done using the same command seconds before running the tests ran. Using the insecure email authorization method is appropriate in this case.

If you are concerned about being compatible with other environments, you could make this configurable. You could also test if the user exists (by trying to use it against the `/api/v3/user/me/` endpoint), and if it doesn't doesn't then calling `make createuser`.

**Comment by chartjes** [comment]
@mythmon I understand the database goes away. My question is how, in a CI environment, can I create a superuser on every execution of the test suite and have that email address available for the tests to use?

**Comment by mythmon** [comment]
`make createuser` can be called in CI to generate a user with a fixed email (If it doesn't already support some kind of flag system, you could echo values into it). That email can then be passed as an argument to the test system. All of that should work fine in Circle. The tools seem to be here. Is there a problem I'm missing?

**Comment by chartjes** [comment]
No, you are not missing anything. I am not familiar with Django and it's various commands so I thought I would ask someone who is what my options are. You have given me enough to start and if I have any more questions I cannot answer on my own I will open up a separate issue here.

**Comment by jaredlockhart** [comment]
@chartjes Just to tack on to what @mythmon was saying, for example in the current contract tests, we run some django management commands to setup the database here:

https://github.com/mozilla/normandy/blob/master/.circleci/config.yml#L259-L260

So you could for example use [this command](https://docs.djangoproject.com/en/3.0/ref/django-admin/#createsuperuser) to create a user with a known email that you use in your tests.
