### ISSUE TITLE
Simplify JS infrastructure

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#2149]
It used to be that we actively developed Normandy action code in this repo (in JS), and we had a React front end. Because of those we built up decent amount of JS tooling, including tests, linting, and dependencies.

These things are mostly slowly us down at this point. No one is changing the code, so the tests don't matter. No one is working on the code, so the linters are just getting in the way. Every extra dependency is one more that we keep up to date and watch for security problems.

We can't completely remove the JS from this repository, for two reasons. First, we current use NPM to fetch action schemas that are published out of mozilla-central. Second, we still have to serve the built action files for legacy clients that rely on server-hosted actions, at least partially. As of now this is still a decent sized population. Importantly, removing these actions from the repo would severely impact the range of Firefox versions that Normandy is compatible with.

We can do some things though. I propose that we

* Remove the JS tests, and all tooling for them
* Remove the JS linting, and all related tooling
* Remove any unneeded NPM packages
* Remove any usage of Babel. We can write our code to work on the target browsers

**Comment by jaredlockhart** [comment]
On the one hand I see your point, on the other hand it feels weird to have JS in here that we're stripping away any kind of validation from.  I guess we just make a rule that we can't modify the JS in this repo?  Is there some way to lock those files in git?

**Comment by mythmon** [comment]
I don't think there is any way to lock a file in git. We could add a CI check that these files don't change or something, but I don't think it's really worth it. The last real work anyone did on these files was nearly two years ago, and that was only to deprecate the old admin UI. We just never touch this stuff.
