### ISSUE TITLE
Store SSL keys for local development inside docker container

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2150]
Rather than writing the SSL keys back out to the host filesystem (which can cause file permission collisions when we run the tests in circle) we can just store them inside a docker volume.

**Comment by mythmon** [comment]
Keep in mind that most of us don't use docker for local development. This will need to stay compatible with that workflow as well.

**Comment by jaredlockhart** [comment]
Yeah I think teh entire config will live in the docker compose file so it shoudln't interrupt any non docker workflows
