### ISSUE TITLE
Update to Python 3.8

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#2157]
The bots keep bugging us about updating, and there are some nice things in 3.8 we could take advantage of (like the `:=` operator). This isn't something that one of the CI bots can take care of though, since we have a bunch of different places where we specify the image. We'll have to do it by hand and be sure to get all the things updated.

**Comment by Nikhil1O1** [comment]
is this one still open, If yes I would like to make the updates
@mythmon

**Comment by mythmon** [comment]
Sorry, @Nikhil1O1, we recently upgraded to Python 3.9, so this isn't needed anymore.
