### ISSUE TITLE
Should we remove the comment field

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#2189]
We have a comment field on the recipe revisions, largely to retain the comments from when we were using reversion. I don't believe there was any information we care about in there and we have no UI in current tooling for it. We've never really found a good use for the comment field and it's causing some issues with submissions from NDT so I would like to suggest that we remove it altogether?

**Comment by mythmon** [comment]
I don't think that the comment field was used for reversion. We should start using it in NDT as a commit message, so that we can make a more robust review process.
