### ISSUE TITLE
Filter V3 Recipe API by Experimenter Slug 

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2205]
In support of further automation integration [here](https://github.com/mozilla/experimenter/issues/2562), we could add the ability to filter the Normandy V3 Recipe API by Experimenter Slug so that we could look up all the recipes associated with that slug and automatically capture their IDs in the Experimenter database.

**Comment by rehandalal** [comment]
I just tried appending: `?experimenter_slug=<slug>` to the endpoint and it works already

**Comment by rehandalal** [comment]
🤦🏽‍♂️ i made an oopsie. reopening and assigning to myself

**Comment by rehandalal** [comment]
nvm i was right the first time... last time i touch this, i promise!

https://github.com/mozilla/normandy/blob/master/normandy/recipes/api/v3/views.py#L53
