### ISSUE TITLE
Set default pref experiment isHighPopulation pref to boolean false?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/normandy#2234]
Randomly spotted while browsing https://normandy.cdn.mozilla.net/api/v3/recipe/?enabled=1

https://github.com/mozilla/normandy/blob/d30097f65413e578f9dd24e7679c21b3e3f5491e/client/actions/preference-experiment/package.json#L47-L51

Not sure if it's an issue or not, but noticed that the boolean behavior on `isHighPopulation="false"` is different than `isEnrollmentPaused=false`

```js
                "isHighPopulation": {
                    "description": "Marks the preference experiment as a high population experiment, that should be excluded from certain types of telemetry",
                    "type": "boolean",
                    "default": "false"
                },
                "isEnrollmentPaused": {
                    "description": "If true, new users will not be enrolled in the study.",
                    "type": "boolean",
                    "default": false
                },
```

**Comment by mythmon** [comment]
Good catch, Ihad to look at this for a while to see what you meant.

The schemas aren't defined as a part of this repo though, they are currently defined in mozilla-central and pulled into this repo via NPM. We'd need to file this on Firefox::Normandy Client to actually make progress.

However, nothing actually uses the default value in these schemas, so it isn't a big deal. Also given that we are working on revamping the handling of schemas in Nimbus, I'd like to wait a bit before making any changes.

Feel free to re-file this on Bugzilla, but I don't think you need to.
