### ISSUE TITLE
Remove newrelic dependency

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#2292]
In a similar vein to #2291, we have a dependency on the `newrelic` package which was originally used to monitor and scale Normandy. It was never active by default, and required activation in deployment by changing the application launch command. To my knowledge we don't use New Relic anymore, and either way I haven't used it in a long time. We should remove that dependency.

@sciurus Does that sound right?

**Comment by sciurus** [comment]
Yep! I'm in favor of removing it.
