### ISSUE TITLE
Validate localstorage in self-repair runner

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#279]
The self-repair runner should validate that local storage is reliable, and values stored there actually persist. This is to avoid a problem where storage is not actually resilient for some users (some privacy-focused addons cause this).

One way to do this would be to store a counter in localstorage that increments every time the runner starts. Any actions that rely on reading data from localstorage should check this counter and make sure it is at least 2 before proceeding.

We probably shouldn't count past 2 here, actually. Values over 2 won't really help us. But we do need more information than a simple boolean, since we need to check that the values persists at least two runs (the first run sets the value, and in the second run the value is persisted).

**Comment by Osmose** [comment]
Should we also update actions that use the storage and have them abort execution early if storage isn't available?

**Comment by mythmon** [comment]
We could do this by making any promises for the storage driver fail if storage isn't available. That should make any actions abort early. We should test this to be sure though.

**Comment by Osmose** [comment]
This was resolved by #313.
