### ISSUE TITLE
in telemetry, unable to distinguish survey variants on the same recipe

### ISSUE THREAD

**Issue by gregglind** [mozilla/normandy#297]
## Currently:
- Unified Telemetry packets for recipes use the Survey Id and Survey Version fields *as is*

is a problem because:
- this makes success (uptake/usage) by variant impossible to distinguish

## Some Solutions
1.  **FIX UITour** to report a 3rd field.
2. **Change Messaging Recipe** to somehow glob the variation into one of those fields, either replacing version (meh) or globbing onto id (meh).  If I were **forced to pick**, I would say surveyId should be `${surveyId}:${variation}`.
3.  **Implement Bucketed Sampling** with guaranteed non-overlapping samples.  See @Osmose  for details.  In this system, each recipe only has 1 survey, period.
4.  **Make Analysts Hope and Pray** by doing 2 different recipes, and hope the sampling overlap isn't too much.

**Comment by mythmon** [comment]
From a development point of view, I think 1 isn't going to happen on a timescale that helps us, and 4 is just mean. I'd be fine with 2 for now. It sounds like 3 is the long term solution, but I'm not sure how close we are to that yet.

I like the idea of doing `${surveyId}:${variation}` in the short term, if that works well for you.

**Comment by gregglind** [comment]
I am even fine with double colon :)  Something that is obvious that 'if it's there, then it means something'.  Hyphen would ungood.  I am liking double colon.

**Comment by mythmon** [comment]
*Double* colon? Both our messages have single colon, though maybe double helps make it more obvious.

**Comment by Osmose** [comment]
Option 3 is farthest along and probably the best solution. I have a branch that implements single-survey-recipes, and bucket sampling. It needs just a few tweaks and can be ready before any of the other proposed solutions.

I'll take this and work on getting that PR ready soon.

**Comment by gregglind** [comment]
(double colon is for the SERIOUSLY, THIS IS REALLY NOT AN ACCIDENT prevention.  BELT AND SUSPENDERS AND BEAR SPRAY)
