### ISSUE TITLE
Show survey ID on recipe listing for show-heartbeat recipes

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#303]
(This issue is intended for Andy to work on as his first bug, do not take this!)

The survey ID on show-heartbeat recipes is a useful piece of information that S&I wants to be able to see on the index listing page. However, since it only applies to show-heartbeat recipes, we probably should come up with a more generic solution for showing details about a recipe based on the action.

Here's a mockup I came up with for one possibility of how to display this:

<img width="970" alt="screen shot 2016-10-21 at 10 00 00 am" src="https://cloud.githubusercontent.com/assets/193106/19606839/72073688-977a-11e6-8fe1-f91c0585dcae.png">

This isn't exactly how it should look; we should probably remove the bullets on the list. But it's a starting point.

If possible, we should also make the survey ID searchable in the search box, and more generically, any value in the details column.

**Comment by andymikulski** [comment]
merged in #314
