### ISSUE TITLE
Annotate postAnswerURL with GA parameters

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#304]
S&I wants the query arguments that are added to the show-heartbeat postAnswerUrl to include Google Analytics-compatible query arguments.

@mattgrimes can you comment on what exact params you want and what you want their values to be?

**Comment by MattGrimes** [comment]
Params
utm_source=firefox
utm_medium=heartbeat (or whatever the action name is - recommendation, shield study, etc)
utm_campaign=shortenedmesssagetext (just a shortened version of whatever is in the message field. It does need to be unique so we can tell them apart.)

Example link https://www.mozilla.org/firefox/new/?utm_source=firefox&utm_medium=heartbeat&utm_campaign=shortenedmesssagetext

That work?

**Comment by Osmose** [comment]
Yep. We can probably URL-ify or slug-ify the message text somehow to make it work in the URL.

**Comment by MattGrimes** [comment]
Solid. Thanks!

**Comment by andymikulski** [comment]
For url-ifying the message text, should we impose a length limit? Currently, I remove whitespace from message and then pass it through `encodeURIComponent`, to give something like this:

```
utm_source=firefox
utm_medium=show-heartbeat
utm_campaign=Thisisamessage%21Woo%21
```

(where the `%21`s are url-safe `!`s). Does this formatting look acceptable?

**Comment by Osmose** [comment]
I don't think we should impost a limit, since we can't guarantee the variation between two different surveys isn't at the end of the message.

**Comment by andymikulski** [comment]
Good point! In that case, this is ready for review in #343

**Comment by rayborn** [comment]
Contemplating opening another issue to not override existing params.  We're manually setting UTM params in some of our URLs.

Thoughts?

**Comment by Osmose** [comment]
> Contemplating opening another issue to not override existing params. We're manually setting UTM params in some of our URLs.
> 
> Thoughts?

Yep, that's the thing to do!

**Comment by rayborn** [comment]
Cool, will open (I don't think that we're doing this now because just after this push my UTM params appeared to change for the mobile promo links, have not read the code)
