### ISSUE TITLE
Add configuration for domain in classify endpoint

### ISSUE THREAD

**Issue by relud** [mozilla/normandy#307]
required to serve site through akamai cdn, so that classify hits normandy directly via a url other than self-repair.mozilla.org in prod (such as normandy.services.mozilla.com)

**Comment by Osmose** [comment]
@relud So the self-repair page currently hits `/api/v1/classify_client/` as part of executing recipes, and you want the domain for that request to be configurable by a Django setting. Does that sound correct?

We can probably add a setting named `APP_SERVER_DOMAIN` or something to reflect that it's the domain for the non-CDN server. How does that sound?

**Comment by relud** [comment]
> @relud So the self-repair page currently hits `/api/v1/classify_client/` as part of executing recipes, and you want the domain for that request to be configurable by a Django setting. Does that sound correct?

yes

> We can probably add a setting named `APP_SERVER_DOMAIN` or something to reflect that it's the domain for the non-CDN server. How does that sound?

awesome
