### ISSUE TITLE
Tie SurveyGizmo Answers to Telemetry Data

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#309]
With regards to Lead Users, the goal is to send out surveys that we think can identify Lead Users, and then analyze the Telemetry profiles of those users to identify patterns from Telemetry data that we think are good indicators of Lead Users (hardware? customizations?).

Legal bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1313453

## Spec
Add a new boolean argument to the `show-heartbeat` action that is displayed in the admin as a checkbox with the label "Include unique user ID in post-answer-url and Telemetry". When checked, the action should append the unique UUID we generate on the client to the `surveyId` that gets logged in telemetry, separated with a double-colon (`::`). It should also alter the query parameters passed to in the `postAnswerUrl` argument to include the unique UUID.

The UUID in question should be the one we include in filter expressions under `normandy.userId`.

**Comment by Osmose** [comment]
@gregglind @mattgrimes The spec above has us modifying the `surveyId` that ends up in telemetry, are ya'll okay with this change? It lines up with what you suggested in the legal bug.

Are we just waiting for the legal bug to be resolved (and your approval) before working on this?

**Comment by Osmose** [comment]
Confirmed via IRC that the spec above is fine. This is now waiting on the linked legal bug to be approved.

**Comment by gregglind** [comment]
I approve of this.  How it will be handled:

- if the analysis code is naive, then different VARIATIONS will look like different SURVEYS.  This is fine.
-  if the analysis code is smart, it will KNOW to split on `::`.  
- analysts will be SMART and not use `::` as part of a surveyId.

- [ ] confirm that uu / query args handle colon fine.

**Comment by Osmose** [comment]
We've gotten the go-ahead for implementing this by legal. We should double-check with them before deploying it, though. Probably not in this week's release.

**Comment by mythmon** [comment]
Fixed by #315
