### ISSUE TITLE
Opt-Out Study Action

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#323]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1337528

Opt-out studies are SHIELD studies that are automatically run on a small sample of users. Opt-out studies are only for low-risk studies that have gone through a thorough approval and review process.

[Current Specification](https://docs.google.com/document/d/1ZxZCMKl56LBkIvOHJ9pPDaDLtoRwtNLL1NALKPj5LTo/edit#)

<details>
<summary>Old Spec</summary>
[See the spec document](https://docs.google.com/document/d/1t3vMC9fdLQApmuiR9BPAi05RjS0VVjcsFH3uEcbgNGc/edit)

We will add a new `opt-out-study` action. Upon running, the action will:

1. Check if the current user has Unified Telemetry disabled, and if so, abort execution.
2. Check if the current user is in the opt-out sample, and abort execution if they aren't.
3. Check if the user has already participated in the study or is currently participating, and abort execution if they already have received the study add-on.
3. Install the study add-on.

The action should take one argument:

- A file upload input for admins to upload the add-on to install.

Uploaded add-ons will already be signed. It'd be nice (but not required) to validate that uploaded add-ons are signed properly.

We also want users to be able to opt-out of studies, both opt-out and opt-in. To increase transparency, we should add a new page (`about:shield`, maybe?) that lists all experiments that are active and that the user participated in in the past. From this page, users should be able to disable any active experiments, and opt-out of experiments completely.

## Open questions

- What should `about:shield` look like, and is `about:shield` the name we want?
  - Will the add-on itself have all the metadata necessary for displaying it?
  - How will we track which add-ons are studies and which ones aren't? 
- Will we need any extra technical approval measures for releasing opt-out studies?
</details>

**Comment by gregglind** [comment]
Awesome.  Keep me in the loop.

**Comment by Osmose** [comment]
Code for observing when about:addons shows up: https://gist.github.com/rhelmer/f3db0702974ef47bdb63ecb691ab0d30

**Comment by MattGrimes** [comment]
@sevaan @Osmose 

Had a good meeting with legal/policy today. Here are some answers to outstanding questions

- They would prefer the opt-out box is on the same page as other data settings. It can be a sub-check box under the basic telemetry box. Unchecking this box does not uncheck basic telemetry.

- The learn more link should go to SUMO. I can work with the SUMO team to get some documentation together.

- I need to file a legal bug to update the usage statistics section of the browser privacy notice. 

- The Shield Experiments tab does not need to be visible unless the user is eligible for AND have been picked for an experiment. Old experiments are greyed out and should remain visible to users so they can see if they have ever been a part of an experiment.

I think those were all of the outstanding questions. Let me know if I missed something.

**Comment by sevaan** [comment]
Sounds good to me. Here is the option with the opt-out on the page: https://mozilla.invisionapp.com/share/UC9XM7O9X#/213265161_Experiments_Tab_-_Opt-Out

**Comment by sevaan** [comment]
Not sure what issue to post this on, of is this is it, but here is the asset for the icon in the about:addons navigation: http://i.sevaan.com/312V0Y1v040L

**Comment by MattGrimes** [comment]
Sorry, I wasn't clear enough. They prefer to have the opt out in the advanced->data settings menu as seen here: http://i.sevaan.com/0k461h1h0c1r

**Comment by sevaan** [comment]
My bad. Here's the version that supports that: https://mozilla.invisionapp.com/share/UC9XM7O9X#/212795383_Experiments_Tab

**Comment by Osmose** [comment]
Here's the spec from #411 after addressing feedback: https://docs.google.com/a/mozilla.com/document/d/1t3vMC9fdLQApmuiR9BPAi05RjS0VVjcsFH3uEcbgNGc/edit?usp=sharing

**Comment by Osmose** [comment]
The spec is a bit out-of-date compared to how we'll implement opt-out studies. I'll update this bug with a new spec when it is prepared.

**Comment by Osmose** [comment]
[Here's the most up-to-date spec for opt-out studies](https://docs.google.com/document/d/1ZxZCMKl56LBkIvOHJ9pPDaDLtoRwtNLL1NALKPj5LTo/edit#).

I've filed a bunch of new issues under the `project: native-studies" tag, which constitute all the remaining work for implementing opt-out studies. Given that, I'm going to close this bug in favor of the tag for tracking development work.
