### ISSUE TITLE
Global Shutoff Valve

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#324]
In the past, self-repair has had a few issues where a recipe config or bug caused a recipe to behave wrongly at a time when none of the people able to change recipes were online. For example, the issue of localStorage being disabled by privacy add-ons + a recipe sent to 100% of Australian users caused surveys to reappear every launch for many users.

To address this, we'd like to add a shutoff valve for recipes that temporarily disables all recipes being sent out to users. This switch will be made available to the MOC, who have IT staff on shift around the clock who can respond to reports of widespread issues with recipes. The MOC can flip the switch when issues arise, and once admins or devs come online, they can resolve the issue and re-enable recipe delivery.

## Spec
The shutoff valve should be a flag that controls _all_ recipes being sent out, independent of their Enabled/Disabled status. If the shutoff valve is on, the recipe API should respond as if there are no enabled recipes. Switching the flag on or off should not modify recipes themselves, only their delivery.

The control interface will need a form for turning the shutoff valve off and on. Turning it on should require a comment explaining why user is disabling recipe deliver (preferably with a related bug number or something). 

We'll probably want a new Django permission to grant access to the shutoff valve. 

## Open Questions
- How will the MOC maintain a list of accounts that can access the shutoff valve?
- Where do we put navigation in the site design to link to the shutoff valve?
- What are the criteria for the MOC to identify a reported issue as being related to Normandy?
  - rob an come up with numbers of complaints that matter
  - Point to doc page of actions
  - list of experiments / recipes internal visible

**Comment by mythmon** [comment]
Normandy has been running for a while without any issue, and this isn't an issue that we have run into so far. Considering that we have a lot of disparate recipes now, and disabling recipes tends to interrupt data collection in irreparable ways, I think that a mass-disable would likely cause more damage than simply disabling individual recipes.

Because of all this, I'm going to close this as WONTFIX, but I'm open to revisiting the issue in the future.
