### ISSUE TITLE
Client-side Error Reporting

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#326]
We currently have no way of reporting client-side errors that occur when executing actions in the add-on. We need to be able to know when we hit errors in the client so that we can fix them. This includes both errors in the actions themselves, and errors in the add-on.

To a lesser extent, it'd also be very nice to get error reports when the admin interface malfunctions.

There's not really a spec here; anything we can do to get better visibility into these kinds of failures is useful.

**Comment by andymikulski** [comment]
Do we have any libraries or third-parties tools in mind for this? Most I know of require a subscription or something - does Moz have licenses for anything already?

**Comment by mythmon** [comment]
One issue with third party tools is that they tend not to work in the context of Firefox chrome code (internal browser code), so we probably can't use something off the shelf for the add-on.

The admin, on the other hand, is just normal webcode. We already have access to Sentry, and we can hook that up to the admin. That should be a different issue though.

**Comment by lonnen** [comment]
Sentry is ok for the service. Client code requires some thinking through --  see [JS exceptions](https://wiki.mozilla.org/Firefox/Data_Collection#Common_Problems) in the wiki under data. When someone is ready to work on this, I'm happy to help work through the concerns and find the right data steward.

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435881
