### ISSUE TITLE
Filter expression testing against user archetypes

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#328]
To help test filters, we'd like to add a way to specify user archetypes, and a way to test a filter against those archetypes.

The idea is to be able to describe a user in terms of the properties in simple filters (#316). So, for example, we could register an archetype for a US-based release user:

- Locale: `en-US`
- Country: `US`
- Channel: `Release`

Then, on the recipe edit page, we can have a control for viewing the archetypes that the given filter config will hit, and admins can see a list of common archetypes that the filter passes for. Archetype testing will _not_ (at least initially) cover more customized filtering, like telemetry or preference filtering. We may add that in a future revision, but for now we're keeping it basic.

**Comment by mythmon** [comment]
I'm going to close this as wontfix. The feature described can't test many types of user archetypes we would want to test (such as new users, or profile age testing in general), and we have other ideas for getting this kind of data experimentally (see #350)
