### ISSUE TITLE
Verify telemetry numbers for heartbeat

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#334]
We currently have multiple sources of info for how users interact with the Heartbeat prompt, including Input, Telemetry, and GA. We plan to depend primarily on Telemetry in the future, and we'd like to run a test to ensure that Telemetry data about Heartbeat interactions is being sent correctly.

**Comment by Osmose** [comment]
One possible way of doing this is to run the test repeatedly and verify over time:

- Create a test heartbeat recipe on prod that checks for a nonsense test locale.
- Create a test using Marionette/Selenium that sets the user's locale to the test locale, waits for the Heartbeat prompt, and then interacts with it. The test could either do this a consistent amount of times, or perhaps a random amount of times, and log the amount of times it ran somewhere.
- Create a daily spark job that pulls Heartbeat data for the fake survey, and asserts that the response data matches with the test job's interactions. If it fails, notify the team of the mismatch. 

This might be overkill. The repeating job model is intended to verify over time that changes we make aren't affecting our telemetry activity reporting, but we might only care about verifying Telemetry once.

@mythmon @gregglind Thoughts?

**Comment by MattGrimes** [comment]
I'd like to also add GA links to the post answer urls. We can see if GA actually is tracking every impression as they claim.

**Comment by mythmon** [comment]
We never tested this experimentally, but at this point I think a year's worth of data has proven our data pipeline fairly reliable.

Closing this as WONTFIX.
