### ISSUE TITLE
Dashboards of Telemetry analysis

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#338]
We'd like to add a basic dashboard for `show-heartbeat` recipes that displays the following metrics from Telemetry:

- Total count of users who have seen the prompt
- Total count of users who have voted / engaged with the prompt
- Conversion rate (seen vs engaged)
- Distribution of star rating votes

The dashboard should allow admins to select a date range over which the results should be computed.

**Comment by Osmose** [comment]
Currently waiting on @rayborn to put up a spark job that outputs these numbers. After that we'll prototype the graphs we want and get feedback on them.

**Comment by mythmon** [comment]
We aren't currently planning to show this kind of data in the Normandy admin.
