### ISSUE TITLE
Counting recipe executions

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#339]
To help monitor recipes, we'd like to start counting actual recipe executions on clients, and make that information available somewhere in the control interface. Perhaps on the same dashboard as #338, under a "Debugging" category?

**Comment by mythmon** [comment]
This is handled by a combination of uptake and enrollment telemetry, but we don't expose this data within Normandy's admin interface. I think that exposing this data is well handled by other tools, such as Test Tube and Experiments Viewer.
