### ISSUE TITLE
Long-lived sessions cannot update recipes

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#345]
@MattGrimes reported that he couldn't submit the recipe form on multiple occasions, and he confirmed that he keeps the admin interface open in a tab for days at a time. I suspect his session is timing out.

I talked with @mythmon about this, and he recommended just having the client refresh its session periodically so that, to the user, it appears that their session never times out.

**Comment by MattGrimes** [comment]
That would be awesome. I am addicted to pin tabs and never close Firefox. It's all my fault.

**Comment by mythmon** [comment]
With auth0 the symptoms of this are slightly different. Now we get  CSP errors, since the API requests redirect to Auth0, which is a domain not allowed by our CSP.
