### ISSUE TITLE
Client-side login page

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#346]
Currently, the login page for the control interface lives outside of the client-side control app. We should instead make APIs to support authenticating and implement the login in the client. From a user's perspective it should otherwise function identically to how it does now.

**Comment by mythmon** [comment]
Since we have Auth0, this isn't a concern anymore. The authentication APIs don't exist, but they wouldn't be a part of of Normandy anyways nowadays.

Closing this as WONTFIX.
