### ISSUE TITLE
Only display one `show-heartbeat` prompt a day

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#348]
`show-heartbeat` recipes should store and check a date when they display, and if a `show-heartbeat` recipe has executed and displayed a prompt to the user within the past 24 hours, other `show-heartbeat` recipes should not prompt the user.

This should be separate from checking if the prompt has been shown recently, so that if a user gets 2 recipes, that 1 of them will show one day, and then the next day it will see that it has shown recently and not run, allowing the second recipe to show instead.

**Comment by andymikulski** [comment]
Plan for this is to use a least-recently-used map ([link](https://github.com/rsms/js-lru)) that tracks when heartbeats were last run. In theory, we can use this to pull the ID of the heartbeat that should run next, and store the state in localStorage.

**Comment by Osmose** [comment]
> Plan for this is to use a least-recently-used map (link) that tracks when heartbeats were last run. In theory, we can use this to pull the ID of the heartbeat that should run next, and store the state in localStorage.

Huh, why do you need to store the heartbeats locally? The intent was to have show-heartbeat just abort early if they can't run (if another show-heartbeat has run recently). It's not important that we log that heartbeat and show it later; if a heartbeat action fails on Monday due to collision, and isn't being sent out on Tuesday, then the user in question just shouldn't see it. No need to guarantee display.

**Comment by andymikulski** [comment]
Ah, I see. My misunderstanding, thanks for clarifying @Osmose !
