### ISSUE TITLE
Ability to test filter expressions on users

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#350]
@MattGrimes and I came up with an idea for testing filter expressions by running them locally against users (like we do with live recipes) without actually sending a recipe to users. We could log the number of users who pass a filter to get a sense of how a filter will perform in the real world.

We'd likely have an interface for registering filters and setting the period over which to test it. On the client we can store which test filters have been evaluated to avoid double-counting, and expire that data after the test period is over locally to avoid storing a bunch of data locally that doesn't benefit the user.

@gregglind @ilanasegall @rjweiss What do ya'll think?

**Comment by mythmon** [comment]
I've talked with everyone tagged on this issue in person. This is a very popular idea, and something we should definitely do.

As far as how we store and report this data: I think storing a flag for which test recipes the user is in, and sending enrollment and unenrollment telemetry events would be a good way to deal with it.

**Comment by mythmon** [comment]
Filed [bug 1435885](https://bugzilla.mozilla.org/show_bug.cgi?id=1435885) for the client side parts of this.
