### ISSUE TITLE
Preferences in filter expressions

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#351]
There's interest in being able to target recipes by preference values. The syntax of this would probably look something like:

```js
normandy.prefs['xpinstall.signatures.required'] == false
```

@mythmon Thoughts on the syntax?

@MattGrimes What are the use cases here? I suspect we'll need privacy approval?

**Comment by mythmon** [comment]
The telemetry key `environment.settings.userPrefs` has some preferences. I think this is the prefs that a user has explicitly changes. We have access to this in filter-expressions as `telemetry.main.environment.settings.userPrefs["app.update.auto"]`. For me, that data is

```
{
  "app.update.auto": false,
  "app.update.enabled": false,
  "browser.cache.disk.capacity": 358400,
  "browser.newtabpage.enhanced": false,
  "browser.startup.page": 3,
  "browser.urlbar.suggest.searches": true,
  "browser.urlbar.userMadeSearchSuggestionsChoice": true,
  "devtools.chrome.enabled": true,
  "devtools.debugger.remote-enabled": true,
  "dom.ipc.processCount": 3,
  "layers.acceleration.disabled": true,
  "layout.css.devPixelsPerPx": "1.5",
  "privacy.donottrackheader.enabled": true,
  "xpinstall.signatures.required": false
}
```

**Comment by Osmose** [comment]
Here's my proposal for the syntax:

```js
// Compare the value of the preference, i.e. Preferences.get
'browser.startup.page'|preferenceValue == 3

// preferenceValue can take a default value as an optional argument, which 
// defaults to `undefined`.
'devtools.chrome.enabled'|preferenceValue(false) == true

// Compare if the preference is user set, i.e. Preferences.isSet
'dom.ipc.processCount'|preferenceIsUserSet != true

// Compare if the preference has _any_ value, whether it's user-set or default, 
// i.e. Preferences.has
'xpinstall.signatures.required'|preferenceExists == false
```

@andymikulski @mythmon @gregglind @MattGrimes @rayborn Last call for feedback on the syntax?

**Comment by gregglind** [comment]
On first blush this looks good. 

1.  prefNames are strings, so all good
2. pref values are null|int|bool|string, and I think this handles all those cases
3. this mirrors some aspects of the pref systems:  defaultness, isSet, exists.

I think that talking about 'defaultPrefBranch', and 'userPrefBranch' or that mess is too complex for user code to see anyway, but I could be wrong?

F+ unless I am missing things!

**Comment by Osmose** [comment]
Thanks @gregglind! Calling this ready, then.
