### ISSUE TITLE
Move normandy-addon into the normandy repo

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#353]
We'd like to mirror what [TestPilot](https://github.com/mozilla/testpilot/) does and keep the add-on code and service code in the same repo. This has a few benefits:

- Ability to share common things, like linting configs.
- Changes to how the service and add-on interact with each other can happen in a single commit/PR.
- Most of the work our team does can be filed as issues on a single repo, which lets us take advantage of milestones and tagging for managing work.

There's some open questions that need to be addressed as part of this issue:

- Should we do anything smart to avoid building and running the add-on or site for changes that only occur in one of the two codebases?
- How should we organize the repo? TestPilot simply has an extra directory at the root of the repo storing the add-on, but some of our long-term plans involve writing a client library for things using SHIELD, which may end up in the monorepo as well.

We might want to wait until the add-on gets merged to mozilla-central before doing this, but nothing is really blocking it.

**Comment by mythmon** [comment]
One issue is that the add-on will require a specific set of lint configs, to match with mozilla-central policies. Good editors can make this pretty painless. We can easily do this by having common configs in `./.eslintrc` (that, the root of the repo), and an add-on specific version in `./addon/.eslintrc`.

[Here is a tool](https://syslog.ravelin.com/multi-to-mono-repository-c81d004df3ce) that someone else used to convert many repos into a monorepo. It seems helpful if want to preserve git history.

**Comment by Osmose** [comment]
Resolved in https://github.com/mozilla/normandy/commit/06634ed70c9ed8d7df26111d4da064f07ffe63c9.
