### ISSUE TITLE
Modify dependency on telemetry preferences

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#354]
There is a subset of actions that we want to abort early because they rely on unified telemetry, but some actions (like the 43 update notice) we want users to see even if they don't have telemetry enabled. So, instead of disabling the add-on, specific actions should disable themselves.

**Blocked by**: 
- [x] #353

**Comment by Osmose** [comment]
After discussing things with @georgf, I think we need to change what telemetry preferences we're checking, and when. 

Currently:

- On startup, we check `toolkit.telemetry.unified`. If it is true, we continue. If it is false, we do not execute any recipes for the rest of the session.

Based on my conversation with @georgf, `datareporting.healthreport.uploadEnabled` is the correct pref to represent that Telemetry is available. I'd like to change our checks to:

- Always register the recipe run timer.
- On each attempt to run, check `datareporting.healthreport.uploadEnabled`. If it is true, continue. If it is false, do not download or execute recipes.

@MattGrimes Heartbeat recipes currently use Telemetry to track user interaction with the prompt. Do we want to still run those recipes even if Telemetry is disabled? I think the answer is yes, since users may still fill out a survey or otherwise benefit from the prompt, but want to confirm.

**Comment by MattGrimes** [comment]
I say yes. Surveys are by nature opt-in. The user can always choose not to answer.

**Comment by mythmon** [comment]
This will be fixed by #1094.

**Comment by mythmon** [comment]
We'll need to revisit this more holistically when we implement system add-ons. I'm going to close this and we can deal with this issue more in depth in other issues.
