### ISSUE TITLE
Recipe listing pagination

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#358]
Prod has enough recipes that we should consider adding pagination to the recipe listing page.

I don't have any particular requirements for what kind of pagination we want, but [this article](https://uxplanet.org/pagination-best-practices-76fbd3f5a78d#.9420551oj) has pretty good guidelines, and [Github's pagination](https://github.com/search?utf8=%E2%9C%93&q=test) looks pretty nice; something that functions like that would work well.

@rehandalal has opinions on the API side of pagination, I believe.

**Comment by andymikulski** [comment]
This is fixed in the new UI which landed in #955
