### ISSUE TITLE
Simplified Filters - Front End Tasks

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#363]
Tracking front end tasks for #316 here

- [x] Columns dropdown menu
- [x] Customize show/hiding columns
- [x] Column layout should be stored locally
- [ ] Combo box (text search)
* - [x] ...filters group dropdown
* - [ ] ...adds a text filter upon hitting enter
- [x] Combo box (dropdown selection for filters)
- [x] Active filters section...
* - [x] ...lists filter state
* - [x] ...clicking removes filter
* - [x] ...actually filters list
* - [x] ...has reset filters button
- [x] Last filter view is saved locally (refreshing does not wipe filters)
- [ ] Recipe page Filters section (Searchable multiselect boxes, etc)
- [ ] Connect stores to API
- [ ] Tests

Nice to haves:
- [ ] Formatted/displayed text to match raw API values (e.g. `de` displays as `German (de)`)
- [ ] Keyboard accessibility

**Comment by andymikulski** [comment]
Attaching wireframes here for easier reference

![shield simple filters final-1](https://cloud.githubusercontent.com/assets/2767162/20534787/bdc6b056-b09f-11e6-96dd-9a8a69b866e3.jpg)

![shield simple filters final-2](https://cloud.githubusercontent.com/assets/2767162/20534792/c082dc48-b09f-11e6-9409-f7d94a5272c6.jpg)

![shield simple filters final-3](https://cloud.githubusercontent.com/assets/2767162/20534794/c21277bc-b09f-11e6-97a0-dc69e525156b.jpg)

![shield simple filters final-4](https://cloud.githubusercontent.com/assets/2767162/20534798/c3d1f460-b09f-11e6-8051-27290a3235c8.jpg)

![shield simple filters final-5](https://cloud.githubusercontent.com/assets/2767162/20534799/c5419f80-b09f-11e6-8f04-6494ddd8d641.jpg)

![shield simple filters final-6](https://cloud.githubusercontent.com/assets/2767162/20534802/c6abccba-b09f-11e6-9e34-c9fa6bac3645.jpg)

**Comment by andymikulski** [comment]
hey @Osmose @mythmon regarding the [search/filter combo box](https://cloud.githubusercontent.com/assets/2767162/20534798/c3d1f460-b09f-11e6-8051-27290a3235c8.jpg), if the user types into the text input, does that filter the dropdown menu? Or is it strictly for filtering rows via text search?

**Comment by Osmose** [comment]
> hey @Osmose @mythmon regarding the search/filter combo box, if the user types into the text input, does that filter the dropdown menu? Or is it strictly for filtering rows via text search?

It should filter the dropdown, unless the user hits enter, at which point it should apply a text filter. Or, rather, it should do whatever New Relic's filter dropdown does, because that's what I based it on.

**Comment by andymikulski** [comment]
@Osmose @mythmon Do we want filters to be exact matches? For instance, here the `German` filter is applied, but recipes are filtered out if _any_ of the locale values are `de`. Do we want it so that if a filter is applied, only recipes with that exact match are shown?

![screen shot 2016-11-30 at 8 55 07 am](https://cloud.githubusercontent.com/assets/2767162/20759565/77a0184c-b6da-11e6-916f-661f85e95536.png)

**Comment by Osmose** [comment]
> For instance, here the German filter is applied, but recipes are filtered out if any of the locale values are de.

Do you mean that they're only included if any of the locales are German, rather than filtered out?

My expectation is that the locale filter shows only recipes that include the locale being filtered by, and excludes recipes that don't include the locale at all. I think I'm also implicitly expecting that there can be only one locale filter active at a time, but I didn't specific state that anyway. I _think_ that makes the most sense, but maybe not?

**Comment by andymikulski** [comment]
>Do you mean that they're only included if any of the locales are German, rather than filtered out?

Yes, sorry!

>I think I'm also implicitly expecting that there can be only one locale filter active at a time,

Oh! Well, the code is set up to allow for multiple filters for certain properties. For instance, you can filter by multiple locales or releases, but things like 'status' and 'action name' can only have one selection:

![multi-filter example](https://cloud.githubusercontent.com/assets/2767162/20763551/bdfb6a3c-b6e7-11e6-8194-96b69e7fdd32.gif)

(pardon the lack of styling)

This can be altered as to how it works right now, not hard at all to only allow one per filter.

**Comment by Osmose** [comment]
That's actually probably great. Looks nice!

**Comment by andymikulski** [comment]
Closing this in favor of #395 and #396
