### ISSUE TITLE
v26 tests failing

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#375]
https://bugzilla.mozilla.org/show_bug.cgi?id=1321409

I've hunted down the origin of the `ERROR RUNNING RECIPE: TYPEERROR: N IS UNDEFINED` message, but there still exists a deeper issue.

The initial fix is to correct how the param destructuring/default assignment works in `LocalStorage#constructor` - 

```
  constructor(prefix, opts) {
    // build an options object, even if
    // no options have been passed in
    const options = { ...opts };

    this.prefix = prefix;
    this.skipDurability = options.skipDurability || false;
  }
```

The specific error is that `_ref` is undefined, which is from babel's way of handling destructuring.
Basically, `someFn({ woo })` is converted down into `someFn(_ref){ const woo = _ref.woo; ....` - which means if no object is passed into the function, an error is thrown (since `_ref` doesnt exist to extract `woo` from)

BUT with that fixed, I'm now running into a deeper issue which seems to dive into non-JS code:

![screen shot 2016-12-01 at 8 40 30 am](https://cloud.githubusercontent.com/assets/2767162/20800075/6a7ccde6-b7a1-11e6-8753-2c1aba3540ef.png)

The source map points to the `.catch`'s console.log, and the _only_ place where `normandy.saveHeartbeatFlow` exists is stubbed out in some tests. Not really sure where to go from here - @mythmon any thoughts?

**Comment by Osmose** [comment]
That screenshot looks like you still have the old action code that uses `saveHeartbeatFlow`, you might want to make sure that you're passing `--update-actions` to `npm run watch` or `npm run build`.

**Comment by andymikulski** [comment]
I'm 90% positive I was running with that flag - maybe the `VERSION` number needs to get bumped up?

**Comment by Osmose** [comment]
> I'm 90% positive I was running with that flag - maybe the VERSION number needs to get bumped up?

Nah, `VERSION` is only used with the data sent to Telemetry to differentiate between what code ended up sending which packet, and is mostly unused in that case anyway. Although I didn't bump it when I change the recipe, which wasn't a great thing  to do.

That traceback in the screenshot shows the error happening in `save`, which was a method on the `HeartbeatFlow` class that actually called `saveHeartbeatFlow`. But that class was deleted in https://github.com/mozilla/normandy/commit/6fd117f4535821733a61e2117826ff46c63ecfb9, which is what leads me to believe your built code is out-of-date.

**Comment by andymikulski** [comment]
Gotcha - maybe I was running with `--update-action` or something close to it.

I'll review the PR for this in a few minutes.
