### ISSUE TITLE
Ability to filter by operating system

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#377]
In [bug 1296028](https://bugzilla.mozilla.org/show_bug.cgi?id=1296028) we logged the common [`navigator.oscpu`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/oscpu) values our users had. Now that we have that, we should add the ability to filter recipes by OS. This covers adding this to **both** the add-on and the self-repair driver.

Some useful links:

- [The logic that actually generates the value](https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpHandler.cpp#844)
- [Example code for getting the value in a chrome context](https://dxr.mozilla.org/mozilla-central/source/devtools/shared/system.js#19)

@andymikulski This needs a spec for what the JEXL filter API will look like that S&I likes. Can you come up with one and get feedback from them on if it'll serve their needs? There's no urgent timeline on this, so don't worry about handling this until your other work is done.

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Normandy%20Client
