### ISSUE TITLE
Landing Page / Site Navigation

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#378]
Pretty soon we're going to have multiple pages outside of the recipe listing (#324, for example). We should give some thought to how we want to lay out the rest of the control interface outside of the one listing page.

**Comment by andymikulski** [comment]
This has been resolved in the new UI which landed in #955 with the introduction of the `Gateway` page:

<img width="420" alt="screen shot 2017-08-07 at 3 24 25 pm" src="https://user-images.githubusercontent.com/2767162/29042347-90fdefa2-7b84-11e7-9b28-2687eb7c1838.png">
