### ISSUE TITLE
Server-side filter expression validation

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#379]
We currently validate filter expressions for syntax on the client, but we should probably be doing server-side validation for this as well in case other clients write to the API.

I wrote [PyJEXL](https://github.com/Osmose/pyjexl) specifically for this, but we never got around to integrating it. We also wanted to add some extra validation:

- Variable validation. We probably can't get a proper schema for things like the telemetry packet, but we can validate filter context identifiers against what's [documented](http://normandy.readthedocs.io/en/latest/user/filter_expressions.html), at least.

Since this is all server validation, it should take the same form as our existing API validation and be displayed on the recipe form post-submission.

**Comment by gregglind** [comment]
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/telemetry/core.schema.json

**Comment by mythmon** [comment]
We're using pyjexl to validate filter expressions now.

```js
fetch('/api/v1/recipe/100/', {
  method: 'PATCH',
  credentials: 'include',
  headers: {'Content-Type': 'application/json', 'X-CSRFToken': 'SNIP'},
  body: JSON.stringify({extra_filter_expression:  '[invalid)'})
})
.then(res => res.json())
.then(data => console.log(JSON.stringify(data))) 

// {"extra_filter_expression":["Could not parse expression: [invalid)"]}
```
