### ISSUE TITLE
Document API with Swagger

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#389]
We have a decent amount of API endpoints, with a minimal amount of documentation around them. AFAIK the only existing documentation is at http://normandy.readthedocs.io/en/latest/dev/self-repair.html for the self-repair related APIs.

@chartjes brought up documenting our API with [Swagger](http://swagger.io/) (apparently we have some tooling that can consume this somewhere), which is a good idea. @jvehent also mentioned it during a Hawaii talk. DRF supports documenting APIs in a format-agnostic way, which can then be output in various formats, including Swagger: http://www.django-rest-framework.org/api-guide/schemas/#schemas

We should do that. While doing that, we should get rid of the self-repair docs, as they're confusing right now IMO.

**Comment by Osmose** [comment]
@rehandalal Is this what you're currently working on?

**Comment by rehandalal** [comment]
@Osmose yeah I guess this is also covered by the PR.

**Comment by mythmon** [comment]
@rehandalal What's the status of this? I see that there are swagger docs at https://normandy.cdn.mozilla.net/api/docs/. Are we done here?

**Comment by rehandalal** [comment]
Yeah I guess we have swagger docs now. Perhaps we should close and revisit if we need a better implementation of this.

**Comment by chartjes** [comment]
+1 to closing, I will take a look at them and add some tests using these definitions if I think it will help
