### ISSUE TITLE
System add-on test service

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#392]
In #391 we're creating a set of test API responses; this issue covers taking those responses and making a test service that Firefox QA can use in testing the system add-on out.

@mythmon and I talked about this at Hawaii and came up with an idea that could work: create a script that takes the pre-written test responses, signs them using the development autograph service, and upload the signed contents to S3. If we have sub-directories for each different test case, QA can just update the pref pointing to the Normandy server and restart Firefox, and they'll receive new recipes for the test case and execute them.

We'll want to document how to use the script to update the test service, and document for QA how to use the test service (e.g. how to change Firefox to trust the dev autograph's signatures, or how to clear out the flags to track if a heartbeat recipe has executed so that they can be run again).

**Comment by Osmose** [comment]
So here's where I'm at: https://github.com/Osmose/normandy-mock-server

The code's more or less ready in terms of being able to generate and upload the correct files to AWS. What I'm stuck on is making it work outside of my own computer, and specifically on CircleCI. Right now my main problem is that I can't find a way to extend normandy-compose's docker-compose config, because:

1. If I combine the files using `-f` when running `docker-compose`, all the paths in the combined file will be relative to the "base" file. I _could_ get around this if I include this in the monorepo and just have the relative volume in the mock-server's config be something like `../mock-server` instead of `.`, which is fine, but sucks.
2. If I try to [extend](https://docs.docker.com/compose/compose-file/#/extends) the `normandy` service, it fails because it has links defined. I could factor out the config to a base file in the normandy-compose repo, and have both the normandy-compose config and the mock-server config extend from that. Alternatively, I could just maintain two similar configs.

Another problem is where the upload to S3 should happen. Currently, I have a script that runs inside the `testgen` container that uploads to S3, but it seems like it'd be better to upload as part of Circle's deploy step, outside the container. The question then becomes: How do I generate the files in the container, and get them back out? Do we just drop them in the root of the mock-repo folder, which is a mounted volume, and pull them from there?

@mythmon @rehandalal @andymikulski Any feedback on the questions and potential solutions above would be appreciated.

**Comment by mythmon** [comment]
I'm not sure about your docker-compose issues. I haven't done anything with extending or combining docker-compose configs. Maybe instead of trying to extend the normandy server config, making an independent Docker image? It could access Normandy via the API (with a link), but I'm not sure how you could use the Python imports. I think you could share the code via volumes as well.

As far as how to get files out of container, I think a good pattern is to mount a separate volume into the repo. That's how the monorepo's linter get the code to lint, and reports it's output.

I think running the actual s3 commands inside a container may be a good idea, so we don't have to set up the environment outside of Docker. Especially in the monorepo, this kind of system isolation is going to prove very useful.

**Comment by Osmose** [comment]
@mythmon Should the files to be deployed be built during the `compile` phase, or the `test` phase? If the build fails in the `compile` phase it will fail the whole run, whereas if they're built in the `test` phase it will continue to run other tests.

**Comment by mythmon** [comment]
If by `compile` phase, you mean `deploy` phase, I think that yeah, the upload to S3 should happen during `deploy`. Especially if artifacts also get stored as build artifacts.

**Comment by Osmose** [comment]
> If by compile phase, you mean deploy phase, I think that yeah, the upload to S3 should happen during deploy. Especially if artifacts also get stored as build artifacts.

I mean the phase when they're _built_, not deployed. I could either use the `compile` phase or the `test` phase, and `compile` seems more like the correct phase; if we had an automated way of checking the built files, that'd go in the `test` phase IMO.

**Comment by mythmon** [comment]
TIL `compile` phase exists. It sounds like a good fit for this. I think we should expect building the files should pass most of the time (whereas uploading to s3 is riskier), so it is fine that it will fail the whole build.

**Comment by Osmose** [comment]
I decided to split out documenting the mock server to #420 so that I can wait until we have a running, functioning mock server before testing and documenting how to use it with the system add-on. I've tested with a finnicky local setup but need to test against a current Nightly with the final mock server.
