### ISSUE TITLE
Simple filters: Active Filters

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#395]
<img width="703" alt="screen shot 2016-12-19 at 4 02 46 pm" src="https://cloud.githubusercontent.com/assets/2767162/21332177/037b296e-c604-11e6-8daa-8328d3fe2647.png">

Mockups can be found here - https://github.com/mozilla/normandy/issues/316#issuecomment-260774698

- [x] Load available filters (locales, names, etc)...
- [x] ...from API
- [x] Display filters in a dropdown list
- [x] Filter dropdown can be filtered by text input
- [x] Clicking a dropdown item (filter) enables that filter
- [x] Typing text into the combobox and hitting 'enter' enables a text filter
- [x] Clicking on an activated filter disables that filter
- [x] Reset button clears all filters
- [x] Upon selecting filter, new recipe list is fetched from API
- [x] Loading message is displayed while loading new recipe list from API
- [x] Cached recipe list is displayed until a new update comes in
- [x] Tests

Bonus objectives:
- [ ] URL updates with filter config (so filter setups can be shared easily)
- [ ] "Displaying _X_ of _Y_ items" text

Reading material:
- [Gist: format for returned filters](https://gist.github.com/andymikulski/e7f281477917bad0183de58127817de5)

**Comment by andymikulski** [comment]
@rehandalal Any thoughts on how the API should consume the various filter params? I'm currently stubbing out code that hits this endpoint: `/api/v1/recipe/?status=disabled&channel=release,aurora&locale=en-uk` - how does that look to you?

**Comment by rehandalal** [comment]
that looks good to me.

i agree about only allowing one text filter at a time.
