### ISSUE TITLE
Simple filters: Recipe Controls

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#396]
<img src="https://cloud.githubusercontent.com/assets/2767162/20534802/c6abccba-b09f-11e6-9e34-c9fa6bac3645.jpg">

- [x] "Multipicker" component
  - [x] Integrate component with redux-form
  - [x] Text search filters remaining options
  - [x] Add all
  - [x] Remove all
  - [x] Display labels but uses values internally
  - [x] ← → buttons
- [x] ~~Detect filter types and create appropriate UI (multipick, checkbox list, datetime, etc)~~
- [x] Compile filters for API
- [x] Read filters applied to existing recipe, apply to page
- [x] Update existing API calls to include new filter values

**Comment by mythmon** [comment]
This style of simple filters isn't something we are going to do.
