### ISSUE TITLE
Redirect users to next study if recipe has been disabled

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#399]
From [bug 1324509](https://bugzilla.mozilla.org/show_bug.cgi?id=1324509):

> When we fill quotas for a study we go in and disable that recipe. Users still continue to enroll in that study as they come online and see the offer. It is my understanding that we can't prevent that on the client side, at least not easily.
>
> I'd like to propose redirecting these users to the next study in line. That way we don't lose sample on a study that has already been filled.

**Comment by mythmon** [comment]
I don't think this correctly describes the current behavior. Further, I think that bucket sampling sort of removes the need for this, as we have more precise control over sampling, and don't have to worry about wasting sample as much.
