### ISSUE TITLE
Test how the add-on sets default preferences.

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#406]
In https://github.com/mozilla/normandy-addon/pull/41 we're changing how we set default prefs to better respect user-set values while still allowing us to update un-changed values. We should have a test for this, but merging that PR soon is important, so this issue exists to track writing the test for it at a later date.

**Comment by mythmon** [comment]
Instead of this work, we're going to use the normal way of using default preferences when we become a Firefox component instead of a system add-on.
