### ISSUE TITLE
Opt-out study specification

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#411]
#323 has links to mockups and info from legal about how the opt-out study should work; this issue covers actually writing and validating the spec with S&I.

**Comment by Osmose** [comment]
@MattGrimes @gregglind Here's the spec for opt-out studies: https://docs.google.com/a/mozilla.com/document/d/1t3vMC9fdLQApmuiR9BPAi05RjS0VVjcsFH3uEcbgNGc/edit?usp=sharing

I left comments in places where I had questions. Can ya'll go through and respond to the questions?

**Comment by MattGrimes** [comment]
Comments have been addressed. I added a couple of questions myself and refrained from answering questions better addressed by @gregglind

**Comment by Osmose** [comment]
I've modified the spec based on feedback, it's pretty much final now. Thanks!
