### ISSUE TITLE
Allow filtering by unique userId in the add-on

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#414]
According to [the spec](http://normandy.readthedocs.io/en/latest/user/filter_expressions.html#normandy.userId), filter expressions should have access to `normandy.userId`, which is a persistent UUID unrelated to any other unique ID, such as the Telemetry ID.

This is a blocker to release. It was originally https://github.com/mozilla/normandy-addon/issues/40 in the add-on repo.

**Comment by mythmon** [comment]
Closed by #441.
