### ISSUE TITLE
Configurable delay for nagging Heartbeat dialogs

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#431]
#429 adds options for how the Heartbeat dialog re-prompts users. The `nag` option re-displays the notification until the user interacts with it in a meaningful way. However, this doesn't include closing the notification with the close button, so they will be re-prompted on startup again if they close the notification.

@MattGrimes has asked that we add the same kind of configurable delay as we have for the `xdays` option. This delay will control how long after a dismissal we should wait before re-prompting. The main use case here is things like prompting Beta users to move to release: we want to prompt them with the option to either decline or go to the Beta download page. If they choose neither and close the prompt, we wait some amount of days, and then re-prompt them.

**Comment by andymikulski** [comment]
Should this be its own configuration, or do we want to alter the `nag` config to take an optional `repeat every x days` field?

**Comment by Osmose** [comment]
With the caveat that I haven't pulled the other PR to see what it looks like yet, it should probably do whatever the `xdays` option does currently for it's delay. It might make sense to make the days config non-optional, and default to 0 if they want "reprompt all the time" behavior.

**Comment by mythmon** [comment]
> Should this be its own configuration, or do we want to alter the nag config to take an optional repeat every x days field?

I think this should be an optional repeat every x days field in the existing configuration.
