### ISSUE TITLE
Telemetry data in the environment is only using archived data

### ISSUE THREAD

**Issue by gijsk** [mozilla/normandy#451]
If a recipe would like to rely on ping data in the telemetry object that we expose, it likely wants the most up-to-date data possible. Archived pings ([which we currently use](https://github.com/mozilla/normandy/blob/master/recipe-client-addon/lib/EnvExpressions.jsm#L36-L57)) are, well, archived, and so maybe we should be looking at including the current ping data as well / instead.

**Comment by mythmon** [comment]
Since Telemetry is only accessible right now in filter expressions (which run shortly after start up) and we don't have plans to change that right now, I think this is OK. I doubt the first five minutes of user activity will produce interesting pings.
