### ISSUE TITLE
Fix commit info in recipe-server Docker  image

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#455]
Since the monorepo merge, the Docker build process for recipe-server no longer has access to the git repo to calculate the commit and tag name. We need this information to deploy.

The problem is these two lines from `Dockerfile`:

```
git rev-parse HEAD > __version__/commit && \
git describe --tags --exact-match > __version__/tag || true # may fail if not on a tag
```

Since the `.git` directory is at the root of the monorepo, which is not part of the Docker context, these commands fail.

It may be ok to fix this only in CI by modifying the CI build scripts. We don't need the version info in non-CI built images, as far as I know.

**Comment by mythmon** [comment]
I planning on moving the calculation of the commit and tag files into `recipe-server/bin/ci/dependencies`, outside of Docker, and have it copied in along with the rest of the app.

@relud I'm curious if you have any other ideas about how we could do this.

**Comment by relud** [comment]
Moving this from the Docker file to the CI build scripts is fine, and it's the only solutionI can think of. if you want non-CI builds to have it then you should script the Docker build command, and instruct people to use the script to build Docker images. regardless, it doesn't matter to me as longs as /__version__ has all the bits when I deploy it.
