### ISSUE TITLE
Cannot create new recipes using control interface (extra_filter_expressions: this field is required)

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#469]
When creating or cloning a recipe in the control interface, the POST to create the recipe return a HTTP 400 and the error `{"extra_filter_expression": ["This field is required."]}`.

**Comment by rayborn** [comment]
Only blocking some testing for now.  Next required recipe change is Monday, but sounds like mythmon thinks the fix will be in tomorrow.  Thanks
