### ISSUE TITLE
Revision status indicator

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#490]
With the additional of approval requests we will now have:
- [x] Approved revisions 
- [x] Draft revisions
- [x] Rejected revisions

In addition to these, there are two special cases:
- [x] The latest draft revision
- [x] The current revision (which is the latest approved revision or the latest draft revision if no approved revisions exist).

We need a visual indicator to let the user know what type of revision they are looking at.

**Comment by andymikulski** [comment]
Fixed in #558
