### ISSUE TITLE
UI for revision history

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#491]
We need to implement UI to show the history of revisions on a recipe. This should:
- [x] Appear alongside the recipe details.
- [ ] Have some way to indicate which revision you are viewing.
- [x] Allow the user to select revisions and have the recipe details populated
- [x] Show icons to indicate the status of each revision (approved, rejected, draft, etc.). ( #490 )

**Comment by andymikulski** [comment]
This is resolved in the new UI which landed in #955 .
