### ISSUE TITLE
Enable reporting of tests to TestRail

### ISSUE THREAD

**Issue by chartjes** [mozilla/normandy#497]
In /recpie-server/contract-tests there is a testrail.cfg.dist file. To enable reporting of results to TestRail, that file needs to be modified and the following values added to it:

* email address for TestRail user (I suggest creating a Normandy-specific one)
* password for TestRail user
* assignedto_id is the TestRail ID for the user

Then the results can be reported by adding the following CLI options to the `pytest` command already being used:

* `--testrail=testrail.cfg` to use the TestRail config file
* `--no-ssl-cert-check` so that Python doesn't complain about the self-signed SSL certificate being used by our TestRail instance

You'll notice that are tests in `test_heartbeat` that have a `@testrail` annotation. Any tests that don't have one already will need one. You can set those test cases up in TestRail itself and then add the necessary annotation.

Happy to answer any questions about all this.

**Comment by shell1** [comment]
Jared is revisiting about automatic testing against the API with Chris.  Will look at the processes and tools that come out of that discussion.   Will close the old issues and see what gets filed (or possibly re-opened) for what is current to focus on - to make sure we do the right things.
