### ISSUE TITLE
Make the last-updated column in the recipe listing more readable

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#505]
The Last Updated column in the recipe listing currently looks like this:

<img width="209" alt="screen shot 2017-02-10 at 10 52 45 am" src="https://cloud.githubusercontent.com/assets/193106/22839643/20df8334-ef7f-11e6-8850-2f1399527aa8.png">

We should probably make it a bit more human readable. The standard practice is to use relative wording for dates, and show the full, readable datetime on hover.

@gregglind @MattGrimes Does relative dates (e.g. "1 day ago") with full dates on hover sound good to ya'll?

**Comment by andymikulski** [comment]
This is resolved in the new UI which landed in #955 .
