### ISSUE TITLE
Add ability to target functional tests against a server environment

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#513]
Currently, the functional tests from #479 are run against a docker-compose instance of the website. Because we want to run these tests during deploys to test newly-deployed environments, we should update the tests so they can be aimed at a specific server environment.

With this, we also need to consider what tests are safe to run in a production server environment, and how to write tests that we can use on a live instance of Normandy without affecting users.

**Comment by mythmon** [comment]
The functional tests have been removed.
