### ISSUE TITLE
Recipe status workflow with peer approval

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#519]
You should not be able to enable a recipe that is not approved.

Disabling a recipe should invalidate the old approvals by setting the `approved_revision` on the recipe to `None`.

**Comment by andymikulski** [comment]
Does this relate to the front end? i.e. do we want to remove/disable the 'enabled' field in the recipe form until approved? Do we need to change the language to be `Published` instead of `Enabled` ? e.g. Draft -> Approved -> Published?

**Comment by Osmose** [comment]
> Does this relate to the front end? i.e. do we want to remove/disable the 'enabled' field in the recipe form until approved? Do we need to change the language to be Published instead of Enabled ? e.g. Draft -> Approved -> Published?

Based on the mockups in https://github.com/mozilla/normandy/issues/287#issuecomment-261647983, the "enabled" field doesn't exist at all; you can only save a draft revision, publish the latest draft revision, or disable the single published revision.

**Comment by rehandalal** [comment]
@andymikulski this was strictly for backend changes. I will file a new issue for the front end changes.
