### ISSUE TITLE
Updating a Heartbeat recipe fails with the HTTP 500 error

### ISSUE THREAD

**Issue by raymak** [mozilla/normandy#522]
the UI prompts the "Recipe cannot be saved. Please correct any errors listed in the form below." error.

**Comment by raymak** [comment]
the UI prompts the "Recipe cannot be saved. Please correct any errors listed in the form below." error.

**Comment by mythmon** [comment]
I'm able to reproduce this on stage and prod, but not locally or with compose. The server response is a 500 with no details (as expected in prod). Nothing is being reported in Sentry, and I don't see anything in the logs on the grep host.

**Comment by Osmose** [comment]
@mythmon Didn't we fix this?

**Comment by mythmon** [comment]
Yeah, this was the error caused by Python 3.6 + new versions of eventlet.

**Comment by 18epedersen** [comment]
I am also encountering this issue after I fill out the recipe form.

I get the error message "Recipe cannot be saved. Please correct any errors listed in the form below."

Steps to reproduce:
1. Name recipe
2. Select locale
3. Click add locale
4. Repeat steps 2 and 3 (I mentioned this in bug https://github.com/mozilla/normandy/issues/609 that you have to add select locale and  click add locale twice before it actually adds the locale.)
5. Select countries
6. Click add countries
7. Repeat steps 5 and 6
8. Checkboxes for release channels (I clicked developer and nightly)
9. Add additional filters (I added the string "true", which were in other recipe examples)
10. Select action (I selected "Log to console" and the message "Hello")
11. Click save
12. Receive error: "Recipe cannot be saved. Please correct any errors listed in the form below."

Thanks so much!
