### ISSUE TITLE
Use LDAP authentication

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#526]
Splitting this off from #286, services ops security wants us to use LDAP for authentication, instead of storing passwords internally as we currently do.

There are no specific requirements as to whether we should build-in LDAP support, or have nginx handle it, and read in user data from an nginx-provided header.

Whichever method we use should integrate with our built-in permissions as they currently are.

**Comment by mythmon** [comment]
CC @relud

**Comment by mythmon** [comment]
With #569 merged and deployed, we are now using Auth0 and LDAP to authenticate users. We are still storing the most recent password the users used. I'll file a separate issue to remove those passwords later.
