### ISSUE TITLE
Bug 1342140 - Show recipe name in breadcrumbs

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#532]
![screenshot-2017-10-18 shield control panel](https://user-images.githubusercontent.com/305049/31735852-efcdf2ec-b3f7-11e7-9501-9eea7b9949e0.png)

The breadcrumbs above show "Recipe" in the breadcrumb spot representing the editing page. It should probably show the name of the recipe instead.

(edit: updated screenshot)

**Comment by mythmon** [comment]
This was a bug in the old control interface, but it applies to the new one as well.

**Comment by mythmon** [comment]
Closing in favor of bug 1342140.
