### ISSUE TITLE
Specify time until Heartbeat prompt is shown again in minutes instead of days

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#536]
Desktop QA mentioned that testing the Heartbeat option for re-showing the prompt after a set amount of days is hard to test because it takes so long. I think we should update the prompt to use minutes instead of days.

<img width="696" alt="screen shot 2017-02-22 at 11 07 37 am" src="https://cloud.githubusercontent.com/assets/193106/23227834/29f91f60-f8ef-11e6-909f-df9863cbbdb6.png">

@MattGrimes @gregglind @andymikulski What do ya'll think of using minutes instead of days?

**Comment by MattGrimes** [comment]
We currently limit to only 1 prompt per day, correct? Switching to minutes seems like it could be dangerous and risk reprompting users aggressively. We could handle that through extra clear communication. Also, maybe give some quick minutes to X conversions in the description for reference.

**Comment by mythmon** [comment]
Minutes is a weird unit to use for the primary use case of this feature. Minutes would have helped QA at one point, but this isn't something we need for ongoing testing. I think this would be more harmful than helpful overall.
