### ISSUE TITLE
normandy.isDefaultBrowser does not work

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#539]
When I create a recipe locally with the filter expression `normandy.isDefaultBrowser`, and DevEdition is set as my default browser, the recipe does not execute. When I invert the expression to `!normandy.isDefaultBrowser`, it gets executed.

Seems like it should be the opposite.

**Comment by mythmon** [comment]
Could this be DevEdition's habit of trying to be a secondary browser? Is this specifically DevEdition? Does this happen on Nightly or Unbranded Beta?

**Comment by Osmose** [comment]
I can reproduce this on a local build of mozilla-central with the latest code (both mozilla-central and our add-on).
