### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#541]
Firefox shows a 404 when it attempts to fetch a favicon for the site. IIRC @designakt made a SHIELD logo that we could use.

Alternatively, a blank image like what http://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests recommends would be fine too. The 404 is mildly confusing because it looks like an error, so we might as well make it go away _somehow_.

**Comment by mastizada** [comment]
Favicon will be always requested even in api view (json text only). Suggestion is stackoverflow is to add html favicon tag with empty base64 image. I think better way will be to add static favicon.ico file and redirect it using webserver configuration or using django url as I did it previously in Pontoon for robots.txt

**Comment by Osmose** [comment]
That's a good point about viewing API views directly (with a browser).

I think your redirect idea is good (`django.contrib.staticfiles.storage.staticfiles_storage.url` should be able to get you the URL for the resource). You'll also want to make sure the redirect view has cache headers for 30 seconds (you should probably add a new setting for this), as we get enough traffic on Normandy that no caching would melt our app servers.

I'm apparently unable to assign the issue to you unless you're a collaborator on the repo, but you should feel free to submit a PR for this issue. Thanks for the help!

**Comment by andymikulski** [comment]
As of #955 we have a favicon asset, set using a simple `link` tag:

```
<link rel="icon" href="{{STATIC_URL}}img/favicon.ico">
```

This meets the front end needs, however I'm 99% sure that doesn't solve the API view business. @mastizada , if you're interested in taking over the django side, you're more than welcome to! Otherwise, this issue can probably be closed.

**Comment by mastizada** [comment]
Hi, for some reason it was in my spam box. Will try to send PR tomorrow, thanks for informing.

**Comment by mastizada** [comment]
@andymckay @mythmon We should test it after deployment and close that issue.

**Comment by mythmon** [comment]
We actually close issues when the code merges. We can re-open if something goes wrong after deployment.
