### ISSUE TITLE
Add-on executing disabled recipes

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#544]
The system add-on is currently downloading and executing recipes that are disabled because it does not filter fetched recipes by their enabled status, nor does it add a filter for the enabled field to its request to the server. The add-on should probably use an enabled filter in the API request to only receive enabled recipes.

**Comment by mythmon** [comment]
Looking at the code in the add-on, it is already correctly adding `?enabled=1` to its requests. The problem is that the server isn't applying filtering to the `/api/v1/recipes/signed/` endpoint.

**Comment by Osmose** [comment]
> Looking at the code in the add-on, it is already correctly adding ?enabled=1 to its requests.

I'm not seeing the `?enabled=1` in my dev server logs. I double checked that querystrings are included in Django dev server logs, so I wonder if the way we're adding that parameter is wrong.

**Comment by mythmon** [comment]
Huh. You're right, they aren't being included. Yay for QA and testing. The server side part also still needs done though.
