### ISSUE TITLE
Circle CI builds suddenly taking much longer

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#549]
Starting with [CircleCI build 1630](https://circleci.com/gh/mozilla/normandy/1630#build-timing), our Circle jobs are taking **much** longer to run. Enough that this is probably a bug.

It looks like all of the extra time is explained by the mock server's compile step jumping from about 1 minute to 45 minutes. I don't see anything obvious in the logs for that step.

@Osmose any ideas?

**Comment by mythmon** [comment]
@vladikoff this issue tracks the long build times you pointed out in #545. Thanks for the heads up.

**Comment by vladikoff** [comment]
👍
