### ISSUE TITLE
Add mock-server test cases for show-heartbeat repeat options

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#565]
The mock-server test cases for `show-heartbeat` don't specify repeat options, and thus all default to only showing once. We should add test cases for each of the repeat options.

Related to Bugzilla [bug 1342444](https://bugzilla.mozilla.org/show_bug.cgi?id=1342444).

**Comment by mythmon** [comment]
Per #1200, we're removing the mock server.
