### ISSUE TITLE
"Show prompt until user interaction" and the 24-hour cutoff for show-heartbeat conflict

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#576]
If a `show-heartbeat` recipe has the repeat option set to "Show prompt until the user interacts with it, then never again", and the user sees a prompt, doesn't interact with it, and then closes and opens Firefox again within 24 hours, the user does not see the prompt because the check for avoiding showing a heartbeat prompt more than once every 24 hours happens first.

What QA (and I) expected was that the repeat option would supersede the 24-hour option and would re-show on reboot.

@MattGrimes @gregglind What is your preferred behavior for this configuration?

**Comment by MattGrimes** [comment]
I think it's fine to wait 24 hours. That is aggressive enough. If we feel the need to be more aggressive down the road we'll have that option available to us. I don't see this as a conflict.

**Comment by Osmose** [comment]
Cool, closing as expected behavior, then. Thanks!
