### ISSUE TITLE
Stop shipping test files

### ISSUE THREAD

**Issue by fqueze** [mozilla/normandy#577]
The following test files are shipped with Firefox since https://hg.mozilla.org/mozilla-central/rev/acd9236e8f36:
resource://shield-recipe-client/test/browser/browser_EnvExpressions.js
resource://shield-recipe-client/test/browser/browser_EventEmitter.js
resource://shield-recipe-client/test/browser/browser_Heartbeat.js
resource://shield-recipe-client/test/browser/browser_LogManager.js
resource://shield-recipe-client/test/browser/browser_NormandyApi.js
resource://shield-recipe-client/test/browser/browser_NormandyDriver.js
resource://shield-recipe-client/test/browser/browser_RecipeRunner.js
resource://shield-recipe-client/test/browser/browser_Storage.js
resource://shield-recipe-client/test/unit/test_Sampling.js
resource://shield-recipe-client/test/unit/xpc_head.js

**Comment by gijsk** [comment]
I think this is because of https://github.com/mozilla/normandy/commit/910227d94b0b381ab52a5e9ddb6c672d9bf7f9a1 . Instead of packaging all the test directory into jar.mn, we should just request Utils.jsm with a file:/// URL or copy the code into the xpc_head.js file.

**Comment by mythmon** [comment]
@gijsk I'm having trouble figuring out a `file:///` URL that points to the utils files, and I can't find any examples on DXR of others doing this. I'd prefer this to using `head.js` files though, so I'd like to get it working. Do you know how I can figure out the right URLs?

**Comment by gijsk** [comment]
If you have a resource URI, I think you can use:

```js
let uri = Services.io.newURI(resourceURIStringSpec)
let fileOrJarURI = Services.io.getProtocolHandler("resource")..QueryInterface(Ci.nsISubstitutingProtocolHandler).resolveURI(uri);
```

https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/res/nsISubstitutingProtocolHandler.idl#38-45

**Comment by mythmon** [comment]
This sort of works, but it returns an absolute path that is specific to my system. Is that expected? I can do this every time I want to import a util function, but this isn't very nice:

```js
const utilsResourceUri = Services.io.newURI("resource://shield-recipe-client/test/browser/Utils.jsm");
const utilsFileUri = Services.io.getProtocolHandler("resource").QueryInterface(Ci.nsISubstitutingProtocolHandler).resolveURI(utilsResourceUri);
Cu.import(utilsFileUri, this); /* globals Utils */
```

Is that what you had in mind?

**Comment by gijsk** [comment]
It's certainly what the previous comment was basically saying, but I think my brain must not have been functioning right. I blame #578. Sorry.

So, the right way to fix this is to add `Utils.jsm` in the support-files instruction of the relevant tests (or maybe just for `[DEFAULT]`) in the `browser.ini` manifest.

Then in the tests (or in a head.js file for that test dir), you can use something like this (untested!):

```js
Cu.import(getRootDirectory(gTestPath) + "Utils.jsm");
```

I'm a bit confused because I think in my earlier comment I thought we were using this file from xpcshell tests, too, but I don't see this happening in my current m-c tree. Am I missing something?

**Comment by gijsk** [comment]
... because if we're only using this from browser tests, a simpler fix would be to rename the file to head.js, and add it to the support-files there. That will global all the stuff in that file automagically when the browser tests are running.

**Comment by mythmon** [comment]
The problem exists for both xpcshell tests and mochi tests, but for different files. We don't share any modules between the two.

I'm really uncomfortable with "global all the stuff in that file automagically". It confuses me, it confuses our linters, and it makes the code harder to read and understand later. I'll stick with the support files.
