### ISSUE TITLE
Driver API for modifying preferences

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#589]
Actions should be able to modify preferences using an API in the driver. Here's a strawman based off of `Preferences.jsm`:

- Set
- Get
- Delete
- Exists
- Is set
- Is user-set

**Comment by mythmon** [comment]
What's the use case for being able to watch for preference changes from an action? I think this isn't something we should copy from `Preferences.jsm`. It will be difficult to get right, and we would have to trust actions to eventually clean up their watchers, or else we'd leak everything.

**Comment by Osmose** [comment]
> What's the use case for being able to watch for preference changes from an action? I think this isn't something we should copy from Preferences.jsm. It will be difficult to get right, and we would have to trust actions to eventually clean up their watchers, or else we'd leak everything.

If a user modifies the preference being used by an experiment, we need to immediately remove them from the experiment and tell telemetry to stop sending data from that user.

There's actually a problem with the spec here, in that if the user modifies the test preference before recipes are executed (internet issues, or just doing it before the 5-minute delay after startup), then nothing will be monitoring the preference and they could be sending telemetry data with them in the experiment but with the wrong preference value. That might be edgy-enough of an edge case that we don't care, though.

**Comment by Osmose** [comment]
> we would have to trust actions to eventually clean up their watchers, or else we'd leak everything.

Couldn't we just track registered watchers in the add-on and clean them up ourselves?

**Comment by mythmon** [comment]
> Couldn't we just track registered watchers in the add-on and clean them up ourselves?

We can do this for when the entire add-on gets removed. I'm more worried about keeping sandboxes alive after recipe execution but while the add-on is loaded. It sounds like that is going to be required though, since the action is going to have a pretty active involvement in the experiment.

Should we lower the 5 minute delay from startup, and instead delay heartbeats by 5 minutes? It sounds beneficial to have these experiments run sooner.

**Comment by Osmose** [comment]
> I'm more worried about keeping sandboxes alive after recipe execution but while the add-on is loaded. It sounds like that is going to be required though, since the action is going to have a pretty active involvement in the experiment.

If we persist the watchers like we probably will be for the persistent timeouts (#591) then we don't need to maintain a sandbox.

> Should we lower the 5 minute delay from startup, and instead delay heartbeats by 5 minutes? It sounds beneficial to have these experiments run sooner.

Hmmmm, I dunno. I'm going to bring up the issue of how accurate we need to be when marking experiment participation with the data team today. They might be able to deal with these issues on the analysis side.

**Comment by Osmose** [comment]
Now that #592 is handling modifying the preferences directly, preference studies don't need this API anymore. We still want this, though.

**Comment by mythmon** [comment]
I don't think this is something we want long term. The action/driver abstraction is going to go away eventually, and this kind of powerful driver API isn't something we have used in the past.
