### ISSUE TITLE
Implement Tox for functional_tests?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/normandy#594]
If there's interest/approval for implementing [Tox](http://tox.readthedocs.io/en/latest/) for the functional_tests directory, I'd volunteer to look at setting that up.

Thoughts @chartjes @mythmon @Osmose ?

**Comment by Osmose** [comment]
IIRC the main benefit of tox is running your tests in multiple environments (like different Python versions), but we only have one environment we care about. What else would tox do for us?

**Comment by chartjes** [comment]
I don't believe this project needs tox support

**Comment by mythmon** [comment]
We could certainly use some better set up tooling and docs, but I don't think Tox is what we need here, since like @Osmose pointed out, we aren't trying to test in many different environments.
