### ISSUE TITLE
Recipe validation depending on its action

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#599]
@gregglind wants some requirements in place for editing preference experiments:

-  Once published, users should be unable to modify the branches of a feature experiment. If they want to add new feature branches, they need to launch a new experiment.
- Feature branch slugs should be unique within an experiment.
- Experiment slugs should be unique.

To support this, we need to be able to validate recipes different depending on their action type.

**Comment by mythmon** [comment]
> Feature branch slugs should be unique within an experiment.

Should feature branch values also be unique within an experiment?

**Comment by gregglind** [comment]
They SHOULD be.

**Comment by mythmon** [comment]
Fixed by #651.
