### ISSUE TITLE
Cannot use about: links in the show-heartbeat Learn More link

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#608]
Bugzilla: [Bug 1346198](https://bugzilla.mozilla.org/show_bug.cgi?id=1346198)

If you try to use an `about:` link as the URL for the "Learn More URL" field in `show-heartbeat` recipes, clicking the link fails with the following error message:

```
11:02:31.696 Error: Cannot open a about: link using the text-link binding. 1 text.xml:328
	open chrome://global/content/bindings/text.xml:328:15
	onxblclick chrome://global/content/bindings/text.xml:377:1
```

**Comment by mythmon** [comment]
The fix here would probably have to be detecting `about:` links and adding our own click handlers to the link to open the correct page.

**Comment by Osmose** [comment]
Adding a `useoriginprincipal` attribute to the element may also fix this; we had to do that for the link to about:studies in about:preferences.

**Comment by mythmon** [comment]
Closing in favor of bug 1346198.
