### ISSUE TITLE
Update Recipe API doesn't update filters

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#609]
New filters (added in #595 ) are not being saved when creating/editing a recipe, though are properly being passed from the front end. Fields include `locales`, `channels`, and `countries`.

You can use the `mozilla/recipe-page-filters` feature branch for your PR.

**Comment by 18epedersen** [comment]
@rehandalal I'm able to save the locales and countries, but I have to add them twice, or else they don't save. 
Steps to reproduce for locales (but also applies to countries):
1. Click on available local (ex. Acholi)
2. Click on "Add Locales" button
The local "Acholi" does not get saved on the selected locales table
3. Click on available local a second time (ex. Acholi)
4. Click on "Add Locales" button
Now "Acholi" gets saved on the selected locales table.
