### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#638]
Sometimes we get non-ascii headers, and DRF doesn't like that. We should handle this more gracefully, and not raise a 500.

https://sentry.prod.mozaws.net/operations/normandy-prod/issues/333793/

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 0: ordinal not in range(128)
(8 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 381, in initial
    neg = self.perform_content_negotiation(request)
  File "rest_framework/views.py", line 296, in perform_content_negotiation
    return conneg.select_renderer(request, renderers, self.format_kwarg)
  File "rest_framework/negotiation.py", line 55, in select_renderer
    for media_type_set in order_by_precedence(accepts):
  File "rest_framework/utils/mediatypes.py", line 44, in order_by_precedence
    precedence = _MediaType(media_type).precedence
  File "rest_framework/utils/mediatypes.py", line 55, in __init__
    self.full_type, self.params = parse_header(media_type_str.encode(HTTP_HEADER_ENCODING))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 0: ordinal not in range(128)
```

**Comment by peterbe** [comment]
It's hard to know but perhaps an upgrade of django-rest-framework might solve this. 

Oh my! We're on 3.6.2 and [a LOT has changed between that and 3.7.7](http://www.django-rest-framework.org/topics/release-notes/)

Perhaps we should park this issue and instead file a new one about not being so behind on django-rest-framework anyway.

**Comment by mythmon** [comment]
I'm good with saving this issue until after we upgrade DRF. I filed #1205 for that.

**Comment by mythmon** [comment]
Sentry issue: [NORMANDY-PROD-35](https://sentry.prod.mozaws.net/operations/normandy-prod/issues/4950648/)

**Comment by shell1** [comment]
server shouldn't respond with 500 (server issue) - should respond with something more useful.  better would be 400 client issue.  

for now - won't fix.  low impact.  Jared can re-evaluate later based on how the dashboard looks and pick-out the higher volume/impact issues.
