### ISSUE TITLE
Inform Telemetry about active preference experiments

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#646]
The preference experiment driver API should inform Telemetry when a preference experiment is active. The API landed in [~~bug 1348748~~](https://bugzilla.mozilla.org/show_bug.cgi?id=1348748) and docs are currently available [here](http://searchfox.org/mozilla-central/source/toolkit/components/telemetry/docs/collection/index.rst). 

It's currently only available on Nightly, but it's on track to be uplifted, so I don't think we need to worry about the API not being available before the preference-experiments feature branch lands on master.

Telemetry doesn't persist this state between sessions, so we need to notify Telemetry both when experiments start and end, and on startup for any in-progress experiments.

**Comment by mythmon** [comment]
The APIs from [bug 1348748](https://bugzilla.mozilla.org/show_bug.cgi?id=1348748) are now available in Beta 53 and above.

**Comment by Osmose** [comment]
Fixed in https://github.com/mozilla/normandy/pull/681.
