### ISSUE TITLE
Expire active preference experiments after 30 days if we can't connect to the service

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#647]
As a last-resort in case a preference experiment breaks something about network access, or the user is away from the network for a significant amount of time, the add-on should expire any preference experiments with a `lastSeen` date older than 30 days. 

@gregglind I think we might actually want to bump this down to something like a week instead of 30 days, as we've almost certainly lost the user by that point if their network access is still broken. Is that okay?

**Comment by gregglind** [comment]
14 days?  I worry 7 is too fast or there will be some weird racing effect
where this gets called first.  Convince me this won't be called by accident
:)

**Comment by Osmose** [comment]
> weird racing effect

Idea: If we only perform this check after an attempt (successful or not) to contact the Normandy server, then we shouldn't ever hit races where we'd disable a recipe before the server told us it was still active unless the user is having network issues, which is the case we're protecting against.

**Comment by mythmon** [comment]
Given the experience we've had with pref studies in the wild since March, I think that this feature isn't necessary anymore.
