### ISSUE TITLE
Title bar buttons link to the wrong URL on revision pages

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#663]
Bugzilla: [Bug 1353747](https://bugzilla.mozilla.org/show_bug.cgi?id=1353747)
Example: https://normandy-admin.stage.mozaws.net/control/recipe/65/revision/3e2bfd54e13d3a760f1ac335c82fd55e162363f6d42a3e268d87603de313fef3

The title bar buttons (Clone, Preview, History) all link to URLs without the recipe ID in them (e.g. https://normandy-admin.stage.mozaws.net/control/recipe/preview/), which has the effect of requiring them to be clicked twice to work. This only applies to the revision-specific pages; recipe pages (https://normandy-admin.stage.mozaws.net/control/recipe/65/) function as expected.

**Comment by rehandalal** [comment]
Redesign makes this invalid.
