### ISSUE TITLE
Recipe preview error message overflows

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#664]
Bugzilla: [Bug 1353741](https://bugzilla.mozilla.org/show_bug.cgi?id=1353741)
Example: https://normandy-admin.stage.mozaws.net/control/recipe/65/preview/

If you try to preview a recipe without the domain of the server in the `browser.uitour.testingOrigins` setting, we display an error asking you to modify it. That error message overflows outside of its box on stage:

<img width="447" alt="screen shot 2017-04-05 at 8 46 09 am" src="https://cloud.githubusercontent.com/assets/193106/24714213/b8095924-19dc-11e7-8e9f-a2f2bc7c7fbc.png">

**Comment by andymikulski** [comment]
This has been corrected with the new UI in #955 .
