### ISSUE TITLE
Cloning a recipe causes a flicker effect on the recipe editing page

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#667]
Bugzilla: [Bug 1354176](https://bugzilla.mozilla.org/show_bug.cgi?id=1354176)

The [video attached to the bug](https://bug1354176.bmoattachments.org/attachment.cgi?id=8855344) shows the effect. It looks like something is up with the state on the recipe editing page after cloning a recipe, causing it to render back and forth between two states.

**Comment by andymikulski** [comment]
This has been corrected with the new UI in #955 .
