### ISSUE TITLE
Disabling a recipe does not remove the approval badge

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#669]
On stage, if I approve and enable a recipe, and then disable it, the approval for that revision should be removed and it should require a new review.

![screen shot 2017-04-06 at 16 19 19-fullpage](https://cloud.githubusercontent.com/assets/193106/24779423/272105ce-1ae5-11e7-8e17-27af731bc951.png)

Currently, after disabling an approved and enabled recipe:

- The "Approved Latest Draft" indicator remains on the page.
- I cannot submit the recipe for review until I save another new draft.

What I expected was:

- The "Approved Latest Draft" indicator would disappear.
- I would be able to submit the revision for review again.

@rehandalal Do my expectations sound right, or am I mistaken?

**Comment by andymikulski** [comment]
This has been corrected with the new UI in #955 .
