### ISSUE TITLE
I have permisssions errors (presumably) when Request Approval is clicked.

### ISSUE THREAD

**Issue by rayborn** [mozilla/normandy#680]
I'm updating recipes 148 - 154 to slightly bump sample.

UI error:"Error creating new approval request." a known issue right now?
Post response error:  {'detail': 'You do not have permission to perform this action.'}

**Comment by mythmon** [comment]
I added "recipes | recipe revision | Can add recipe revision" to the list of permissions the recipe editor group has. I suspect this is the issue.

@rayborn can you try again?

**Comment by rayborn** [comment]
w00t, working!  Thanks
