### ISSUE TITLE
Add driver method to register a preference rollout

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#715]
This driver method will be called by the Rollout action every time the recipe is executed. It should update the list of stored rollouts, and change prefs as needed.

For user branch rollouts, the original preference value should be stored in Storage, with care to detect if no value is set. Aftewards, the rollout value should be set on the user branch.

For default branch rollouts, store the original default value in memory and set the pref on the default branch.

It shouldn't worry about un-enrolling old rollouts, that will be done in another issue.

--

- [x] Update list of stored rollouts when Rollout action is executed
- [x] User branch rollouts should store original pref value in Storage
  - [x] Rollout value should be set on user branch
- [ ] Default branch rollouts should store original default value in memory
  - [x] Rollout value should be set on default branch

**Comment by andymikulski** [comment]
@mythmon For default branches, the ticket says to store the value in memory, whereas user branches get stored in Storage. Wouldn't it make sense to store both in Storage, keyed on rollout name?

**Comment by mythmon** [comment]
My point there was mostly that we don't want the default branch version to persist between restarts. It seemed simpler to store it in memory instead of having to figure out if the value in storage is what we wanted or not.
