### ISSUE TITLE
Re-set rollout preference if they are rolled back

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#717]
If a rollout recipe is no longer applicable to a client, it should roll back. This could happen for several reasons:

* If the recipe is rolled back by lowering the sample rate.
* If the recipe applies to a specific version and the user upgrades or downgrades Firefox.
* If the recipe's filter no longer applies to the user (for example, a geolocation filter and the user changes countries).

All of these are the same to the rollout system. If a particular rollout recipe that was previously known does not execute during a recipe execution cycle, it should be rolled back.

To roll back a user branch rollout, set the user branch value for the preference to it's original setting when the preference started.

To roll back a default branch rollout, set the default branch value for the preference to the value it had when the browser last started up.

**Comment by Osmose** [comment]
Will you need to handle the case of a rollout switching between a default and user pref rollout? Or make that a thing that is not possible in the admin interface?

**Comment by Osmose** [comment]
Also, what happens if a user changes a preference manually in the middle of a rollout? I haven't seen the spec for this (if there is one outside of these issues) so maybe that's covered elsewhere already.

**Comment by mythmon** [comment]
Roll-out will need rethought,  and this issue likely doesn't apply anymore.
