### ISSUE TITLE
Try build fails due to duplicate bootstrap.js

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#718]
A [try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=cf86a39cdddd3f8915d4fcbf4f185b453e2c2275&selectedJob=94368141) of master synced to mozilla-central failed with this message in the logs:

```
[task 2017-04-26T02:30:53.854588Z] 02:30:53     INFO -  ERROR: The following duplicated files are not allowed:
[task 2017-04-26T02:30:53.854756Z] 02:30:53     INFO -  browser/features/shield-recipe-client@mozilla.org/bootstrap.js
[task 2017-04-26T02:30:53.854935Z] 02:30:53     INFO -  browser/features/shield-recipe-client@mozilla.org/chrome/content/bootstrap.js
[task 2017-04-26T02:30:53.855123Z] 02:30:53     INFO -  /home/worker/workspace/build/src/toolkit/mozapps/installer/packager.mk:39: recipe for target 'stage-package' failed
[task 2017-04-26T02:30:53.855274Z] 02:30:53     INFO -  gmake[7]: *** [stage-package] Error 1
```

Looks like this is related to [my changes to jar.mn](https://github.com/mozilla/normandy/commit/3e09dcea8fbeb336e1590b6d0fcd3f78348e3535#diff-7f782ee3d7cb6ae1101b946a214af6fc). I made that change so that `bootstrap.js` could be imported during tests. Apparently the step that finds and eliminates duplicates isn't being run during our TC builds; I can't find anything about it in the logs.

@gijsk Tomorrow I'm going to try and read up on the build system so I can understand what jar.mn actually does (I get that it helps build a jarfile, but I dunno what that jarfile is used for, or how it relates to system add-ons). If you have any links to useful docs, or any ideas on how to fix this failure, I'd appreciate it. :D

**Comment by gijsk** [comment]
It looks like bootstrap.js is now packaged twice. We try to stop people from packaging the same file contents twice because, uh, well, it's wasteful. :-)

It should be possible to import the bootstrap file from a file protocol, I guess, instead of resource:///, but I haven't tested that.
