### ISSUE TITLE
getApiUrl omits trailing slashes

### ISSUE THREAD

**Issue by rnewman** [mozilla/normandy#719]
I see this during late-stage startup on my profile:

```
GET XHR https://self-repair.mozilla.org/api/v1 [HTTP/1.1 301 Moved Permanently 0ms]
GET XHR https://self-repair.mozilla.org/api/v1/ [HTTP/1.1 200 OK 104ms]
…
GET XHR https://self-repair.mozilla.org/api/v1/action/console-log [HTTP/1.1 301 Moved Permanently 0ms]
GET XHR https://self-repair.mozilla.org/api/v1/action/console-log/ [HTTP/1.1 200 OK 53ms]
```

The call stacks, with promise bumpf elided:

```
        apiCall resource://shield-recipe-client/lib/NormandyApi.jsm:42:12
	get resource://shield-recipe-client/lib/NormandyApi.jsm:46:12
	this.NormandyApi.fetchAction< resource://shield-recipe-client/lib/NormandyApi.jsm:136:23
	this.NormandyApi.fetchAction< resource://shield-recipe-client/lib/NormandyApi.jsm:132:30
	this.RecipeRunner.executeRecipe< resource://shield-recipe-client/lib/RecipeRunner.jsm:135:26
	this.RecipeRunner.start< resource://shield-recipe-client/lib/RecipeRunner.jsm:95:17
	this.RecipeRunner.start< resource://shield-recipe-client/lib/RecipeRunner.jsm:84:17
	this.RecipeRunner.start< resource://shield-recipe-client/lib/RecipeRunner.jsm:84:17
	this.RecipeRunner.start< resource://shield-recipe-client/lib/RecipeRunner.jsm:84:17
```

I think there's a missing trailing slash somewhere, causing hundreds of millions of surplus HTTP requests each day. Worth a fix?

**Comment by rnewman** [comment]
(I'm sure Firefox caches the 301, of course, but that doesn't help new users and new URLs, and the dance still has to be done on the client.)

**Comment by mythmon** [comment]
Nice catch! This is definitely worth a fix.

> The call stacks, with promise bumpf elided

Eliding promise bumps sounds like a really nice trick. How did you do that?

**Comment by rnewman** [comment]
> Eliding promise bumps sounds like a really nice trick. How did you do that?

No magic, sadly — I dumped the stack into Vim and deleted a bunch of lines!

It's possible that — given that you use `async`/`await` — the built-in stack tracer will someday do a better job with this. Fingers crossed!
