### ISSUE TITLE
`t is undefined` during Karma test runs

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#738]
When I set up the Karma test runner, the first run happens correctly, but subsequent runs after rebuilds produce the following error:

```
  TypeError: t is undefined
  at client/control/tests/index.js:1
```

If I close down the test runner and restart it, I get another clean run. I suspected this had something to do with my running the webpack watcher in another terminal at the same time, but I get the issue even with it stopped.

**Comment by andymikulski** [comment]
This has to do with setting `NODE_ENV` when we run karma tests. If we change `NODE_ENV=production karma start` to just `karma start`, tests correctly recompile.

I'm not sure where we left off with karma between #918 and #943. I understand the need to run tests against prod, so I'm wondering if we should split the commands into `test:dev`/`test:prod`, where `dev` would watch and `prod` would be a one-shot run.
