### ISSUE TITLE
Global opt-out study control

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#741]
Bugzilla: <strike>[Bug 1370801](https://bugzilla.mozilla.org/show_bug.cgi?id=1370801)</strike> [Bug 1377192](https://bugzilla.mozilla.org/show_bug.cgi?id=1377192)

Opt-out studies are governed by a global opt-out preference that should be visible to users in the Advanced -> Data Choices section of about:preferences:

<img src="https://d3vv6lp55qjaqc.cloudfront.net/items/0M3Q102a0L293z141r2B/Image 2017-01-03 at 11.35.24 AM.png">

In lieu of any better guidance on preference naming (@gijsk?), let's call this pref `app.shield.optoutstudies.enabled`. It should:

- Default to true
- Be displayed as a checkbox below the "Share additional data" checkbox.
- Be set to false if the FHR checkbox is set to false, in the same way the telemetry checkbox is.
  - Open question: Is this visual only, and the prefs keep the same values? And our code just needs to check both prefs? Or do we need to watch the pref value?

In particular, I think we should land this directly in Firefox, instead of adding this checkbox somehow via the system add-on. The preference can be used by the add-on, but doesn't need to disappear if the SHIELD add-on isn't present.

@MattGrimes Do we have copy for this new checkbox? Also, do we need a "Learn More" link, and where should that link to?

**Comment by MattGrimes** [comment]
Copy can be found here: https://docs.google.com/document/d/1v1fmM0ZMRyvToFLAsIzZIlWSAe6bCMlK_75RonDqX8E/edit

The learn more link for other data choices goes to the privacy policy. I'll check with legal to see if we need to add one for Shield Studies or if we can just point to the SUMO page.

**Comment by MattGrimes** [comment]
Ok. Spoke to the lawyers. They want the learn more link to point to the Privacy Policy like the others do. Mika is working on a new Privacy Policy that has bits in it for Shield Studies. If that is live when we hit release, we are good to go. If that is not live, we can update the existing privacy policy. I've already let them know that we need this done by end of quarter, so they'll let us know which option we are rolling with.

**Comment by Osmose** [comment]
@MattGrimes talked with legal and the pref reorg folks and they've agreed to reuse the FHR checkbox; post-reorg the wording will more accurately cover the kind of studying we're doing with opt-out studies.

The remaining work for this bug is making sure that we check the pref before installing opt-out studies. The pref in question is `datareporting.healthreport.uploadEnabled`.

**Comment by Osmose** [comment]
This bug just keeps changing. See [bug 1377192](https://bugzilla.mozilla.org/show_bug.cgi?id=1377192) for most of the details, but the gist of it is now that we need to respect the FHR pref mentioned above as well as add a new checkbox/pref to the new preferences page from our add-on that defaults to true and is also respected. A comment in the bug links to an example of how form autofill does this.

I intend to handle this eventually, but if someone else wants to snatch this up and do the work before I get to it feel free. Just ask me beforehand so I can clarify the required behavior.
