### ISSUE TITLE
trivially capture / target "first run ever in profile" as part of a filter

### ISSUE THREAD

**Issue by gregglind** [mozilla/normandy#742]
1.  If we can do this, this seems like it mostly replaces Funnel Cake
2.  Doing 'first day => 2nd day" and other EARLY retention would be awesome.  

`telemetry.isBrandNew` would solve this.

Claim:  if we target on this, and put people into tagged cohorts, then we can get fast spark retention for free.

**Comment by mythmon** [comment]
This is now available with `normandy.isFirstRun`.
