### ISSUE TITLE
Filtering by add-ons

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#743]
We want to be able to target recipes based on the add-ons that a user has installed. Telemetry may contain this information, but to make filers more readable, and to allow for future expansion, we want to add another API to query the AddonManager directly. Here's my strawman:

```js
// normandy.addons is a map; keys are add-on IDs, and the values are objects
normandy.addons['shield-recipe-client@mozilla.org'] // Truthyness means the add-on is installed

// The value contains version information
normandy.addons['shield-recipe-client@mozilla.org'].version == '1.0.0'
```

One thing that is important to test here is if `[]` syntax for indexing into an object gracefully handles missing keys. I _think_ JEXL actually throws if a key doesn't exist (whereas `.` syntax does not, it just returns `undefined` in all cases). It may be time for us to fork JEXL to change this behavior.

@rayborn @gregglind @MattGrimes Thoughts on the syntax above?

**Comment by mythmon** [comment]
The spec above would be vulnerable to Jexl's `[]` syntax oddities. To work around this, I think we could do something like this:

```jexl
normandy|getAddon('shield-recipe-client@mozilla.org') // truthyness means the add-on is installed
normandy|getAddon('shield-recipe-client@mozilla.org').version == '1.0.0'
```

Fixing the `[]` issue might be a better long term solution though.

**Comment by Osmose** [comment]
> Fixing the [] issue might be a better long term solution though.

I'm inclined to aim for that, if it's not an issue. Using data also allows us to leverage other parts of the language, like filter expressions (no, not that kind). If we had a `|values` filter, for example:

```js
// Find all addons above version 1.0.0
normandy.addons|values[.version > '1.0.0']
```

That's a crap example, but you get the idea. In retrospect I'd like preference filters to work like this too, but oh well.

Thoughts?

**Comment by mythmon** [comment]
Filed #782 to deal with fixing Jexl. Lets tackle that before we go further here.

**Comment by mythmon** [comment]
#767 (which #782 was a dupe of) is fixed now. I think we should go with the original suggestion of an object, `addons`, which has keys of the add-on IDs and values of the type of add-on object we are using in in `driver.addons.get()` (see #747).

In `flow` notation:

```js
/* @flow */
type AddonId = string;
type Addons = {
  [AddonId]: {
    id: AddonId,
    installDate: Date,
    isActive: boolean
    name: string,
    type: "extension" | "theme" | "webextension" | ...,
    version: string,
  }
}
```

@Osmose thoughts?

**Comment by Osmose** [comment]
Sounds good to me!

**Comment by mythmon** [comment]
Waiting for #787 to land before filing this PR.
