### ISSUE TITLE
Rename normandy.experiments filter to normandy.preferenceExperiments

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#744]
After talking with @mythmon, we've decided to not try and put all types of experiments under a single filter expression key. To this end, we should rename the `normandy.experiments` key in filter expressions to `normandy.preferenceExperiments` and update the docs to reflect this. 

We should keep `normandy.experiments` available as an alias for `normandy.preferenceExperiments` until we're confident that it'd be safe to remove.

**Comment by mythmon** [comment]
At this point I think that this kind of breaking change would be too disruptive to do, and isn't something we should do any more.
