### ISSUE TITLE
Filter by native study participation

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#745]
Users should be able to write filter expressions that target users based on what experiments they have participated in and whether they are active or inactive. Here's my strawman API:

```js
// normandy.studies is a mapping; keys are study slugs, and values are objects
normandy.studies['unique-study-name'] // Truthyness checks if the study has ever been seen by the user

// .active returns true or false depending on whether the study is active
normandy.studies['unique-study-name'].active == false 
```

@rayborn @MattGrimes @gregglind Thoughts on the syntax above? Any other info about studies you'd like to filter by?

**Comment by mythmon** [comment]
Is `normandy.studies` a specific enough name for this? Are we going to run into the same issues we are fixing in #744?

**Comment by Osmose** [comment]
> Is normandy.studies a specific enough name for this? Are we going to run into the same issues we are fixing in #744?

Is `normandy.addonStudies` better?

**Comment by mythmon** [comment]
Yeah, lets go with that.

**Comment by Osmose** [comment]
@gregglind @MattGrimes So opt-out studies, as they're currently implemented, no longer have a unique name that's generated by you (based on your feedback that coming up with unique slugs sucks). However, without a unique slug, what should we use to filter by study details?

Or, alternatively: We can filter by add-on ID. We can use that to filter out users already participating in a study if that study is using a study-specific add-on ID. Given that, maybe we don't even need this feature?

**Comment by MattGrimes** [comment]
No longer have a unique name or the slug is generated automatically? I think I'm not following. If you are auto-generating a slug we can just copy whatever was used to find users from that study. add-on ID could work, but I'll let @gregglind ponder the implications on that.

**Comment by Osmose** [comment]
> No longer have a unique name or the slug is generated automatically?

No longer have a unique name. In its place where we need it I'm using the recipe ID, which is unique, but not nearly as human-readable. For add-on studies, we expected the add-on itself to contain the slug that annotates pings in telemetry, so Normandy doesn't actually need to know what the slug is.

If we do want a unique, non-numeric slug, I can add one back in, although I'd be worried about making sure the slug matches what the add-on is telling telemetry the experiment slug is.

**Comment by Osmose** [comment]
Per discussion in the S&I team meeting, we don't need this feature right now.
