### ISSUE TITLE
Add driver functions for reading preferences

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#746]
The opt-out study action will need to check certain preferences to determine if it should install the study add-on or not. We'll need to add an API to the driver for reading preferences.

I think mirroring [Preferences.jsm](https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/Preferences.jsm) on the driver is our best bet:

```js
normandy.preferences.get('foo.bar.baz', 'default_value');
normandy.preferences.has('foo.bar.baz')
normandy.preferences.isSet('foo.bar.baz');
```

@crankycoder How does the API above look to you?

**Comment by Osmose** [comment]
@crankycoder You're working on the Pioneer add-on right now, right? Can someone else take this over while you're working on that? Do you have a branch for them to work on?

**Comment by crankycoder** [comment]
I don't have much to this - just the one commit (including a bad edit to my normandy-base.yml) over here: https://github.com/crankycoder/normandy/commit/f72590e24a7a0d1ced9015b42d5193d629addf53
