### ISSUE TITLE
Store info about installed studies 

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#749]
Users should be able to view a list of current and past studies that they have participated in. To show this, we need to store that data, and keep it up-to-date.

The install function in #748 should, when called, add a new entry to our internal list of studies the user has participated, storing:

- The unique name for the experiment
- The install date
- The study end date (starts off null)
- The add-on ID
- The add-on version
- The add-on description
- The active status of the study (starts off true)

In order to detect when the user removes an add-on, we need to monitor two things:

- If we detect the add-on in question is uninstalled (using the [AddonManager.addAddonListener](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/AddonManager#addAddonListener()) method), we should mark the study as inactive and record the time the study ended. We'll need to register these listeners on startup, similar to what we do for preference experiments.
- If, on startup (before we fetch recipes) we notice that the addon is no longer installed, we should mark the study as inactive and record the time the study ended.

@kmaglione Is IndexedDB, via your promise-based helper, a reasonable place to store this kind of data? Would we be able to ship in 54 (post-release, potentially) if we used IndexedDB.jsm?

If not, then we should consider consolidating the JSON files we're storing in the profile folder (currently two of them) rather than adding yet another one.

**Comment by kmaglione** [comment]
> @kmaglione Is IndexedDB, via your promise-based helper, a reasonable place to store this kind of data? Would we be able to ship in 54 (post-release, potentially) if we used IndexedDB.jsm?

Yes, to both questions. However, you should be aware that you might run into issues if users use the same profile with different Firefox versions with different storage schemas.

**Comment by Osmose** [comment]
@kmaglione Followup question: Are there any performance concerns with reading from IndexedDB during startup? Some of the data we want to store needs to be read during startup (for example, if we stored preference experiments with it, we'd read that at startup to modify preferences before the first window paint).

**Comment by kmaglione** [comment]
Not performance concerns, as such, but the event loop tends to be so busy during startup that, unless you start the query very early, there's a good chance you won't get the response until after firstpaint. But that's also true for just about any other async IO operation.

**Comment by Osmose** [comment]
> Not performance concerns, as such, but the event loop tends to be so busy during startup that, unless you start the query very early, there's a good chance you won't get the response until after firstpaint. But that's also true for just about any other async IO operation.

Good point, thanks.

For this particular feature, I think IndexedDB is fine (the helper I mentioned is [here](http://searchfox.org/mozilla-central/source/toolkit/modules/IndexedDB.jsm)). We don't need to do this immediately at startup, and in [bug 1371350](https://bugzilla.mozilla.org/show_bug.cgi?id=1371350) we're going to split things that happen in `ShieldRecipeClient.jsm` from happening immediately at startup, so the startup methods there are a fine place to register the listeners and check if the add-on was removed between sessions.

**Comment by andymikulski** [comment]
The original issue here outlines using the `install` function in #748 to save active study data (and `uninstall` to alter that data). After discussion with @Osmose, we've decided to alter the approach in that addon installation and 'starting' a study will live as separate functions. This affords us the ability to use un/install addon functions in other actions later.

**Comment by Osmose** [comment]
Fixed in #919.
