### ISSUE TITLE
Add study listing to about:studies

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#751]
The `about:studies` study listing visual design is in [this mildly outdated mockup](https://mozilla.invisionapp.com/share/UC9XM7O9X#/screens/212795383_Experiments_Tab).

Here's the major divergences from that mockup:

- We will be standalone instead of integrated in `about:addons`. We will still have a sidebar (which will eventually list multiple types of studies).
- There will be no search box or settings gear in the top right.
- There will be no "X days remaining" indicator in the listings
- There will be no Preferences buttons for studies.
- There will be no "More" link besides study descriptions.

Here's the spec for listing behavior:

- The list should contain entries for all active and former studies.
  - Study name
  - Study description.
  - Active / Inactive status
- Clicking remove should uninstall the study, and have the same UX as the remove button on the extensions tab.
  - There should be no option to Undo uninstalling the study.
- The add-on details page should only have a button for leaving the study.
- The “Learn More” link at the top should link to a SUMO page describing studies.
- The “Settings” button at the top should open the Advanced -> Data Choices preferences page.

@MattGrimes Do we have final copy for this page?

**Comment by MattGrimes** [comment]
Final copy for this and the data choices page can be found here: https://docs.google.com/document/d/1v1fmM0ZMRyvToFLAsIzZIlWSAe6bCMlK_75RonDqX8E/edit

**Comment by MattGrimes** [comment]
Just as an FYI. We need to get screenshots of the preference panel with the checkbox and the about:studies pages for the SUMO folks. They are putting together an article that explains the program and gives information on how to opt out.

**Comment by Osmose** [comment]
Sevaan has updated the mock: https://mozilla.invisionapp.com/share/UC9XM7O9X#/screens/239894733_Shield_Study

I've updated the original description to note that we're not including the "More" links shown in that mockup. The other modifications (No preferences button, no time remaining indicator) also still apply.

**Comment by Osmose** [comment]
Fixed by #902.
