### ISSUE TITLE
Add study details page to about:studies

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#752]
The [study listing](https://github.com/mozilla/normandy/issues/751) links to details pages for individual studies. This issue covers implementing that page.

The page should be visually similar to the existing add-on detail page in about:addons, with the following changes:

- The page should have no search box or settings gear.
- There should be no control for automatic updates. The desired metadata to display is:
  - Icon
  - Author
  - Name
  - Description
- Studies do not (at least initially) support custom preference controls in the listing.
- Only the "Remove" button should remain for leaving studies.

@MattGrimes Do we have final copy for this page? Specifically the "Remove" button, in case we want to use a different string.

**Comment by MattGrimes** [comment]
Here's my suggestions in order of preference:

- Leave Study
- Disable
- Opt-out

@gregglind do you have a strong preference?

**Comment by MattGrimes** [comment]
Here is the link to the sumo article https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/shield

I have confirmed with the SUMO folks that this link will not change when they migrate back to the newer platform. They are still waiting on us to provide screenshots for them to populate the article.

**Comment by Osmose** [comment]
Upon further discussion, we've decided not to have a details page for each study. The listing page will contain all the functionality we need.
