### ISSUE TITLE
RecipeRunner should monitor enabled/disabled preferences

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#754]
Currently, `RecipeRunner.jsm` checks the `toolkit.telemetry.unified` and `extensions.shield-recipe-client.enabled` preferences once, on startup, and disables itself if either of them is false. This means that changes to those preferences are not reflected in SHIELD until the next session.

Instead, we should register watchers for both of those preferences that enables and disables the recipe runner as needed based on their values.

**Comment by mythmon** [comment]
This would be fixed by #1080 .

**Comment by mythmon** [comment]
#1080 is merged.
