### ISSUE TITLE
implementing a way to get object keys

### ISSUE THREAD

**Issue by raymak** [mozilla/normandy#756]
My use case: targeting users based on their addons. For instance, to target those who have one of the top privacy/security extensions, part of the JEXL would look like this:

normandy.telemetry.main.environment.addons.activeAddons['e67f8350-7edf-11e3-baa7-0800200c9a66@fri-gate.org'] || normandy.telemetry.main.environment.addons.activeAddons['proxytool@proxylist.co'] || normandy.telemetry.main.environment.addons.activeAddons['stealthyextension@gmail.com'] || normandy.telemetry.main.environment.addons.activeAddons['ipfuck@p4ul.info'] || normandy.telemetry.main.environment.addons.activeAddons['jid1-AVgCeF1zoVzMjA@jetpack'] || normandy.telemetry.main.environment.addons.activeAddons['{b749fc7c-e949-447f-926c-3f4eed6accfe}'] || normandy.telemetry.main.environment.addons.activeAddons['{9c51bd27-6ed8-4000-a2bf-36cb95c0c947}'] || normandy.telemetry.main.environment.addons.activeAddons['{455D905A-D37C-4643-A9E2-F6FEFAA0424A}'] || normandy.telemetry.main.environment.addons.activeAddons['useragentoverrider@qixinglu.com'] || normandy.telemetry.main.environment.addons.activeAddons['jid1-5Fs7iTLscUaZBgwr@jetpack'] || normandy.telemetry.main.environment.addons.activeAddons['{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}'] || normandy.telemetry.main.environment.addons.activeAddons['jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack'] || normandy.telemetry.main.environment.addons.activeAddons['{bb6bc1bb-f824-4702-90cd-35e2fb24f25d}'] || normandy.telemetry.main.environment.addons.activeAddons['clickclean@hotcleaner.com'] || normandy.telemetry.main.environment.addons.activeAddons['yesscript@userstyles.org'] || normandy.telemetry.main.environment.addons.activeAddons['requestpolicy@requestpolicy.com'] || normandy.telemetry.main.environment.addons.activeAddons['{9D6218B8-03C7-4b91-AA43-680B305DD35C}'] || normandy.telemetry.main.environment.addons.activeAddons['{2b10c1c8-a11f-4bad-fe9c-1c11e82cac42}'] || normandy.telemetry.main.environment.addons.activeAddons['jid1-dwtFBkQjb3SIQp@jetpack']

Maybe a better way to write this would be:

normandy.telemetry.main.environment.addons.activeAddons|keys|hasAny|['jid1-5Fs7iTLscUaZBgwr@jetpack', '{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}', 'jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack', ...  ]

**Comment by Osmose** [comment]
A `keys` operator to get a list of keys is easy enough. `hasAny` seems a bit unwieldy though.

JEXL allows us to add custom operators, what if we add a new `intersection` operator that computes the intersection between two list-like objects? We could also use the `&` operator, which python uses for that operation. Something like:

```js
normandy.telemetry.main.environment.addons.activeAddons|keys intersect ['addon@mozilla.org']
// or
normandy.telemetry.main.environment.addons.activeAddons|keys & ['addon@mozilla.org']
```

**Comment by raymak** [comment]
Yes, `intersection` sounds good to me.
