### ISSUE TITLE
Show preference experiments in about:support

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#762]
Telemetry experiments are shown in about:support to help QA as well as other teams to diagnose issues with Firefox caused by those experiments:

<img width="821" alt="screen shot 2017-05-16 at 1 45 46 pm" src="https://cloud.githubusercontent.com/assets/193106/26127414/1b09f430-3a3e-11e7-9cd5-849c6ade34aa.png">

Since preference experiments modify Firefox behavior without leaving another visible artifact in about:support (like an add-on), we should figure out how to list ourselves on the page as well.

@bsmedberg Who would end up using this / can help us spec out our requirements? Is it you?

**Comment by bsmedberg** [comment]
This is something that is used by QA to easily check whether an experiment is active during testing.

It is also used by QA and SUMO to help narrow down bugs from users in the field, to determine which setting(s) were active at the time the bug happened.

We want a historical record of prior pref-flip settings (start day, end day, pref name, cohort).

**Comment by mythmon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435905
