### ISSUE TITLE
Double login is a lot of login

### ISSUE THREAD

**Issue by gregglind** [mozilla/normandy#763]
Two-factor VPN and 0Auth seems like a lot of login.  Convince me otherwise :)  I find getting on the VPN is a hassle (especially from mobile devices).   Can we dial that back?  if not, that is fine :)

**Comment by mythmon** [comment]
@relud I heard there was some work on this in the past. Any updates?

**Comment by relud** [comment]
Eventually the vpn login is planned to be replaced by an auth0 portal. The project to do that needs development work, and the people assigned to it on my team are currently busy with other things.

**Comment by mythmon** [comment]
For now, VPN and Auth0 are required for the security profile that we want. This may change in the future with the work that relud alluded to, but for now there isn't anything to do on Normandy for this.
