### ISSUE TITLE
Allow users to approve their own approval requests with a setting

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#764]
To ease development, we want to add a default-on setting that controls whether users are allowed to approve their own approval requests. This will allow developers to save changes to recipes without logging in to a different account, as well as QAs to do so on staging.

**Comment by mythmon** [comment]
I think this should  be default off, and we can turn it on by default in the Development configuration, and we'll flip it on in Stage as well.

@relud is this an ok kind of difference to have between prod and stage?

**Comment by relud** [comment]
i'm fine with it

**Comment by Osmose** [comment]
> I think this should be default off, and we can turn it on by default in the Development configuration, and we'll flip it on in Stage as well.

Sorry, we agree. I had written the setting as controlling enforcement of peer approval rather than controlling the ability to approve your own requests.
