### ISSUE TITLE
Filter Expressions cannot use array syntax on undefined values

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#767]
CC @raymak @MattGrimes : I had to disable Kamyar's add-on bug due to this issue.

In JEXL, if you type in `foo.bar.baz`, and `foo.bar` is undefined, then the entire expression `foo.bar.baz` is returned as undefined, which is desired behavior. However, if you type `foo.bar['baz']`, and `foo.bar` is undefined, JEXL throws an exception. Instead, we'd like it to return undefined as well.

We will commonly run into this with Telemetry filters that use keys that are invalid for dotted-path attributes, like `normandy.telemetry.main.environment.addons.activeAddons['{2b10c1c8-a11f-4bad-fe9c-1c11e82cac42}']`. See [bug 1366125](https://bugzilla.mozilla.org/show_bug.cgi?id=1366125) for an actual example of us running into this in production.

This is a bug in JEXL, and I think it's likely that we'll end up forking JEXL to fix this.

**Comment by mythmon** [comment]
Do we want to preserve filter expressions while fixing this bug? Or should we make [] access the same as dotted access?

**Comment by mythmon** [comment]
We may also run into https://github.com/TechnologyAdvice/Jexl/issues/27, an issue with filter expressions that start with non-letters. We should make sure to test that case.

**Comment by Osmose** [comment]
> Do we want to preserve filter expressions while fixing this bug? Or should we make [] access the same as dotted access?

I dunno... if we fork, I'd honestly prefer a different syntax or even a transform instead of the current override of `[]`, but it may not be worth our time.

In lieu of any more solid plans in that regard, I think we should preserve them.
