### ISSUE TITLE
Need the ability to have silent recipe execution

### ISSUE THREAD

**Issue by rayborn** [mozilla/normandy#784]
Talked to @Osmose about this.  Going to be brief here.

We have a project to compare the ability of Heartbeat messages to change user perceptions.  This involved messaging bucket A then following up some time later with bucket A with a survey about various domains of sentiment.

We want a control bucket.  The initial idea was to simply create a control bucket X, skip the messaging stage, and prompt users with the survey.  However, this means that the control group just has to meet the requirements to be pinged once, whereas our test branches have to meet that requirement twice.  Therefore, tour control users would be a broader group since Heartbeat requires specific behaviors  to be triggered, namely activity and restarts.

@Osmose thinks that this may be possible with existing SysAddon functionality, but we may need to update.

@gregglind will manage the deploys for this project (called "perf .* " in Normandy's front end.

This will also be nice for user config censuses to figure out the addressiblity of various recipes.

[ping FYI @MattGrimes ]

**Comment by Osmose** [comment]
I checked, and there's only one way I can think of to do this without updating the system add-on: We'd have to add a new "marker" recipe that stores data in a known storage namespace, and then update the heartbeat recipe to accept an argument with the name of the marker and have it check that before executing the heartbeat.

I don't think that's a reasonable design unless this is an emergency. 

My suggestion for a design here is to add markers to the telemetry environment that SHIELD can set manually, similar to the experiment markers, but that are persistent. Then we add an action that can set these markers. If they're in Telemetry, then they're filterable by recipes, including Heartbeat. This would also let us, via telemetry, measure the impact of a filter expression by sending out a marker recipe and measuring the number of unique clients who match in telemetry. 

@georgf At first glance, what do you think of that idea? Is maintaining persistent environment markers (maybe with an expiry time?) a non-starter?

**Comment by mythmon** [comment]
I think that the idea of "silent recipe execution" is not the best solution to this problem. Lets keep the original problem (a control group for surveys) in mind when we're expanding the capabilities of experiments.
