### ISSUE TITLE
the approval block elem needs overflow control

### ISSUE THREAD

**Issue by hamilton** [mozilla/normandy#785]
using `pre` here by default won't wrap the text, gets a bit hairy, and possibly might break in awkward ways in other circumstances. Should a `div` work fine in this instance?

<img width="1356" alt="screen shot 2017-05-25 at 4 12 32 pm" src="https://cloud.githubusercontent.com/assets/95735/26474318/2a43d99c-4165-11e7-8272-7b4e78622993.png">

**Comment by jtg567** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/1797418/26608840/88dbce9c-4552-11e7-9090-3a6e8d53539f.png)

**Comment by lonnen** [comment]
@andymikulski -- you want this?

**Comment by andymikulski** [comment]
I think it's safer to wait until the front end refactor is resolved; there's discussion around using a UI library, which would result in this piece just being replaced. In fact, I'm 98% sure this message is removed from this space all together in @Osmose 's new front end, anyway.
