### ISSUE TITLE
No locales, countries, or channels available for simple filters on staging and production

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#794]
On the staging and production servers, the simple filter inputs for filtering by country, locale, and channel, don't have any data in them:

<img width="773" alt="screen shot 2017-06-06 at 2 24 50 pm" src="https://user-images.githubusercontent.com/193106/26852691-f337313e-4ac3-11e7-9b23-e6434462794d.png">

Perhaps we aren't running the management command to pull this data?

@rehandalal Do you want to take this? Given that this is user-facing, I think we should either fix this bug if the fix isn't difficult, or do something to help users understand why the form inputs are in this state.

**Comment by rehandalal** [comment]
Filed bug to run required commands to populate data:
https://bugzilla.mozilla.org/show_bug.cgi?id=1370997

**Comment by rehandalal** [comment]
This was fixed.
