### ISSUE TITLE
Default-branch preference experiments enroll users with user-set values

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#797]
STR:
1. Choose a preference with a default value (e.g. `browser.newtabpage.columns`) and set it to a non-default user-set value. This means the default preference branch has a value, and the user preference branch has a different value.
2. Create a preference experiment recipe for that preference. Set it to use the default preference branch. To illustrate the problem, create a branch with a value different from the default and user-set values from step 1.
3. Execute the recipe. You will be enrolled in the experiment, and the default branch will get a different value. But the user-set value is still in place.

Previously, we discussed this issue and decided that filter expressions can prevent this from happening (by filtering out users who have user-set values for the preferences we want to test). @mythmon and I discussed it some more, and have decided that our default behavior should be to avoid enrolling users with user-set values into experiments on the default preference branch for those prefs.

Our current behavior is fine and should be preserved for all other combinations (default-exp default-value, user-exp user-value, and user-exp default-value).

**Comment by mythmon** [comment]
I *think* this is the same issue that was fixed in [bug 1416003](https://bugzilla.mozilla.org/show_bug.cgi?id=1416003).
