### ISSUE TITLE
Error when running default-branch preference experiments with no default value

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#798]
STR:

1. Open about:config and create a new preference with any value. This means the default branch has no value for the pref, and the user branch has your custom value.
2. Create a preference experiment for that preference. Choose the default branch for the experiment.
3. Execute the recipe.

Expected: The behavior described in #797; either the user is enrolled and the default value changes, or, if that issue is fixed, then the user should not be enrolled.

Actual: An error is logged to the console:

```
1496851566572	extensions.shield-recipe-client.recipe-runner	ERROR	Could not execute recipe asdfa:: Error: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getIntPref] (resource://shield-recipe-client/lib/ActionSandboxManager.jsm:81:13) JS Stack trace: runAsyncCallback@ActionSandboxManager.jsm:81:13
```

Pretty sure this is due to how Preferences.jsm fetches preferences; it checks their type using the nsPrefBranch instance it wraps, and then calls one of the getters. I think the type check is returning the type of the user-set preference, which makes Preferences.jsm skip the logic for returning a default value if a value doesn't exist, and the getters all throw errors if the preference doesn't exist.

**Comment by mythmon** [comment]
I *think* this is the same bug that was fixed in [bug 1416003](https://bugzilla.mozilla.org/show_bug.cgi?id=1416003).
