### ISSUE TITLE
Race condition when validating preference experiment slugs

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#803]
We saw a [KeyError on staging](https://sentry.prod.mozaws.net/operations/normandy-stage/issues/612026/) recently while validating the arguments for a preference experiment. The key was `true?`, which was the value of the slug of the recipe in question, which is weird; we don't use it as a key.

After looking over the validation code, the only thing I noticed that might cause a KeyError was this:

```python
# Experiment slugs should be unique.
experiment_recipes = Recipe.objects.filter(latest_revision__action=self)
existing_slugs = set(r.arguments['slug'] for r in experiment_recipes)
if old_arguments:
    # It is ok if the slug did not change
    existing_slugs.remove(old_arguments['slug'])
```

Sets throw a KeyError if the value you're trying to remove doesn't exist. I _think_ (but cannot reproduce) that there's a race condition here; if the recipe changes during another update request, then the recipes fetched above may have different slugs than the slug passed in via `old_arguments`, leading to the KeyError.

**Comment by shell1** [comment]
only ever saw on staged - likely caused by fuzzing.  likely never hit in real life.  closing unless becomes real issue.
