### ISSUE TITLE
Expose date that a recipe was disabled in the API

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#804]
@sunahsuh wants to know the end date for an experiment, and @gregglind suggested that the date when a recipe was last disabled is a good proxy for that. 

This wouldn't strictly work for experiments that are time-limited by the filter expression itself, but since we don't want enabled recipes to sit around forever, we'd eventually disable those recipes. I think it's a good "I'm done with this experiment" signal.

@sunahsuh, is there a date you need this shipped by?

**Comment by sunahsuh** [comment]
It's not pressing right now, but we'll keep re-running aggregation as long as we get new data tagged with particular experiments, and given what we've seen from TelEx, I think there's a good chance we'll keep getting data long after experiments are over. Not a huge deal until we have more than a handful of experiments but we'll probably want this within a month or so.

**Comment by sunahsuh** [comment]
> we'll probably want this within a month or so.

Coincidentally, it's been exactly a month! Any idea when this might end up in the API?

**Comment by mythmon** [comment]
@sunahsuh Hi! This isn't something we're working on right now, unfortunately.

As a work-around you could probably use the `last_updated` field of a recipe. Recipes don't usually change after they are disabled, so if the recipe is disabled, `last_updated` is probably going to be the last time they were disabled as well. It may over estimate the time span, but at least it provides an upper bound.

**Comment by acmiyaguchi** [comment]
This is relevant to some experiment retention queries I've been looking into. The start date can be inferred from the first time a ping with an experiment slug arrives in the pipeline, but the end date is a bit harder. It sounds like I can use the workaround with a combination of `is_enabled` and `last_updated` field, but it would be useful to have this exposed generally.

**Comment by mythmon** [comment]
One thing to note is that we don't have this data right now. We may be able to add it in the future, but there won't be anyways to backdate this data for old experiments in a 100% reliable way.

**Comment by mythmon** [comment]
This has been exposed in the v3 API for a while, in the `enabled_states` field.
