### ISSUE TITLE
Normandy, first run, tours, and attrition

### ISSUE THREAD

**Issue by gregglind** [mozilla/normandy#817]
## Some known problems (that BY MAGIC might be related):
1. Firefox wants "during firstrun" actions (such as tours, surveys, customization).  
2. Normandy is good at finding people.
3. finding people during first session is currently impossible (because Normandy waits until 2nd reliable run).

## A possible solution:
1.  PATCH FIREFOX such that during every session it records "total.lifetime.sessions".
2.  PATCH NORMANDY to see that flag, so it can act on 0.

## Alternative / Allied work:
- Unified Telemetry is attempting to record FIRST INSTALL for a profile.  

## Side benefits:
1.  Normandy can do things during first run.   it becomes FIREFOX's job to know first run, not normandy's.  No special logic for checking "on second run".
2.  Unified Telemetry gets to count "ever returned" and single / 2nd session.  
3.  We can tailor / experiment with orientation things easily.  Cardboard prototyping!

## Concerns / potential problems
1.  For all the Usual Reasons, if we guess wrong that someone is a 'first run' and get it wrong, we can annoy the user with prompts by accident.  Saving data at client is accident prone.  (we could mitigate / robust this by doing something in the cloud.
2.  Session counts are fingerprintable after a while.  If this is actually a risk, we could turn it into a probabilistic count after 10 sessions or such.

**Comment by mythmon** [comment]
I claim that the capabilities described here are now available in Normandy, and that this issue is complete.
