### ISSUE TITLE
Ability to log out

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#852]
Currently, users have to `/control/logout` in order to log out of the site. This brings up a couple questions:

- Are we still going to use this server-provided logout page? Or are we going to do something like create a React page that hits an API to log out?
- ~redux-little-router `Link` components only allow linking _within_ the React app - it doesn't allow external links. This is only a problem because the `NavigationMenu` is built on `Link`s, and we'd need to find a solve if we intend to use the server's logout page.~ This info is outdated and now irrelevant, as we have changed how the `NavigationMenu` is built.

**Comment by rehandalal** [comment]
We decided to keep using the server-provided logout page.
