### ISSUE TITLE
Re-evaluate filter expressions before making preference changes on startup

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#881]
See [bug 1379627](https://bugzilla.mozilla.org/show_bug.cgi?id=1379627).

- When a preference experiment starts, store the filter expression used to evaluate it.
- Modify the client information we fetch during recipe runs (geolocation and current time) to be cached between runs/
- On startup, before we modify preferences, re-evaluate the filter expression to ensure that it is still valid. If it is not, disable the experiment. If the filters use geolocation or current time, use the cached versions.

Depending on when we do this, we should consider doing this for all experiments, not just preference experiments.

**Comment by mythmon** [comment]
Closing in favor of bug 1379627.
