### ISSUE TITLE
Typo in recipe-client-addon telemetry test

### ISSUE THREAD

**Issue by marcrowo** [mozilla/normandy#905]
[ClientEnvironment.jsm#L109](https://github.com/mozilla/normandy/blob/master/recipe-client-addon/lib/ClientEnvironment.jsm#L109)

`if (mostRecentPings[ping.type].timeStampCreated < ping.timeStampCreated)`
should be:
`if (mostRecentPings[ping.type].timestampCreated < ping.timestampCreated)`

(ie. `timeStampCreated` should be `timestampCreated`)

**Comment by mythmon** [comment]
This was fixed in #1070.
