### ISSUE TITLE
Can't approve a recipe

### ISSUE THREAD

**Issue by 18epedersen** [mozilla/normandy#910]
Steps to reproduce:

1. Click  'new recipe'
2. Fill out 'create new recipe' form
3. Click 'save' button
4. Click 'request approval'
5. Click 'approval request'
6. Click 'approve' 
At this point, the approve button doesn't seem to any effect and I can't self-approve a recipe that I created.

**Comment by 18epedersen** [comment]
When I click on the 'approve' button, I get this error in the console:
TypeError: ze.data is undefined[Learn More]

Also, I am using Nightly 56.0a1 (2017-07-24) (64-bit)

**Comment by rehandalal** [comment]
This is expected behavior. By default we prevent users from being able to self approve. The whole point of approvals is to ensure a second user is required.

**Comment by rehandalal** [comment]
We should however, not be showing the approve/reject buttons if self approval is disabled, so that is a bug.

**Comment by mythmon** [comment]
This is actually a little different: Self approval is enabled on dev, and this behavior also happens when approving someone else's approval request.
