### ISSUE TITLE
'state is undefined' in users/selectors.js

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/normandy#915]
In the user selector here we expect a state object:

https://github.com/mozilla/normandy/blob/redesign/recipe-server/client/control_new/state/app/users/selectors.js#L3

But when we call into it here, we look up a field on the state object (which could be undefined) and pass that in:

https://github.com/mozilla/normandy/blob/redesign/recipe-server/client/control_new/state/app/serviceInfo/selectors.js#L5

Looks like we should just be passing the state?

**Comment by mythmon** [comment]
This was introduced in #914, which I merged before it had gotten enough review.

**Comment by mythmon** [comment]
This was introduced in #897, which I merged before it had gotten enough review.
