### ISSUE TITLE
Import recipe definitions from Experimenter

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/normandy#917]
https://github.com/mozilla/experimenter is a system for managing experiments in Firefox and wants to deploy those experiments using Shield Pref Studies.  To help automate the integration workflow, we can build a menu into the Shield control panel to query the experiment definitions from Experimenter and allow a Shield user to easily import them into the database.  This workflow lets us automate the import process without compromising any of the access control restrictions in place for Shield.

**Comment by mythmon** [comment]
This is a good feature, and definitely something that should exist in the Shield ecosystem. However, Normandy is eliminating all its GUI components in favor of external tools like mozilla/delivery-console. We should talk more about the future of Experimenter's Normandy integration when you have some bandwidth.
