### ISSUE TITLE
Enable CORS on Normandy servers

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#954]
https://normandy.cdn.mozilla.net (our public, read-only address) should add CORS headers allowing anyone to use the data on other web pages.

**Comment by mythmon** [comment]
@rehandalal Want to take a stab at this? In the past I haven't had success doing CORS myself, and using a library has worked well.

**Comment by mythmon** [comment]
This will also need to cover the VPN-protected read-write servers before we can really use the Delivery Console to interface with Normandy.

**Comment by peterbe** [comment]
@mythmon My commit had the suffix "..., fixes #954" but this issue is still open. Is that a deliberate thing?

Any by the way, why doesn't bors squash commits? Now the commit log is a mess :)

**Comment by mythmon** [comment]
I've found that "fixed #954" doesn't work in commit message for some reason, or at least is very finicky. It works much better for me to put it in the PR's body (or the commit body, which shows up in the PR body).

As to squashing commits: Normandy has decided that we prefer to maintain history. Both approaches have pros and cons, and historically the Normandy team decided we prefer this way. Separately from that, bors doesn't support squash merges yet.

**Comment by peterbe** [comment]
Regarding squashing commits; I'll have to try to not say something inappropriate in commit messages as I'm frustrated'ingly committing trial-and-error hacks till tests pass.
