### ISSUE TITLE
Use UpdateUtils.jsm to determine update channel

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#957]
Currently, we use `Services.appinfo.defaultUpdateChannel` to determine the update channel used in filtering. However, this value changes from `beta` to `release` when the RC builds hit the Beta channel. This bit us by preemptively stopping a preference experiment on Beta.

Given that we ship changes to Firefox, we should probably use a more stable indicator for update channel. The update system uses [UpdateUtils.jsm](http://searchfox.org/mozilla-central/source/toolkit/modules/UpdateUtils.jsm) to get the update channel. However, this adds a bunch of extra modifiers to the channel. We should take this into account when figuring out how to write filters with this value:

- Should we add some transforms to compare the base channel?
- Should we manually remove the extra annotations and expose that as the channel value?

@Mossop @gijsk Can one of you double-check my thinking on this?

**Comment by Osmose** [comment]
Oh I totally missed that the partner info is optional and controlled by an argument. Let's ignore all that stuff I mentioned about partners for now.

**Comment by gijsk** [comment]
Yeah, I think you can just use `UpdateUtils.getUpdateChannel(false);` and should be OK? Does that answer your question? :-)
