### ISSUE TITLE
opt-out-study error

### ISSUE THREAD

**Issue by 18epedersen** [mozilla/normandy#960]
After selecting the action 'opt-out-study' action, no dropdown menu of further preferences is shown.

Steps to replicate:
1. Click 'new recipe'
2. Fill out 'create new recipe' form (such as filling out a name and filter expressions)
3. Select opt-out-study

At this point, no further dropdown menu is shown after selecting opt-out-study.

**Comment by Osmose** [comment]
This should be fixed now; the opt-out-study action now shows further UI when being selected.
