### ISSUE TITLE
Filter Expression Autocomplete

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#979]
<img src="https://i.imgur.com/lgDWrzd.gif" height=300 title="Autocomplete Prototype" />

**Description**
Provide users editing the `extra filter expression` field with autocompletion for objects available in the JEXL context (`normandy`, transforms, and operators)

**Goal**
- Eliminate the need to constantly refer to the filter expression docs
- Prevent typos, forgotten arguments, etc, ultimately saving time for the end user

**Level of Effort**
Medium-. The front end library we use has components that come real close to what we want, but the last 10% to nail it is 90% of the work.

**Comment by andymikulski** [comment]
@MattGrimes @gregglind , does this sound like a valuable tool for you and your teams?

**Comment by MattGrimes** [comment]
This sounds extremely handy. Just yesterday rrayborn and i both made the same mistake with normandy.isFirstRun using normandy.FirstRun instead. Autocomplete would have saved a head scratching.
