### ISSUE TITLE
Recipe Identicons (IdentiSHIELDs?)

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#981]
<img src="https://i.imgur.com/iiz6MjC.jpg" title="IdentiSHIELDs Prototype" />

**Description**
Automatically create a visually unique SHIELD/emblem for recipes.

**Goal**
- Provide identifier that is easily rememberable and communicable between end users.

**Level of Effort**
Medium. @mythmon has already done a bulk of the work with regards to creating the prototype shields, which is awesome. The remaining work is implementing them into the site; the shields introduce a new aesthetic element in several places, which would require minor design QA/reworking.

**Comment by bcolloran** [comment]
holy crap these are amazing

**Comment by hamilton** [comment]
Y'all. This is the cutest thing I've literally ever seen.
