### ISSUE TITLE
Listing Pages: Long load times

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#996]
>Note: This is something that has been discussed previously, but I feel needs an actual ticket to track these issues.

Currently, we reload the recipe/extension listing pages every time the user navigates to them. We designed the system this way to prevent stale data from appearing as the latest data. However, this leads us into some UX issues:

- Recipes landing page takes an average of **~3.4s** to load (tracking the `fetchFilteredRecipesPage` call)
  - For reference, 100ms is considered the threshold between whether a user can notice a delay or not
  - Also note, this is when viewing a listing page without any filters applied at all
- UI hangs during loading
  - This prevents clicking ANY interface element until the app is ready.

This UX is pretty subpar IMO - navigating between multiple recipes takes 5s+, even with recently viewed links in the nav (#982)

Things to investigate:
- Handling `_RECEIVED` actions in bulk
  - Currently, hitting the recipes list causes a bunch of `[RECIPE|REVISION]_RECEIVED` actions to fire. I suspect that the approach of iterating over each action plus the use of redux-logger to console.log reduced actions is causing a considerable chunk of the slowdown.
  - There are several redux things we can experiment with, IMO the easiest way is to simply add a `RECIPE_BULK_RECEIVED` or similar, which would update the redux stores in one fell swoop (versus looping over an array and `dispatch`ing a bunch).
- Caching API results
  - Since we want to ensure the data is fresh, caching seems like something that's off the table. However, if we could do something like assign a hash to an API response, we could use that for cachebusting.
  - Ex: user loads recipe listing, gets hash `abc123` back with the data. user does stuff, navigates back to recipe page, hits the _hash only_ endpoint to see that the hash is now `bcd345`, which means it should request the full lookup.
  - With this approach, we at least remove the need for waiting for the listing call to respond, and keep data fresh.

I'm open to ideas on how to approach this, but IMO looking at the redux side of things may help with a good chunk of the slow down.

**Comment by andymikulski** [comment]
Checking out the logger, I notice a few things are getting `dispatch`ed that don't necessarily need to. For instance, `ACTION_RECEIVE` fires on _every_ received recipe, even if the action already exists in the store.

I suspect we could trim these duplicate `dispatch`es and see a performance increase.

**Comment by Osmose** [comment]
How much of that load time is spent making network requests vs processing data client side? Last time I looked into this our API views were pretty inefficient in how they query the database, in some cases ending up with hundreds of unnecessary database queries.

**Comment by mythmon** [comment]
A fair amount o f time is spent waiting on the server, but not all of it. @andymikulski's suggestions still make sense along side server improvements.

We should definitely be disabling Redux Logger in production builds, to avoid the slow down it causes. After this, I imagine bulk loading might help a bit, but will be less impactful. Still worth doing though, if it doesn't hurt maintainability of the code.

The cachebusting technique you describe sounds a lot like etags to me. We may be able to implement that in a performant way, and return `304 Not Modified` if the etag matches. The trick here will be to figure out if the etag matches without making a full request, which would negate most of the benefit it would have provided.

**Comment by mythmon** [comment]
> Last time I looked into this our API views were pretty inefficient in how they query the database, in some cases ending up with hundreds of unnecessary database queries.

The number of database queries has been improved with #1014, which is deployed on prod now. Things still seem sluggish to me, so I think we should move forward with the frontend performance ideas @andymikulski had.

**Comment by andymikulski** [comment]
I've actually got a PR I'm about to put up that cuts the recipe listing/history load times by 40-60%. Turns out `dispatch`ing a bunch of Redux actions is worse than just handling them all in one go.

Thanks for #1014 @mythmon, I'm sure that work combined with my front end fixes will cut the load times down a ton.
